<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <title>TEMBA Statistics – Simple Linear Regression</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-0427d8d92a431aa6a6430e53ec02a470.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Simple Linear Regression</h1>
  <p class="subtitle">TEMBA Statistics 2026</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="sale-prices-and-living-area" class="slide level2">
<h2>Sale prices and living area</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="simple_linear_regression_files/figure-revealjs/viz-houses-scatter-1.png" width="537"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width: 40%; font-size: 0.85em;">
<p>Each point is one of 438 <a href="../notes/appendix_data.html#sec-data-housing-kaggle">homes sold</a> in a single ZIP code in southeast Austin.</p>
<p>A 2,000 sq ft home comes on the market. What price would you predict?</p>
</div></div>
<style>
.reveal .nowrap td, .reveal .nowrap th { white-space: nowrap; }
.reveal .tabletight table { font-size: 0.8em; }
.reveal .mathcol { font-size: 0.6em; }
.reveal .mathcol p { margin: 0.2em 0; }
.reveal .mathcol mjx-container[display="true"], .reveal .mathcol .katex-display { margin: 0.35em 0; }
</style>
<aside class="notes">
<p>These are different homes from the three ZIP codes in Chapter 13, but size and price are about as closely related: r = 0.73 here versus 0.77 there. Take a few guesses. Most people look at the homes near 2,000 sq ft and average them by eye. The line does the same thing in a disciplined way. We come back to this listing in Use 2.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-fitted-line" class="slide level2">
<h2>A fitted line</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="simple_linear_regression_files/figure-revealjs/viz-houses-line-1.png" width="537"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width: 40%; font-size: 0.85em;">
<p>The line runs through the bulk of the data:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\text{price}} = {} &amp; 100{,}771 \\
&amp; + 100.01 \times \text{area}
\end{aligned}
\]</span></p>
<p>We estimated its intercept and slope from these 438 homes.</p>
</div></div>
</section>
<section id="hats-mark-estimates" class="slide level2">
<h2>Hats mark estimates</h2>
<p><span class="math display">\[
\hat y = \hat\beta_0 + \hat\beta_1 x
\]</span></p>
<ul>
<li><span class="math inline">\(\hat\beta_0 = 100{,}771\)</span> estimates the true intercept <span class="math inline">\(\beta_0\)</span>, and <span class="math inline">\(\hat\beta_1 = 100.01\)</span> estimates the true slope <span class="math inline">\(\beta_1\)</span>.</li>
<li>A hat marks a number computed from data, just like <span class="math inline">\(\hat p\)</span> for a sample proportion.</li>
<li><span class="math inline">\(\hat y\)</span> is a predicted value: the height of the line above <span class="math inline">\(x\)</span>.</li>
</ul>
<aside class="notes">
<p>Greek letters are unknown parameters, as in Chapter 8. We’ll write the model that defines beta_0 and beta_1 in a few slides.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fitted-values-and-residuals" class="slide level2">
<h2>Fitted values and residuals</h2>

<img data-src="simple_linear_regression_files/figure-revealjs/viz-residuals-1.png" width="960" class="r-stretch"><p>A <strong>residual</strong> is the observed price minus the <strong>fitted value</strong> on the line. A positive residual means the home sold for more than the line predicts for its size.</p>
<aside class="notes">
<p>The smaller home sold for less than the larger one, but it did better relative to its size. Residuals carry information about everything besides living area: location on the block, condition, age, and so on.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="least-squares-minimizes-the-residual-variance" class="slide level2">
<h2>Least squares minimizes the residual variance</h2>

<img data-src="simple_linear_regression_files/figure-revealjs/viz-least-squares-1.png" width="960" class="r-stretch"><p>Among all possible lines, <strong>least squares</strong> chooses the one whose residuals have the smallest variance.</p>
<aside class="notes">
<p>All three lines pass through the point of averages, so each set of residuals averages zero and the residual variance is the average squared residual. The orange segments are residuals for 70 of the homes. Tilting the line either way makes the typical residual bigger. We won’t derive the minimizing line; software finds it. The criterion is in the notes.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-slope-is-correlation-times-a-ratio-of-sds" class="slide level2">
<h2>The slope is correlation times a ratio of SDs</h2>
<p><span class="math display">\[
\hat\beta_1 = r\,\frac{s_y}{s_x}
= 0.73 \times \frac{72{,}263}{527}
\approx 100 \text{ dollars per sq ft}
\]</span></p>
<ul>
<li>Here <span class="math inline">\(r\)</span> is the correlation from Chapter 13, and <span class="math inline">\(s_x\)</span> and <span class="math inline">\(s_y\)</span> are the standard deviations of area and price.</li>
<li>A home one SD larger than average (527 sq ft) has a predicted price <span class="math inline">\(r = 0.73\)</span> SDs above average.</li>
<li>Two relationships with the same correlation can have different slopes when their outcomes vary by different amounts.</li>
</ul>
<aside class="notes">
<p>0.73 SDs of price is about $52,800. Hang onto the last bullet: it explains the Tesla and Walmart comparison at the end.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="residuals-in-sales-forecasting" class="slide level2">
<h2>Residuals in sales forecasting</h2>
<p>A retailer predicts monthly sales from advertising spend, both in thousands of dollars.</p>
<div class="columns">
<div class="column" style="width:55%;">
<p><span class="math display">\[
\widehat{\text{sales}} = 125 + 3.2 \times \text{advertising}
\]</span></p>
</div><div class="column" style="width:45%;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Month</th>
<th style="text-align: right;">Advertising</th>
<th style="text-align: right;">Sales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>March</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">265</td>
</tr>
<tr class="even">
<td>April</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">275</td>
</tr>
</tbody>
</table>
</div></div>
<ol type="1">
<li>Find the fitted value and residual for each month.</li>
<li>Which month did better relative to what its advertising predicts?</li>
<li>The CFO is worried about April’s negative residual. Was April a bad month?</li>
</ol>
<aside class="notes">
<p>Source: exercise ex-slr-sales-residuals in the notes. Allow three or four minutes.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="residuals-in-sales-forecasting-solution" class="slide level2">
<h2>Residuals in sales forecasting: solution</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Month</th>
<th>Fitted value</th>
<th>Residual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>March</td>
<td><span class="math inline">\(125 + 3.2 \times 40 = 253\)</span></td>
<td><span class="math inline">\(265 - 253 = +12\)</span></td>
</tr>
<tr class="even">
<td>April</td>
<td><span class="math inline">\(125 + 3.2 \times 50 = 285\)</span></td>
<td><span class="math inline">\(275 - 285 = -10\)</span></td>
</tr>
</tbody>
</table>
<p>April had higher sales, but March beat its prediction by $12,000 while April fell $10,000 short.</p>
<p>A negative residual means April sold less than the line predicts for $50,000 of advertising, not that April was a bad month. Residuals average zero, so some months always land below the line.</p>
<aside class="notes">
<p>April’s shortfall could be ordinary month-to-month variation, seasonality, or anything else the model leaves out.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-regression-model" class="slide level2">
<h2>The regression model</h2>
<div class="columns">
<div class="column" style="width:62%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="simple_linear_regression_files/figure-revealjs/viz-model-1.png" width="614"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width: 38%; font-size: 0.85em;">
<p><span class="math display">\[
\begin{gathered}
y = \beta_0 + \beta_1 x + \epsilon \\
\epsilon \sim N(0, \sigma^2)
\end{gathered}
\]</span></p>
<ul>
<li>The line gives the average price of all homes of each size.</li>
<li>Prices of homes the same size are normally distributed around the line.</li>
<li>The standard deviation <span class="math inline">\(\sigma\)</span> is the same at every size.</li>
</ul>
</div></div>
<aside class="notes">
<p>The gray point is one 2,800 sq ft home, and epsilon is its distance from the true line. We drew the picture using our estimates as if they were the truth. In practice we never see the true line.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="estimates-stand-in-for-unknown-parameters" class="slide level2">
<h2>Estimates stand in for unknown parameters</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">True value (unknown)</th>
<th style="text-align: center;">Estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td style="text-align: center;"><span class="math inline">\(\beta_0\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\hat\beta_0 = 100{,}771\)</span></td>
</tr>
<tr class="even">
<td>Slope</td>
<td style="text-align: center;"><span class="math inline">\(\beta_1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\hat\beta_1 = 100.01\)</span></td>
</tr>
<tr class="odd">
<td>SD around the line</td>
<td style="text-align: center;"><span class="math inline">\(\sigma\)</span></td>
<td style="text-align: center;"><span class="math inline">\(s_e = 49{,}443\)</span></td>
</tr>
</tbody>
</table>
<p>The <strong>residual standard error</strong>, <span class="math inline">\(s_e\)</span>, is essentially the SD of the residuals.</p>
<p>Another sample of homes would give different estimates. Standard errors measure how far estimates tend to fall from the truth, as they did for <span class="math inline">\(\bar x\)</span> and <span class="math inline">\(\hat p\)</span>.</p>
</section>
<section id="the-regression-table" class="slide level2 nowrap tabletight">
<h2>The regression table</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<colgroup>
<col style="width: 31%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 23%">
<col style="width: 7%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. error</th>
<th style="text-align: right;">95% CI</th>
<th style="text-align: right;">t</th>
<th style="text-align: left;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: right;">100,771</td>
<td style="text-align: right;">7,923</td>
<td style="text-align: right;">[85,198, 116,343]</td>
<td style="text-align: right;">12.72</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Living area (sq ft)</td>
<td style="text-align: right;">100.01</td>
<td style="text-align: right;">4.48</td>
<td style="text-align: right;">[91.20, 108.83]</td>
<td style="text-align: right;">22.30</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Residual standard error</td>
<td style="text-align: right;">49,443</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">R²</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Observations</td>
<td style="text-align: right;">438</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li class="fragment">Each coefficient comes with a standard error, a 95% confidence interval, and a test of whether its true value is zero.</li>
<li class="fragment">The residual standard error is <span class="math inline">\(s_e\)</span>, our estimate of <span class="math inline">\(\sigma\)</span>.</li>
</ul>
<aside class="notes">
<p>Walk the columns left to right. R-squared comes in Use 3. The software’s intervals differ slightly from estimate plus or minus two SEs because it makes small adjustments for accuracy. Software also reports an adjusted R-squared; it’s bookkeeping that matters only in small samples (see the notes).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section>
<section id="use-1-summarizing-trends" class="title-slide slide level1 center">
<h1>Use 1: Summarizing trends</h1>

</section>
<section id="the-slope-compares-average-prices" class="slide level2">
<h2>The slope compares average prices</h2>

<img data-src="simple_linear_regression_files/figure-revealjs/viz-slope-1.png" width="960" class="r-stretch"><p>Comparing homes that differ by 1,000 sq ft, the larger ones sold for about $100,000 more on average.</p>
<aside class="notes">
<p>Three equivalent readings, from the notes: the line rises $100.01 per square foot; two homes a square foot apart have predicted prices $100.01 apart; and, across many pairs of homes a square foot apart, the larger ones sell for $100.01 more on average. The last one is the model’s reading: each point on the line is the average price of all homes of that size.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-intercept-is-an-extrapolation-here" class="slide level2">
<h2>The intercept is an extrapolation here</h2>

<img data-src="simple_linear_regression_files/figure-revealjs/viz-intercept-1.png" width="960" class="r-stretch"><p>The smallest home in the data has 852 sq ft, so the intercept is an extrapolation to zero square feet with no practical meaning.</p>
<aside class="notes">
<p>Someone usually proposes an empty lot as a zero-square-foot house. Even granting that, zero is far outside the data, and nothing says the line holds down there.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="an-intercept-with-a-meaning" class="slide level2">
<h2>An intercept with a meaning</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="simple_linear_regression_files/figure-revealjs/viz-evals-intercept-1.png" width="537"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width: 40%; font-size: 0.85em;">
<p><a href="../notes/appendix_data.html#sec-data-evals-hamermesh">Course evaluations</a> for 463 UT Austin sections (Hamermesh and Parker, 2005).</p>
<p>Each instructor’s beauty rating is shifted so that 0 is the average rating.</p>
<p>The intercept, 4.00, is the predicted evaluation for an instructor of average beauty.</p>
</div></div>
<aside class="notes">
<p>Six students rated each instructor’s photo. Because beauty has mean zero and the line passes through the point of averages, the intercept is also the average evaluation. Centering area the same way would make the housing intercept the predicted price of an average-sized home; the slope would not change.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="plausible-values-for-the-slope" class="slide level2">
<h2>Plausible values for the slope</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="simple_linear_regression_files/figure-revealjs/viz-slope-ci-1.png" width="537"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width: 40%; font-size: 0.85em;">
<p><span class="math display">\[
\begin{aligned}
&amp;\hat\beta_1 \pm 2\,\text{SE}(\hat\beta_1) \\
&amp;= 100.01 \pm 2(4.48) \\
&amp;\approx [91,\ 109]
\end{aligned}
\]</span></p>
<p>Plausible values for the true slope run from about $91 to $109 per square foot.</p>
<p>A flat line, with slope zero, is far outside that range.</p>
</div></div>
<aside class="notes">
<p>The regression table’s interval, [91.20, 108.83], differs only in the decimals. The dashed lines pivot around the point of averages; they show the range of slopes the data support, not a full band for the line.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="testing-for-a-linear-relationship" class="slide level2">
<h2>Testing for a linear relationship</h2>
<p>A true slope of zero means no linear relationship: the line is flat.</p>
<p><span class="math display">\[
H_0: \beta_1 = 0 \qquad H_A: \beta_1 \neq 0
\]</span></p>
<p><span class="math display">\[
t = \frac{\hat\beta_1 - 0}{\text{SE}(\hat\beta_1)}
= \frac{100.01}{4.48}
\approx 22.3
\]</span></p>
<p>The estimate is about 22 standard errors from zero, so the p-value is far below 0.001. These are the <span class="math inline">\(t\)</span> and p-value in the slope row of the regression table.</p>
<aside class="notes">
<p>The test agrees with the interval: zero is not a plausible slope. The intercept row has its own test of beta_0 = 0, which is of no practical interest here for the reasons on the intercept slide.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="use-2-making-predictions" class="title-slide slide level1 center">
<h1>Use 2: Making predictions</h1>

</section>
<section id="predicting-a-2000-sq-ft-home" class="slide level2">
<h2>Predicting a 2,000 sq ft home</h2>

<img data-src="simple_linear_regression_files/figure-revealjs/viz-prediction-1.png" width="960" class="r-stretch"><p><span class="math display">\[
\widehat{\text{price}} = 100{,}771 + 100.01 \times 2{,}000 \approx \$300{,}791
\]</span></p>
</section>
<section id="a-rough-95-prediction-interval" class="slide level2">
<h2>A rough 95% prediction interval</h2>

<img data-src="simple_linear_regression_files/figure-revealjs/viz-prediction-interval-1.png" width="960" class="r-stretch"><p><span class="math display">\[
\widehat{\text{price}} \pm 2 s_e = 300{,}791 \pm 2 \times 49{,}443
\approx [\$201{,}905,\ \$399{,}677]
\]</span></p>
<p>The model says about 95% of 2,000 sq ft homes sell within <span class="math inline">\(2 s_e\)</span> of the line.</p>
<aside class="notes">
<p>In our data, 93% of the homes fall between the dashed lines. Software computes a slightly more careful interval that also accounts for uncertainty in the line; here it is almost identical.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="three-kinds-of-typical-error" class="slide level2 nowrap">
<h2>Three kinds of typical error</h2>
<table class="caption-top">
<colgroup>
<col style="width: 30%">
<col style="width: 30%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Typical distance</th>
<th style="text-align: right;">Housing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Standard deviation, <span class="math inline">\(s_y\)</span></td>
<td>from prices to their average</td>
<td style="text-align: right;">$72,263</td>
</tr>
<tr class="even">
<td>Standard error, <span class="math inline">\(\text{SE}(\hat\beta_1)\)</span></td>
<td>from <span class="math inline">\(\hat\beta_1\)</span> to the true slope</td>
<td style="text-align: right;">$4.48</td>
</tr>
<tr class="odd">
<td>Residual standard error, <span class="math inline">\(s_e\)</span></td>
<td>from prices to the line</td>
<td style="text-align: right;">$49,443</td>
</tr>
</tbody>
</table>
<p>Which of these would shrink if we had four times as many homes?</p>
<div class="fragment">
<p>The standard error would be about half as large, because the estimate improves with more data. <span class="math inline">\(s_y\)</span> and <span class="math inline">\(s_e\)</span> would stay about the same, because sale prices would be no less variable.</p>
</div>
<aside class="notes">
<p>Take answers before revealing. This distinction drives most of the confusion about regression output: a tiny SE for the slope says the line is well estimated, not that predictions for individual homes are precise.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="extrapolation" class="slide level2">
<h2>Extrapolation</h2>

<img data-src="simple_linear_regression_files/figure-revealjs/viz-extrapolation-1.png" width="960" class="r-stretch"><p>We fit the line to homes from 852 to 3,319 sq ft. These data tell us nothing about how prices behave for a 10,000 sq ft home.</p>
<aside class="notes">
<p>Price per square foot for luxury properties can look quite different, and they sit in different neighborhoods. The intercept slide was the same problem at the other end of the line.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="use-3-measuring-strength" class="title-slide slide level1 center">
<h1>Use 3: Measuring strength</h1>

</section>
<section id="predicting-with-and-without-living-area" class="slide level2">
<h2>Predicting with and without living area</h2>

<img data-src="simple_linear_regression_files/figure-revealjs/viz-null-vs-line-1.png" width="960" class="r-stretch"><p>The colored homes are the same in both panels. Which set of prediction errors is smaller?</p>
<aside class="notes">
<p>We’ll call the left panel the null model: it forces the slope to zero, matching the null hypothesis beta_1 = 0.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="prediction-errors-with-and-without-living-area" class="slide level2">
<h2>Prediction errors with and without living area</h2>

<img data-src="simple_linear_regression_files/figure-revealjs/viz-error-histograms-1.png" width="960" class="r-stretch"><p>Using living area shrinks the typical prediction error from $72,263 to $49,443.</p>
</section>
<section id="each-homes-price-splits-into-two-parts" class="slide level2">
<h2>Each home’s price splits into two parts</h2>
<div class="columns">
<div class="column" style="width:68%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="simple_linear_regression_files/figure-revealjs/viz-house-decomposition-1.png" width="806"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:32%;">
<div style="height: 6em">

</div>
<div style="font-size: 1.5em;">
<p><span class="math display">\[{\color{#0072B2}y} = {\color{#009E73}\hat y} + {\color{#D55E00}e}\]</span></p>
</div>
</div></div>
<aside class="notes">
<p>The two homes from the residuals slide. Each price is the line’s prediction for a home that size plus a residual: the part of the price that size alone doesn’t predict.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="variance-splits-the-same-way" class="slide level2">
<h2>Variance splits the same way</h2>
<div class="columns">
<div class="column" style="width:71%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="simple_linear_regression_files/figure-revealjs/viz-house-variance-split-1.png" width="902"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:29%;">
<div class="mathcol">
<p><span class="math inline">\(\text{Var}({\color{#0072B2}y}) = \text{Var}({\color{#009E73}\hat y}) + \text{Var}({\color{#D55E00}e})\)</span></p>
<div style="height: 0.6em">

</div>
<p>In thousands of dollars:</p>
<p><span class="math display">\[{\color{#0072B2}72.3^2} \approx {\color{#009E73}52.8^2} + {\color{#D55E00}49.4^2}\]</span> <span class="math display">\[
\begin{aligned}
R^2 &amp;= ({\color{#009E73}52.8} / {\color{#0072B2}72.3})^2 \\
    &amp;= 1 - ({\color{#D55E00}49.4} / {\color{#0072B2}72.3})^2 \\
    &amp;= 0.53
\end{aligned}
\]</span></p>
</div>
</div></div>
<aside class="notes">
<p>Standard deviations don’t add; variances do, because the fitted values and the residuals are uncorrelated. R-squared is the share of the variance in prices that the line predicts from size.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="r2-measures-the-reduction-in-prediction-variance" class="slide level2">
<h2><span class="math inline">\(R^2\)</span> measures the reduction in prediction variance</h2>
<ul>
<li>Using living area cuts the variance of our prediction errors by about 53%.</li>
<li><span class="math inline">\(R^2\)</span> is also the squared correlation: <span class="math inline">\(0.73^2 \approx 0.53\)</span>.</li>
<li>An <span class="math inline">\(R^2\)</span> of 0 means the line predicts no better than the average; an <span class="math inline">\(R^2\)</span> of 1 means every point sits on the line.</li>
</ul>
<aside class="notes">
<p>“Explained” in “proportion of variance explained” really means “predicted.” Predicting size from price gives exactly the same R-squared.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-low-r2-does-not-mean-no-relationship" class="slide level2">
<h2>A low <span class="math inline">\(R^2\)</span> does not mean no relationship</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="simple_linear_regression_files/figure-revealjs/viz-evals-weak-1.png" width="537"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width: 40%; font-size: 0.85em;">
<p><span class="math inline">\(R^2 = 0.036\)</span>: beauty predicts about 4% of the variation in evaluations.</p>
<p>The 95% CI for the slope is [0.07, 0.20], and <span class="math inline">\(t = 4.1\)</span>.</p>
<p>The data give strong evidence of a weak linear relationship.</p>
</div></div>
<aside class="notes">
<p>Knowing beauty barely changes the typical error: 0.55 points without it and 0.55 with it. Clarity and fair grading almost surely matter more, and they end up in the residuals. Whether there is a linear relationship is a question about the slope, not about R-squared.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="r2-and-the-size-of-prediction-errors" class="slide level2">
<h2><span class="math inline">\(R^2\)</span> and the size of prediction errors</h2>
<p>A logistics company predicts weekly delivery costs from the number of shipments. The model has <span class="math inline">\(R^2 = 0.77\)</span> and <span class="math inline">\(s_e = \$3{,}200\)</span>. Weekly costs have a standard deviation of <span class="math inline">\(s_y = \$6{,}700\)</span>.</p>
<p>The CFO says, “An <span class="math inline">\(R^2\)</span> of 0.77 seems low. I don’t want forecasts that miss by more than $7,000 very often.”</p>
<ol type="1">
<li>How much smaller is the typical prediction error using shipments than predicting the average cost every week?</li>
<li>Is the model precise enough for the CFO?</li>
</ol>
<aside class="notes">
<p>Source: exercise ex-slr-rsquared-interpretation in the notes. Allow three minutes.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="r2-and-the-size-of-prediction-errors-solution" class="slide level2">
<h2><span class="math inline">\(R^2\)</span> and the size of prediction errors: solution</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Typical prediction error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Predicting the average cost</td>
<td style="text-align: right;">$6,700</td>
</tr>
<tr class="even">
<td>Using shipments</td>
<td style="text-align: right;">$3,200</td>
</tr>
<tr class="odd">
<td>Reduction</td>
<td style="text-align: right;">$3,500</td>
</tr>
</tbody>
</table>
<p>A $7,000 miss is <span class="math inline">\(7{,}000 / 3{,}200 \approx 2.2\)</span> residual standard errors. Misses that large should happen in fewer than 5% of weeks, so the model meets the CFO’s standard.</p>
<p><span class="math inline">\(R^2\)</span> is a relative measure. To judge the size of errors in dollars, look at <span class="math inline">\(s_e\)</span>.</p>
</section></section>
<section>
<section id="use-4-adjusted-comparisons" class="title-slide slide level1 center">
<h1>Use 4: Adjusted comparisons</h1>

</section>
<section id="do-two-story-homes-sell-for-more" class="slide level2">
<h2>Do two-story homes sell for more?</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">One-story</th>
<th style="text-align: right;">Two-story</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Homes</td>
<td style="text-align: right;">284</td>
<td style="text-align: right;">154</td>
</tr>
<tr class="even">
<td>Average price</td>
<td style="text-align: right;">$252,500</td>
<td style="text-align: right;">$300,700</td>
</tr>
<tr class="odd">
<td>Average living area</td>
<td style="text-align: right;">1,468 sq ft</td>
<td style="text-align: right;">2,090 sq ft</td>
</tr>
</tbody>
</table>
<p>Two-story homes sold for about $48,200 more on average. They are also about 622 sq ft larger.</p>
<p>How much of the $48,200 is size?</p>
</section>
<section id="comparing-homes-of-the-same-size" class="slide level2">
<h2>Comparing homes of the same size</h2>

<img data-src="simple_linear_regression_files/figure-revealjs/viz-stories-1.png" width="1152" class="r-stretch"><p>At the same living area, two-story homes sold for about $14,000 <em>less</em> on average.</p>
<aside class="notes">
<p>Hand check from the table: the extra 622 sq ft adds 622 x $100 = $62,200 to the predicted price, and $48,200 - $62,200 is about -$14,000. The raw premium was size, and then some. This compares homes of the same size; it is not a claim about what adding a second story would do.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="size-is-not-the-only-difference" class="slide level2">
<h2>Size is not the only difference</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">One-story</th>
<th style="text-align: right;">Two-story</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Median age (years)</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">9.5</td>
</tr>
<tr class="even">
<td>Average bathrooms</td>
<td style="text-align: right;">2.1</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="odd">
<td>Average bedrooms</td>
<td style="text-align: right;">3.1</td>
<td style="text-align: right;">3.6</td>
</tr>
</tbody>
</table>
<p>A line in size alone cannot hold these fixed, so the residuals still mix them into the comparison. <strong>Multiple regression</strong> compares homes that match on several characteristics at once.</p>
</section></section>
<section>
<section id="case-study-the-market-model" class="title-slide slide level1 center">
<h1>Case study: The market model</h1>

</section>
<section id="the-market-model-r-alpha-beta-r_m-epsilon" class="slide level2">
<h2>The market model: <span class="math inline">\(R = \alpha + \beta R_M + \epsilon\)</span></h2>

<img data-src="simple_linear_regression_files/figure-revealjs/viz-beta-lines-1.png" width="960" class="r-stretch"><p><strong>Beta</strong> is the slope: a stock’s average move per 1% move in the market. <strong>Alpha</strong> is the intercept: its average return when the market is flat.</p>
<aside class="notes">
<p>Alpha and beta are finance’s names for beta_0 and beta_1. R is the stock’s return, R_M the market’s, and epsilon the stock-specific part of the return. Beta above 1 amplifies market swings in both directions; below 1 dampens them.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="tesla-and-ford" class="slide level2">
<h2>Tesla and Ford</h2>

<img data-src="simple_linear_regression_files/figure-revealjs/viz-tesla-ford-prompt-1.png" width="960" class="r-stretch"><p>Each point is one week of <a href="../notes/appendix_data.html#sec-data-returns-2025">returns</a>, October 2023 to September 2025; the market is the S&amp;P 500 (SPY). The dashed line has slope 1.</p>
<p>Which stock amplifies market moves? Roughly what is each beta?</p>
<aside class="notes">
<p>Pause here and take guesses before moving on.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="software-tests-beta-0" class="slide level2 nowrap tabletight">
<h2>Software tests <span class="math inline">\(\beta = 0\)</span></h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. error</th>
<th style="text-align: right;">t</th>
<th style="text-align: right;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: right;">-0.02</td>
<td style="text-align: right;">0.72</td>
<td style="text-align: right;">-0.03</td>
<td style="text-align: right;">0.980</td>
</tr>
<tr class="even">
<td style="text-align: left;">Market return</td>
<td style="text-align: right;">1.87</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">5.60</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Residual standard error</td>
<td style="text-align: right;">7.19</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">R²</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Observations</td>
<td style="text-align: right;">104</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Returns in percent. When the market moves 1%, Tesla moves about 1.87% on average. The intercept, <span class="math inline">\(\hat\alpha\)</span>, is small next to its standard error.</p>
<p>The <span class="math inline">\(t\)</span> of 5.60 tests <span class="math inline">\(\beta = 0\)</span>. For a stock, the more useful question is whether <span class="math inline">\(\beta = 1\)</span>.</p>
<aside class="notes">
<p>Nobody doubts that Tesla moves with the market. The question an investor cares about is whether it moves more than one-for-one.</p>
<p>The 95% intervals for alpha are about [-1.46, 1.43] for Tesla and [-1.06, 0.58] for Ford, percent per week.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="is-teslas-beta-different-from-1" class="slide level2 nowrap">
<h2>Is Tesla’s beta different from 1?</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Stock</th>
<th style="text-align: center;"><span class="math inline">\(\hat\beta\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\hat\beta \pm 2\,\text{SE}\)</span></th>
<th style="text-align: center;">Is 1 plausible?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tesla</td>
<td style="text-align: center;">1.87</td>
<td style="text-align: center;">[1.20, 2.54]</td>
<td style="text-align: center;">No</td>
</tr>
<tr class="even">
<td>Ford</td>
<td style="text-align: center;">0.98</td>
<td style="text-align: center;">[0.60, 1.36]</td>
<td style="text-align: center;">Yes</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
t = \frac{\hat\beta - 1}{\text{SE}(\hat\beta)}
= \frac{1.873 - 1}{0.335}
\approx 2.61,
\qquad \text{p-value} \approx 0.009
\]</span></p>
<p>We have good evidence that Tesla amplifies market moves. Ford’s estimate is just under 1, and the data are consistent with a beta of 1.</p>
</section>
<section id="similar-r2-different-betas" class="slide level2">
<h2>Similar <span class="math inline">\(R^2\)</span>, different betas</h2>

<img data-src="simple_linear_regression_files/figure-revealjs/viz-tesla-walmart-1.png" width="960" class="r-stretch"><p>Both correlations with the market are about 0.48.</p>
<aside class="notes">
<p>This is the payoff of the slope formula from the start of the lecture: same r, different s_y, different slope. R-squared is a relative measure, so the two stocks can share it while Tesla’s residuals are far larger: s_e = 7.19% versus 2.59%.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="each-weeks-return-splits-into-two-parts" class="slide level2">
<h2>Each week’s return splits into two parts</h2>
<div class="columns">
<div class="column" style="width:68%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="simple_linear_regression_files/figure-revealjs/viz-tesla-decomposition-1.png" width="806"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:32%;">
<div style="height: 6em">

</div>
<div style="font-size: 1.5em;">
<p><span class="math display">\[{\color{#0072B2}y} = {\color{#009E73}\hat y} + {\color{#D55E00}e}\]</span></p>
</div>
</div></div>
<aside class="notes">
<p>Two weeks of Tesla returns. The week ending April 26, 2024, the market rose 2.6%; the line predicted 4.9% for Tesla and it returned 14.4%, a residual of 9.5%. The week ending October 20, 2023, the market fell 2.4%; the line predicted a 4.5% loss and Tesla lost 15.6%. Every week splits this way: a market part on the line, plus a stock-specific part off it.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="variance-splits-the-same-way-1" class="slide level2">
<h2>Variance splits the same way</h2>
<div class="columns">
<div class="column" style="width:71%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="simple_linear_regression_files/figure-revealjs/viz-variance-split-1.png" width="902"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:29%;">
<div class="mathcol">
<p><span class="math inline">\(\text{Var}({\color{#0072B2}y}) = \text{Var}({\color{#009E73}\hat y}) + \text{Var}({\color{#D55E00}e})\)</span></p>
<div style="height: 0.6em">

</div>
<p><span class="math display">\[{\color{#0072B2}8.17^2} \approx {\color{#009E73}3.96^2} + {\color{#D55E00}7.15^2}\]</span> <span class="math display">\[
\begin{aligned}
R^2 &amp;= ({\color{#009E73}3.96} / {\color{#0072B2}8.17})^2 \\
    &amp;= 1 - ({\color{#D55E00}7.15} / {\color{#0072B2}8.17})^2 \\
    &amp;= 0.23
\end{aligned}
\]</span></p>
<div style="height: 1.4em">

</div>
<p><span class="math display">\[{\color{#0072B2}2.94^2} \approx {\color{#009E73}1.40^2} + {\color{#D55E00}2.58^2}\]</span> <span class="math display">\[
\begin{aligned}
R^2 &amp;= ({\color{#009E73}1.40} / {\color{#0072B2}2.94})^2 \\
    &amp;= 1 - ({\color{#D55E00}2.58} / {\color{#0072B2}2.94})^2 \\
    &amp;= 0.23
\end{aligned}
\]</span></p>
</div>
</div></div>
<aside class="notes">
<p>Standard deviations don’t add; variances do, because the market part and the residual are uncorrelated. Beta sets how much market risk a stock carries: Tesla’s market part is almost three times as wide as Walmart’s. R-squared is the market’s share of the total, and it is the same for both. Diversification can only shrink the orange part.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="similar-betas-different-r2" class="slide level2">
<h2>Similar betas, different <span class="math inline">\(R^2\)</span></h2>

<img data-src="simple_linear_regression_files/figure-revealjs/viz-apple-ford-1.png" width="960" class="r-stretch"><p>Apple and Ford both move about one-for-one with the market on average. Ford’s returns scatter more around its line, so the market predicts less of their variation.</p>
<aside class="notes">
<p>Beta tells us whether a stock amplifies or dampens market moves. R-squared tells us what share of its week-to-week variation the market predicts.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="abnormal-returns-are-residuals" class="slide level2">
<h2>Abnormal returns are residuals</h2>

<img data-src="simple_linear_regression_files/figure-revealjs/viz-tesla-residuals-1.png" width="960" class="r-stretch"><p>A residual is Tesla’s return minus what the market model predicts for that week. Finance calls it an <strong>abnormal return</strong>. The dashed lines are two SDs above and below zero.</p>
<aside class="notes">
<p>With no news at all we’d expect about 5% of weeks, roughly 5 of 104, outside the dashed lines; 6 are. The largest, the week of October 24, 2024, followed a strong third-quarter earnings report. Others line up with the July 2024 delivery numbers, the June 2025 Musk-Trump spat, the January 2024 growth warning, the October 2024 robotaxi event, and the rally after the 2024 election. Sources are linked in the notes. Not every extreme residual has a tidy explanation, and news rarely accounts for all of one.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>