<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>16&nbsp; Sampling Distributions and Confidence Intervals – TEMBA Statistics — Course Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./inference_02_hypothesis-tests.html" rel="next">
<link href="./prob_10_sums-averages-clt.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d3f7f8e73c8d287b30bcf59c2b563615.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/foldbox/foldbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>
.Exercise {
  --color1: #E7F4F5;
  --color2: #147D85;
}
.Example {
  --color1: #F4EFEA;
  --color2: #80644D;
}
.Definition {
  --color1: #F4EAF0;
  --color2: #7C3F58;
}
.TechnicalDetail {
  --color1: #EEF1F3;
  --color2: #5B6770;
}
.Notation {
  --color1: #EEF1F3;
  --color2: #5B6770;
}
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles/callouts.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./inference_01_sampling-distributions.html">Statistical Inference</a></li><li class="breadcrumb-item"><a href="./inference_01_sampling-distributions.html"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Sampling Distributions and Confidence Intervals</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">TEMBA Statistics — Course Notes</a> 
        <div class="sidebar-tools-main">
    <a href="./../index.html" title="Course site" class="quarto-navigation-tool px-1" aria-label="Course site"><i class="bi bi-house-door"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Data analysis and visualization for one variable</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_01_visualizing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Visualizing a Single Quantitative Variable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_02_describing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Distributions of Quantitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_03_location-and-spread.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Measuring Location and Spread</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_04_transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Transforming Quantitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_05_categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Categorical Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Probability for one variable</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_01_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introduction to Probability and Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_02_probability-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Probability Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_03_distribution-parameters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Measures of Location and Spread (and Other Parameters of Probability Distributions)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_04_normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">The Normal Distribution</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Data analysis, visualizations, and probability models for multiple random variables</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_05_multivariate-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Joint, Marginal, and Conditional Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_06_probability-trees-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability Trees, Total Probability, and Bayes’ Rule</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_07_independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Independence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_08_quantitative-quantitative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Visualizing and Summarizing Two Quantitative Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Combining Random Variables</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_09_combining-random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Combining Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_10_sums-averages-clt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Sums, Averages, and the Central Limit Theorem</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_01_sampling-distributions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Sampling Distributions and Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_02_hypothesis-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Hypothesis Tests and p-values</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_03_limits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">The Limits of Statistical Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_04_proportions-comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Proportions and Comparisons Between Groups</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./case_triangle-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Case Study: Can Customers Taste the Difference?</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-sap-dispute" id="toc-sec-sap-dispute" class="nav-link active" data-scroll-target="#sec-sap-dispute"><span class="header-section-number">16.1</span> The SAP dispute</a></li>
  <li><a href="#sec-sampling-ci" id="toc-sec-sampling-ci" class="nav-link" data-scroll-target="#sec-sampling-ci"><span class="header-section-number">16.2</span> Sampling distributions and confidence intervals</a>
  <ul class="collapse">
  <li><a href="#sec-app-walkthrough" id="toc-sec-app-walkthrough" class="nav-link" data-scroll-target="#sec-app-walkthrough"><span class="header-section-number">16.2.1</span> Simulating the sampling distribution</a></li>
  <li><a href="#sec-ci" id="toc-sec-ci" class="nav-link" data-scroll-target="#sec-ci"><span class="header-section-number">16.2.2</span> Accounting for sampling error when presenting results</a></li>
  </ul></li>
  <li><a href="#sec-sampling-practice" id="toc-sec-sampling-practice" class="nav-link" data-scroll-target="#sec-sampling-practice"><span class="header-section-number">16.3</span> Practice</a></li>
  <li><a href="#sec-bootstrap" id="toc-sec-bootstrap" class="nav-link" data-scroll-target="#sec-bootstrap"><span class="header-section-number">16.4</span> The bootstrap</a></li>
  <li><a href="#sec-sampling-practice-more" id="toc-sec-sampling-practice-more" class="nav-link" data-scroll-target="#sec-sampling-practice-more"><span class="header-section-number">16.5</span> Additional practice</a></li>
  <li><a href="#data-used-in-this-section" id="toc-data-used-in-this-section" class="nav-link" data-scroll-target="#data-used-in-this-section">Data used in this section</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./inference_01_sampling-distributions.html">Statistical Inference</a></li><li class="breadcrumb-item"><a href="./inference_01_sampling-distributions.html"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Sampling Distributions and Confidence Intervals</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Sampling Distributions and Confidence Intervals</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-sap-dispute" class="level2" data-number="16.1">
<h2 data-number="16.1" class="anchored" data-anchor-id="sec-sap-dispute"><span class="header-section-number">16.1</span> The SAP dispute</h2>
<p>In 2005 SAP, the world’s largest maker of enterprise software, ran advertisements claiming that companies running SAP are 32% more profitable than companies that don’t. The figure came from a study SAP commissioned and never released for public scrutiny <span class="citation" data-cites="carr-sap-lies carr-sap-ads">(<a href="appendix_data.html#ref-carr-sap-lies" role="doc-biblioref">Carr 2005</a>, <a href="appendix_data.html#ref-carr-sap-ads" role="doc-biblioref">2006</a>)</span>. In March 2006 the analyst firm Nucleus Research published a rebuttal <span class="citation" data-cites="sap-nucleus">(<a href="appendix_data.html#ref-sap-nucleus" role="doc-biblioref">Nucleus Research 2006</a>)</span>. Nucleus collected data on the 81 publicly traded companies listed as customers on SAP’s website. For each company, it looked up <strong>return on equity</strong> (ROE), annual profit as a percentage of shareholder equity, along with the average ROE of the company’s industry. ROE measures how profitably a company uses its shareholders’ capital.</p>
<p>The 81 SAP customers averaged an ROE of 12.6% against industry benchmarks averaging 15.7%, and Nucleus titled the report “SAP customers are 20 percent less profitable than their peers” (12.6 is about 20% below 15.7).</p>
<p>SAP dismissed the report as “junk science.” Its argument was about sample size: 81 companies out of SAP’s roughly 30,000 customers is about a quarter of one percent, far too few — SAP claimed — to say anything about the customer base as a whole. Who is right? Both sides are arguing about the same unknown quantity, the average ROE among all 30,000 customers. The next few chapters build the tools to say what 81 companies can and cannot tell us about it.</p>
<p>The <code>sap_roe</code> data contain the 81 companies from the Nucleus report, one row per company: its name (<code>company</code>), its industry (<code>industry</code>), its ROE in percent (<code>roe</code>), and the average ROE of its industry (<code>industry_roe</code>). <a href="#fig-sap-roe" class="quarto-xref">Figure&nbsp;<span>16.1</span></a> shows the 81 ROE values along with the two averages in dispute.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-sap-roe" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sap-roe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="inference_01_sampling-distributions_files/figure-html/fig-sap-roe-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sap-roe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.1: ROE for the 81 publicly traded SAP customers in the Nucleus report. The sample mean of 12.6% sits about 3 percentage points below the 15.7% average of the companies’ industry benchmarks, and the spread around both lines is much larger than the gap between them.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Company ROEs run from -91.8% to 116.4%, with a standard deviation of 25.7 percentage points. Because the sample mean is sensitive to extreme values, including or excluding a few firms could change it appreciably. How much would the mean vary across random samples of 81 companies?</p>
<p>To reason about an error we can’t observe, we need a model for how the sample arose. For now, consider the 81 companies as a <strong>simple random sample</strong> of SAP customers: a lottery draw in which every group of 81 customers is equally likely to be selected. Since 81 is a small fraction of the population, we can approximate this sampling process with iid random variables <span class="math inline">\(X_1, \dots, X_{81}\)</span>, drawn from a discrete distribution placing probability <span class="math inline">\(1/N\)</span> on each of the <span class="math inline">\(N\)</span> companies in the population. This is the same thought exercise we went through in <a href="./prob_01_intro.html#what-is-sampling-what-is-a-sample-and-what-is-a-representative-sample">the introductory probability chapter</a>. The true population mean and standard deviation of that distribution are <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>, respectively — the mean and SD we would get if we could see all 30,000 firms’ ROE.</p>
<div id="technical-population-as-distribution" class="TechnicalDetail">
<details class="TechnicalDetail fobx-simplebox fobx-default"><summary><strong>Technical detail 16.1: </strong>Approximating a random sample with iid draws</summary><div>
<p>If the connection between sampling firms and drawing random variables still feels abstract, the table below may help. <a href="#tbl-population-dist" class="quarto-xref">Table&nbsp;<span>16.1</span></a> shows the probability distribution of a single firm drawn completely at random from the population.</p>
<div class="cell">
<div id="tbl-population-dist" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-population-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;16.1: The probability distribution of a single random draw from the population. Each of the 30,000 companies is equally likely, so each has probability 1/30,000. The ROE values shown are from the simulated population used in the sampling app later in this chapter.
</figcaption>
<div aria-describedby="tbl-population-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Company</th>
<th style="text-align: right;">ROE (<span class="math inline">\(x\)</span>)</th>
<th style="text-align: right;">Probability of selecting company</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">44.3%</td>
<td style="text-align: right;">1/30,000</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">6.3%</td>
<td style="text-align: right;">1/30,000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">5.1%</td>
<td style="text-align: right;">1/30,000</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.9%</td>
<td style="text-align: right;">1/30,000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">4.5%</td>
<td style="text-align: right;">1/30,000</td>
</tr>
<tr class="even">
<td style="text-align: right;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">30,000</td>
<td style="text-align: right;">-1.0%</td>
<td style="text-align: right;">1/30,000</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Let <span class="math inline">\(X\)</span> be the ROE of a company drawn at random, with every company equally likely. If company <span class="math inline">\(i\)</span> has ROE <span class="math inline">\(x_i\)</span>, the mean of this distribution is</p>
<p><span class="math display">\[
\mu = \frac{1}{30{,}000}\sum_{i=1}^{30{,}000}x_i
    = \frac{x_1 + x_2 + \cdots + x_{30{,}000}}{30{,}000}.
\]</span></p>
<p>This is the average ROE over the whole population. The population variance <span class="math inline">\(\sigma^2\)</span> and standard deviation <span class="math inline">\(\sigma\)</span> are computed similarly, using the <a href="./prob_03_distribution-parameters.html#sec-rv-variance">discrete variance and standard deviation formulas</a>. Just as before, we can interpret <span class="math inline">\(\mu\)</span> as the expected value for the ROE of a single firm sampled from this population and <span class="math inline">\(\sigma\)</span> as a measure of how far that firm’s ROE is likely to be from <span class="math inline">\(\mu\)</span>.</p>
<p>Our thought experiment treats the observed sample of 81 firms as iid observations, like a series of coin tosses or dice rolls. However, when working with surveys of a finite population, a random sample typically selects firms without replacement — no firm could appear more than once — producing dependence between the observations (if firm A appears, firm B is less likely to appear because one “slot” of the 81 is missing). However: a) the dependence is very weak when the sample size is much smaller than the population, and b) ignoring this particular kind of dependence actually produces a conservative estimate of uncertainty.</p>
</div></details>
</div>
<p>Before we continue, we need to collect a few definitions and notation conventions.</p>
<div id="defn-estimator-estimate" class="Definition">
<div class="Definition fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-book fobx-icon" aria-hidden="true"></i><strong>Definition 16.1: </strong>Parameter, estimator, and estimate</div><div class="fobx-body">
<ul>
<li><p>The <strong>parameter</strong> is a fixed numerical property of the population or probability distribution that we want to estimate — here the true average ROE <span class="math inline">\(\mu\)</span> among all of SAP’s customers.</p></li>
<li><p>An <strong>estimator</strong> for a parameter is the recipe (a mathematical formula) applied to a random sample — for example, the sample mean <span class="math inline">\(\bar{X}\)</span> is the arithmetic average we defined in <a href="./singlevar_03_location-and-spread.html#defn-sample-mean">the definition of the sample mean</a>, computed on a random sample. It’s a random variable because the sample over which we take the average is random.</p></li>
<li><p>The <strong>estimate</strong> is the number the recipe produced from our actual sample: in the SAP example, <span class="math inline">\(\bar{x} = 12.6\%\)</span>.</p></li>
<li><p>The <strong>estimation error</strong> <span class="math inline">\(\bar{X} - \mu\)</span> is random; it depends on the sample we observe. Since we can describe the probability distribution of <span class="math inline">\(\bar X\)</span>, we can describe the probability distribution of our estimation error.</p></li>
<li><p>The <strong>realized estimation error</strong> <span class="math inline">\(\bar{x} - \mu\)</span> is a single fixed number we cannot calculate from the sample alone, because it depends on the unknown <span class="math inline">\(\mu\)</span>.</p></li>
</ul>
</div></div>
</div>
<p>The essential question in this dispute is this: Does the estimate of 12.6% ROE among the 81 firms provide strong evidence that SAP firms have below-average (15.7%) ROE?</p>
<p><!---
The expected value for $X_1$ is just $\mu$: That's a basic calculation from [the expected-value formula](prob_03_distribution-parameters.qmd#defn-expected-value). Similarly its standard deviation will be $\sigma$. 
To get the second row in our sample --- $X_2$ --- we take another random sample from the same distribution, which has mean $\mu$ and standard deviation $\sigma$. This is the same as flipping a coin to get a sample from a binary distribution where a 1 or 0 is equally likely, or rolling a die to get a sample from a distribution over 1 - 6 where each outcome is equally likely. Our die just happens to have 30,000 faces.

 Repeated application of our basic probability rules tells us that the probability we get a firm with ROE in any given interval, say 5% - 15%, is:

$$
\frac{\text{Number of companies with ROE between 5\% and 15\%}}{Number of companies in the population}
$$

That is, 
---></p>
</section>
<section id="sec-sampling-ci" class="level2" data-number="16.2">
<h2 data-number="16.2" class="anchored" data-anchor-id="sec-sampling-ci"><span class="header-section-number">16.2</span> Sampling distributions and confidence intervals</h2>
<p>Suppose thousands of analysts each drew a random sample of 81 SAP customers and computed its mean ROE. Their estimates would vary around the population mean <span class="math inline">\(\mu\)</span>. If that variation were small, a single sample mean would usually be close to <span class="math inline">\(\mu\)</span>; a wide spread would allow larger estimation errors. We describe this variation with the <strong>sampling distribution</strong>.</p>
<div id="defn-sampling-distribution" class="Definition">
<div class="Definition fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-book fobx-icon" aria-hidden="true"></i><strong>Definition 16.2: </strong>Sampling distribution</div><div class="fobx-body">
<p>The <strong>sampling distribution</strong> of a statistic (like the sample mean) is the probability distribution of that statistic across random samples of a given size <span class="math inline">\(n\)</span>. For the sample mean, it is the distribution of <span class="math inline">\(\bar{X}\)</span> — the values our recipe could have produced, had the sample come out differently.</p>
</div></div>
</div>
<p>In real life we get one sample, so we never see the sampling distribution directly.</p>
<p>Under the iid model, we know two things about this distribution exactly. The <a href="./prob_10_sums-averages-clt.html#sec-sums-averages">rules for sums and averages of iid random variables</a> give <span class="math inline">\(E[\bar X] = \mu\)</span> and <span class="math inline">\(SD(\bar X) = \sigma/\sqrt{n}\)</span>. The <a href="./prob_10_sums-averages-clt.html#sec-clt">Central Limit Theorem (CLT)</a> adds the shape: the sampling distribution of the sample mean is approximately normal when the iid model has finite variance and the sample size is large enough:</p>
<p><span class="math display">\[
\bar{X} \;\approx\; N\!\left(\mu,\; \sigma^2/n\right).
\]</span></p>
<p>In words: across random samples, the sample mean is right on average, and its typical distance from the truth shrinks as the sample grows.</p>
<p>Using our rules for <a href="./prob_03_distribution-parameters.html#sec-shift-scale">shifting and scaling random variables</a>, which apply to <a href="./prob_04_normal.html">normal distributions</a> too, we can get the distribution of the estimation <em>error</em> <span class="math inline">\(\bar{X} - \mu\)</span> over many random samples by shifting the mean to zero:</p>
<p><span class="math display">\[
\bar{X} - \mu \;\approx\; N\!\left(0,\; \sigma^2/n\right).
\]</span></p>
<p>Across random samples, the errors average to zero. Their standard deviation, <span class="math inline">\(\sigma/\sqrt{n}\)</span>, describes how far individual sample means typically fall from <span class="math inline">\(\mu\)</span>; we call it the <strong>standard error</strong> of the sample mean.</p>
<div id="defn-standard-error" class="Definition">
<div class="Definition fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-book fobx-icon" aria-hidden="true"></i><strong>Definition 16.3: </strong>Standard error</div><div class="fobx-body">
<p>The <strong>standard error</strong> of a statistic is the standard deviation of its sampling distribution. For a statistic that is right on average, like the sample mean, it is the typical size of the estimation error:</p>
<p><span class="math display">\[
SE(\bar{X}) = \frac{\sigma}{\sqrt{n}} \approx \frac{s}{\sqrt{n}},
\]</span></p>
<p>and the number we report is an estimate, computed by plugging in the sample standard deviation <span class="math inline">\(s\)</span> for the unknown <span class="math inline">\(\sigma\)</span>.</p>
</div></div>
</div>
<p>For the SAP sample the ingredients are <span class="math inline">\(s = 25.7\)</span> and <span class="math inline">\(n = 81\)</span>, so</p>
<p><span class="math display">\[
SE(\bar{X}) \approx \frac{s}{\sqrt{81}} \approx 2.85 \text{ percentage points}.
\]</span></p>
<p>In words: when we estimate the average ROE of all SAP customers from 81 of them, our estimate typically misses by about 2.9 percentage points. The gap Nucleus built its headline on is 3.1 points — almost exactly the size of a typical error induced by using a random sample of size 81 instead of the entire population.</p>
<section id="sec-app-walkthrough" class="level3" data-number="16.2.1">
<h3 data-number="16.2.1" class="anchored" data-anchor-id="sec-app-walkthrough"><span class="header-section-number">16.2.1</span> Simulating the sampling distribution</h3>
<p>The app draws repeated samples from a simulated population of 30,000 company ROE values. We know every value in this population, so we can compare each sample mean with its true mean. This is an illustration of random sampling; these simulated firms are not the actual population of SAP customers.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Try it yourself
</div>
</div>
<div class="callout-body-container callout-body">
<p>Open the <a href="https://jaredsmurray.github.io/stats-webapps/sap_sampling.html" target="_blank">sampling distribution explorer</a> in a new browser window beside this page. Work through the steps below as you read.</p>
</div>
</div>
<p>The app shows three stacked panels. The top panel is the population: a histogram of all 30,000 simulated ROE values, with the population size <span class="math inline">\(N\)</span>, the population mean <span class="math inline">\(\mu\)</span>, and the population standard deviation <span class="math inline">\(\sigma\)</span> printed on the plot.</p>
<p>Set the sample size to 81, matching the Nucleus study, and hit the “Take 1 sample” button. The middle panel shows the 81 values the app just drew, with <span class="math inline">\(n\)</span>, <span class="math inline">\(\bar{x}\)</span>, and <span class="math inline">\(s\)</span> printed beside them. A red line marks the sample mean. The bottom panel repeats that mean as a red X, beside a dashed line at the population mean <span class="math inline">\(\mu\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-app-1sample" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-app-1sample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="inference_01_sampling-distributions_files/figure-html/fig-app-1sample-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-app-1sample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.2: The app after one sample of n = 81. Top: the simulated population. Middle: the 81 sampled values, with the sample mean marked by the red line. Bottom: that same mean as a red X, beside the dashed line at the population mean.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The red X’s position relative to the dashed line shows the sample’s estimation error: negative to the left of <span class="math inline">\(\mu\)</span>, positive to the right. Your app will draw a different random sample, so its mean will generally differ from the one printed here.</p>
<p>Hit “Take 1 sample” again. The middle panel now shows a fresh set of 81 companies with a new mean, the red X jumps to the new value, and the bottom panel keeps the previous mean in its history.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-app-2samples" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-app-2samples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="inference_01_sampling-distributions_files/figure-html/fig-app-2samples-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-app-2samples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.3: The bottom panel after a second sample. The red X sits at the newest sample mean; the first sample’s mean stays in the histogram.
</figcaption>
</figure>
</div>
</div>
</div>
<p>By default, the “Take many samples” button adds batches of 50 sample means to the bottom panel. Keep the sample size at 81 and compare the histograms after 50 and 5,000 samples. More repetitions give a clearer picture of the sampling distribution for <span class="math inline">\(n=81\)</span>; they do not reduce its standard error. To reduce the standard error, we would need more firms in each sample.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-app-50samples" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-app-50samples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="inference_01_sampling-distributions_files/figure-html/fig-app-50samples-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-app-50samples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.4: After 50 samples the histogram of sample means is taking shape but still ragged. The x-axis here and in the next figures is zoomed in relative to the app’s.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-app-5000samples" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-app-5000samples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="inference_01_sampling-distributions_files/figure-html/fig-app-5000samples-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-app-5000samples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.5: After 5,000 samples the histogram is smooth and bell-shaped, centered at the population mean.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The sample means cluster around the population mean in an approximately bell-shaped distribution, even though individual ROEs are skewed.</p>
<p>This isn’t a coincidence; this is the Central Limit Theorem at work. Tick the “Show normal approximation” box and the app overlays the curve <span class="math inline">\(N(\mu, \sigma^2/n)\)</span> in purple — computed from the simulated population’s mean and standard deviation and the sample size.</p>
<p>The app’s standard error is 2.35 percentage points. It uses the known standard deviation of the simulated population, <span class="math inline">\(\sigma = 21.2\)</span> points. Our earlier estimate of 2.85 points used <span class="math inline">\(s = 25.7\)</span> points from the actual SAP sample. Both calculations divide by <span class="math inline">\(\sqrt{81}\)</span>, but their inputs describe different data.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-app-normal" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-app-normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="inference_01_sampling-distributions_files/figure-html/fig-app-normal-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-app-normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.6: The same 5,000 sample means with the normal approximation overlaid in purple: the curve N(mu, sigma^2/n) computed from the population mean, the population standard deviation, and n = 81, for a standard error of 2.35 percentage points.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Nucleus had one sample. The sampling model lets us estimate how much its mean would vary across repeated samples, even though we cannot observe those other samples.</p>
</section>
<section id="sec-ci" class="level3" data-number="16.2.2">
<h3 data-number="16.2.2" class="anchored" data-anchor-id="sec-ci"><span class="header-section-number">16.2.2</span> Accounting for sampling error when presenting results</h3>
<p>Let’s return to SAP’s objection: They said, essentially, that a sample of 81 firms was far too small to learn anything about 30,000 firms. We know that is, at best, incomplete — if the population variability of ROE was very low, we could learn an awful lot from the average of 81 observations. A more charitable read of the objection would be: Given the variability in ROE across the population of firms, if the true average ROE of SAP firms were 15.7% (the industry average), then an observed difference of <span class="math inline">\(12.6 - 15.7 = -3.1\)</span> percentage points between the sample estimate and true value is perfectly consistent with chance variability due to random sampling. Concluding that SAP firms have below-average profitability would be a mistake. (SAP is actually making a stronger statement, that their firms have average ROE 32% higher than average, which would be about 20.7%.)</p>
<p>We can avoid making a guess about the true population mean entirely if we ask a different, related question: What values for the true population average are <em>consistent</em> with the data we observed? The sample average ROE is our best guess for the population average ROE, but we know that it is off by some amount due to the random sampling process. What we would like to do is report an interval: Our best guess plus or minus a <em>margin of error</em> that describes the range of true values we can’t rule out with a high degree of certainty given the natural variability in ROE — measured by <span class="math inline">\(\sigma\)</span>, estimated by <span class="math inline">\(s\)</span> — and the sample size <span class="math inline">\(n\)</span>.</p>
<p>We already established that <span class="math inline">\(\bar X - \mu\)</span>, our error, has an approximately normal distribution with mean zero and standard deviation <span class="math inline">\(SE(\bar X) = \sigma/\sqrt{n}\)</span>. That means the interval <span class="math display">\[
\bar X \pm 2\underbrace{SE(\bar X)}_{ = \sigma/\sqrt{n}}
\]</span> will contain <span class="math inline">\(\mu\)</span> in about 95% of all possible random samples of size <span class="math inline">\(n\)</span>. Why? Since <span class="math inline">\(\bar X-\mu \approx N(0, SE(\bar X)^2)\)</span>, <span class="math display">\[
\Pr[-2SE(\bar X) \leq \bar X - \mu \leq 2 SE(\bar X)] \approx 0.95.
\]</span> A little algebra turns this into <span class="math display">\[
\Pr[\bar X - 2SE(\bar X) \leq \mu \leq \bar X + 2 SE(\bar X)] \approx 0.95.
\]</span></p>
<p>We can plug in the observed estimate <span class="math inline">\(\bar x\)</span> and <span class="math inline">\(s/\sqrt{n}\)</span>, the estimate of <span class="math inline">\(SE(\bar X)\)</span> computed in <a href="#defn-standard-error">the definition of standard error</a>, to get a computable interval:</p>
<p><span class="math display">\[
\bar x \pm 2\frac{s}{\sqrt{n}}
\]</span></p>
<p>We call an interval constructed this way a <strong>confidence interval</strong>, and it represents all possible values for the true population mean that are consistent with the data we have, at a given level of confidence (95% here).</p>
<div id="defn-confidence-interval" class="Definition">
<div class="Definition fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-book fobx-icon" aria-hidden="true"></i><strong>Definition 16.4: </strong>Confidence interval</div><div class="fobx-body">
<p>A <strong>confidence interval</strong> for a parameter is a range of <em>plausible values</em> for that parameter (at a given confidence level, usually 95%). These are values for the true parameter that are consistent with the data we observed; the difference between a plausible value and our best guess (<span class="math inline">\(\bar x\)</span>) can be reasonably explained by chance variation due to sampling.</p>
<p>For an estimator whose sampling distribution is approximately normal and centered at the parameter, an approximate 95% confidence interval is</p>
<p><span class="math display">\[
\text{estimate} \pm 2 \times \text{(standard error)}.
\]</span></p>
<p>The 95% describes repeated use of the procedure: across many random samples of the same size, about 95% of the intervals contain the fixed population parameter. For the sample mean, we estimate the standard error with <span class="math inline">\(s/\sqrt n\)</span>, so the interval’s width also varies from sample to sample. Its coverage is approximate.</p>
</div></div>
</div>
<p>For the SAP sample,</p>
<p><span class="math display">\[
12.6 \pm 2(2.85) \approx [6.9\%,\ 18.3\%].
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Interpretation: what the interval says about the dispute
</div>
</div>
<div class="callout-body-container callout-body">
<p>The plausible values for the true average ROE among all SAP customers run from about 6.9% to about 18.3%. Parity with peers is one of them: the 15.7% industry benchmark sits inside the interval, so the 3.1-point gap Nucleus led with is consistent with ordinary sampling variation. So is an average ROE near 7%, which would be considerably worse than Nucleus claimed. Using the industry benchmark for this comparison, SAP’s advertised 32% advantage implies about 20.7%, which lies outside the interval and is not a plausible value at this confidence level.</p>
</div>
</div>
<p>We can get a feel for what a confidence interval represents and how it behaves in the app. Tick “Show approximate 95% confidence interval” and every sample now draws its interval along the bottom of the sampling distribution, colored green when it covers the dashed line at <span class="math inline">\(\mu\)</span> and red when it misses.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-app-ci" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-app-ci-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="inference_01_sampling-distributions_files/figure-html/fig-app-ci-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-app-ci-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.7: The bottom panel after one sample of n = 81 with the interval shown. The app uses the known simulated population SD, giving a standard error of 2.35 points and equal-width intervals. The sample mean of 11.65% plus or minus 2 standard errors (4.71 points) gives the interval [6.9%, 16.4%], drawn in green because it covers the dashed line at mu.
</figcaption>
</figure>
</div>
</div>
</div>
<p>As you keep sampling, the footer keeps a running tally of how often the interval covered <span class="math inline">\(\mu\)</span>. The tally bounces around early on — after 50 samples ours read 90.0% — and settles near 95% as the samples pile up. <a href="#fig-app-coverage" class="quarto-xref">Figure&nbsp;<span>16.8</span></a> draws the first 100 intervals separately instead of one at a time, so you can see each miss the tracker counted.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-app-coverage" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-app-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="inference_01_sampling-distributions_files/figure-html/fig-app-coverage-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-app-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.8: The first 100 samples, one interval each, in the order they were drawn. The 6 red intervals miss the population mean; the other 94 cover it. Across all 5,000 samples the coverage is 95.6%.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Common mistake: The 95% describes the procedure, not this interval
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\mu\)</span> is a fixed number, and <span class="math inline">\([6.9\%, 18.3\%]\)</span> either contains it or it doesn’t — there is no randomness left to attach a probability to.</p>
<p>The 95% statement belongs to the method: intervals built this way contain <span class="math inline">\(\mu\)</span> in about 95% of random samples. Over many independent data analyses for this class where the sampling assumptions hold, about 95% of the intervals will contain the true value and about 5% will miss. We can’t know <em>which</em> intervals miss, but we know it doesn’t happen too often.</p>
</div>
</div>
</section>
</section>
<section id="sec-sampling-practice" class="level2" data-number="16.3">
<h2 data-number="16.3" class="anchored" data-anchor-id="sec-sampling-practice"><span class="header-section-number">16.3</span> Practice</h2>
<div id="exercise-identify-delivery-estimate" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 16.1: </strong>What is being estimated?</div><div class="fobx-body">
<p>A retailer wants the mean delivery time <span class="math inline">\(\mu\)</span> for all orders in its current service area. In an invented study, it takes a random sample of 100 orders and computes an average delivery time of 42 minutes.</p>
<p>Identify the parameter, the estimator, and the estimate. If the retailer drew a new random sample, which of these would change and which would stay fixed?</p>
<details aria-label="Solution" id="solution-identify-delivery-estimate" class="solution-details">
<summary>Solution</summary>
<p>The parameter is the population mean delivery time <span class="math inline">\(\mu\)</span>. The estimator is the sample mean <span class="math inline">\(\bar{X}\)</span>, the rule for averaging the sampled times. The estimate is <span class="math inline">\(\bar{x}=42\)</span> minutes. A new sample would generally give a different estimate; the population parameter and the averaging rule would stay fixed.</p>
</details>
</div></div>
</div>
<div id="exercise-delivery-sd-se" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 16.2: </strong>Individual times and averages</div><div class="fobx-body">
<p>Suppose delivery times are iid draws from a population with standard deviation <span class="math inline">\(\sigma=12\)</span> minutes. Compare random samples of 100 and 400 orders.</p>
<p>Compute the standard error of the sample mean for each size. Explain which spread changes and which stays at 12 minutes when the sample size increases.</p>
<details aria-label="Solution" id="solution-delivery-sd-se" class="solution-details">
<summary>Solution</summary>
<p>The standard errors are <span class="math inline">\(12/\sqrt{100}=1.2\)</span> minutes and <span class="math inline">\(12/\sqrt{400}=0.6\)</span> minutes. Quadrupling the sample size halves the spread of sample means across repeated samples. Individual delivery times still have population SD 12 minutes; collecting more orders makes their average more precise without making individual deliveries less variable.</p>
</details>
</div></div>
</div>
<div id="exercise-delivery-confidence-interval" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 16.3: </strong>A confidence interval for delivery time</div><div class="fobx-body">
<p>An iid sample of 100 delivery times has sample mean 42 minutes and sample standard deviation 12 minutes. Assume the sampling distribution of the sample mean is approximately normal.</p>
<ol type="1">
<li>Compute the estimated standard error and an approximate 95% confidence interval for the population mean using the two-SE rule.</li>
<li>A true average delivery time above 45 minutes would trigger a costly process review; is that warranted based on this audit?</li>
<li>Using the sample standard deviation of 12 minutes as a stand-in for the population standard deviation, if the company wanted the margin of error <span class="math inline">\(2SE(\bar X)\)</span> for the next audit to be 1 minute, how many deliveries should they include? (Hint: set <span class="math inline">\(2SE(\bar X) = 1\)</span>, plug in <span class="math inline">\(s\)</span> for <span class="math inline">\(\sigma\)</span>, and solve for <span class="math inline">\(n\)</span>.)</li>
</ol>
<details aria-label="Solution" id="solution-delivery-confidence-interval" class="solution-details">
<summary>Solution</summary>
<ol type="1">
<li>The estimated SE is <span class="math inline">\(12/\sqrt{100}=1.2\)</span> minutes. The interval is <span class="math inline">\(42\pm2(1.2)=[39.6,44.4]\)</span> minutes. It gives plausible values for the population mean delivery time under the sampling assumptions.</li>
<li>The interval’s upper endpoint, 44.4 minutes, is below 45 minutes. Under the sampling assumptions, this audit does not support triggering a process review on the grounds that the population mean exceeds 45 minutes.</li>
<li>Using 12 minutes as the planning value for the population standard deviation, we solve <span class="math inline">\(2(12)/\sqrt n=1\)</span>, giving <span class="math inline">\(\sqrt n=24\)</span> and <span class="math inline">\(n=576\)</span>. The next audit should include at least 576 deliveries to target a margin of error no larger than 1 minute.</li>
</ol>
</details>
</div></div>
</div>
</section>
<section id="sec-bootstrap" class="level2" data-number="16.4">
<h2 data-number="16.4" class="anchored" data-anchor-id="sec-bootstrap"><span class="header-section-number">16.4</span> The bootstrap</h2>
<p>For the sample mean, <span class="math inline">\(s/\sqrt n\)</span> estimates the standard error directly. For other statistics, we may not have a convenient formula, and a normal approximation may not describe the sampling distribution well.</p>
<p>The <strong>bootstrap</strong> estimates sampling variability by repeatedly sampling from the observed data. In the app above we sampled from a known population. Here we use the sample as an approximation to the population distribution, preserving the sample size and computing the statistic again on each resample.</p>
<div id="defn-bootstrap" class="Definition">
<div class="Definition fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-book fobx-icon" aria-hidden="true"></i><strong>Definition 16.5: </strong>The bootstrap</div><div class="fobx-body">
<p>To bootstrap a statistic computed from a sample of size <span class="math inline">\(n\)</span>: draw <span class="math inline">\(n\)</span> observations from the sample <strong>with replacement</strong>, compute the statistic on this <em>bootstrap sample</em>, and repeat many times (say <span class="math inline">\(B = 10{,}000\)</span>).</p>
<p>The distribution of these <span class="math inline">\(B\)</span> statistics approximates how the statistic varies across samples, and their standard deviation is the <strong>bootstrap standard error</strong>. This use of the bootstrap relies on an iid sample that represents the population well enough for the statistic we want to estimate.</p>
</div></div>
</div>
<section id="why-sample-n81-firms" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="why-sample-n81-firms">Why sample n=81 firms?</h4>
<p>We want to estimate variability across samples of 81 firms, so each bootstrap resample must also contain 81 firms. Smaller resamples would overstate the variability of the sample mean; larger ones would understate it. The number of resamples, <span class="math inline">\(B\)</span>, controls how precisely the simulation estimates that variability. It does not increase the original sample size.</p>
</section>
<section id="why-sample-with-replacement" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="why-sample-with-replacement">Why sample with replacement?</h4>
<p>Each bootstrap iteration draws 81 firms from a sample of exactly 81 firms. Without replacement there is only one possible draw: every resampled dataset would be the original sample, just shuffled, and the mean wouldn’t vary across bootstrap resamples at all. Sampling with replacement is what lets the resamples differ.</p>
</section>
<section id="when-is-the-formula-useful" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="when-is-the-formula-useful">When is the formula useful?</h4>
<p>For a sample mean, the formula is quick to compute and shows how precision depends on sample size: quadrupling <span class="math inline">\(n\)</span> halves the standard error. The bootstrap requires more computation but can estimate standard errors when a formula is inconvenient or unavailable. It can also show skew or other departures from a normal shape. Using the bootstrap to estimate an SE does not, by itself, justify a two-SE confidence interval; that interval still needs an approximately normal sampling distribution centered at the parameter.</p>
<p><a href="#fig-sap-bootstrap" class="quarto-xref">Figure&nbsp;<span>16.9</span></a> shows the result of bootstrapping the SAP mean, with a normal curve centered at the observed sample mean and using our estimated SE for comparison.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-sap-bootstrap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sap-bootstrap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="inference_01_sampling-distributions_files/figure-html/fig-sap-bootstrap-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sap-bootstrap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.9: 10,000 bootstrap means from resamples of 81 SAP customers. The dashed line marks the observed sample mean. The orange normal curve has that same center and has standard deviation 2.85 percentage points; the bootstrap standard error is 2.84 points.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The bootstrap distribution is centered near the observed sample mean because we resample from the 81 observed firms. The actual sampling distribution is centered at the unknown population mean; the bootstrap approximates its spread using the sample.</p>
<p>Using the bootstrap SE in the two-SE interval gives approximately [7.0%, 18.3%], compared with [6.9%, 18.3%] from the formula. The lower endpoint rounds differently, but the conclusions about the SAP dispute are unchanged.</p>
<div id="technical-bootstrap-mean" class="TechnicalDetail">
<details class="TechnicalDetail fobx-simplebox fobx-default"><summary><strong>Technical detail 16.2: </strong>Why the two standard errors are so close</summary><div>
<p>Treat the observed sample as fixed. Each bootstrap observation is an independent draw from the distribution that gives each of the <span class="math inline">\(n\)</span> observed data points probability <span class="math inline">\(1/n\)</span>. That distribution has mean <span class="math inline">\(\bar x\)</span> and a standard deviation of approximately <span class="math inline">\(s\)</span> (technically <span class="math inline">\(\sqrt{\frac{n-1}{n}}s\)</span>, about <span class="math inline">\(0.99s\)</span> for these 81 firms).</p>
<p>Let <span class="math inline">\(\bar X^*\)</span> be the mean of a bootstrap resample of size <span class="math inline">\(n\)</span>. The <a href="./prob_10_sums-averages-clt.html#sec-clt">CLT</a> applies here too:</p>
<p><span class="math display">\[
\bar X^* \;\approx\; N\!\left(\bar x,\;s^2/n\right).
\]</span></p>
<p>The center is the original sample mean, and the standard deviation is approximately <span class="math inline">\(s/\sqrt n\)</span>. As we increase the number of resamples <span class="math inline">\(B\)</span>, the standard deviation of the simulated means approaches the bootstrap distribution’s standard deviation, approximately <span class="math inline">\(s/\sqrt n\)</span>. Increasing <span class="math inline">\(B\)</span> makes the simulation more precise; the adequacy of the normal approximation still depends on <span class="math inline">\(n\)</span> and the shape of the observed-data distribution.</p>
<p>For the sample mean, the bootstrap therefore gives nearly the same two-SE interval as the formula:</p>
<p><span class="math display">\[
\bar x \pm 2\times\text{(bootstrap SE)}
\;\approx\; \bar x \pm 2\frac{s}{\sqrt n}.
\]</span></p>
<p>The benefit to using the bootstrap? We could get nearly the same answer as using the CLT without doing any math at all to work out the standard error. For a sample mean the math is not a big impediment, but it can be for other statistics, and sometimes the math requires modeling assumptions we would rather not make.</p>
</div></details>
</div>
<div id="exercise-bootstrap-design-check" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 16.4: </strong>Check a bootstrap design</div><div class="fobx-body">
<p>An analyst has an iid sample of 100 delivery times and wants a bootstrap standard error for its sample mean. Assume the sample adequately represents the population. The analyst proposes three procedures, each repeated 10,000 times:</p>
<ol type="1">
<li>Draw 100 observations without replacement and compute their mean.</li>
<li>Draw 400 observations with replacement and compute their mean.</li>
<li>Draw 100 observations with replacement and compute their mean.</li>
</ol>
<p>Which procedure matches the original sample size and allows the resamples to vary? Explain the problem with each other procedure. In the matching procedure, what quantity should the analyst compute from the 10,000 means to estimate SE?</p>
<details aria-label="Solution" id="solution-bootstrap-design-check" class="solution-details">
<summary>Solution</summary>
<p>Procedure 3 matches the original sample size and uses replacement so that observations can repeat or be omitted. Procedure 1 only shuffles the same 100 observations, so every resample mean is identical. Procedure 2 mimics a sample of 400 rather than 100, understating the variability of the mean for the original sample size. The sample standard deviation of the 10,000 means is the bootstrap SE; it is not the standard deviation of the delivery times within one resample.</p>
</details>
</div></div>
</div>
</section>
</section>
<section id="sec-sampling-practice-more" class="level2" data-number="16.5">
<h2 data-number="16.5" class="anchored" data-anchor-id="sec-sampling-practice-more"><span class="header-section-number">16.5</span> Additional practice</h2>
<div id="exercise-sap-paired" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 16.5: </strong>Each company against its own industry</div><div class="fobx-body">
<p>The chapter compared the SAP customers’ mean ROE with the 15.7% average of their industry benchmarks. The <code>sap_roe</code> data also allow a comparison company by company: for each of the 81 firms, subtract its industry’s ROE from its own. <a href="#fig-practice-sap-diff" class="quarto-xref">Figure&nbsp;<span>16.10</span></a> shows these differences. Their sample mean is -3.06 percentage points and their sample standard deviation is 23.3 points.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-practice-sap-diff" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-practice-sap-diff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="inference_01_sampling-distributions_files/figure-html/fig-practice-sap-diff-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-practice-sap-diff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.10: Each SAP customer’s ROE minus its industry’s average ROE, in percentage points. The dashed line marks zero, where a company matches its peers.
</figcaption>
</figure>
</div>
</div>
</div>
<ol type="1">
<li>State the parameter this analysis estimates, and explain how it differs from the <span class="math inline">\(\mu\)</span> in <a href="#sec-sampling-ci" class="quarto-xref"><span>Section 16.2</span></a>.</li>
<li>Compute the estimated standard error and an approximate 95% confidence interval for that parameter.</li>
<li>Is a true average gap of zero, meaning SAP customers match their peers on average, a plausible value? Is Nucleus’s headline gap of about <span class="math inline">\(-3\)</span> points? SAP’s advertised 32% advantage over peers would put the average gap near <span class="math inline">\(+5.0\)</span> points; is that plausible?</li>
<li>The standard error here, 2.6 points, is smaller than the standard error of the mean ROE alone, 2.8 points, even though each difference combines two uncertain quantities. Use the variance rule for a difference from <a href="./prob_09_combining-random-variables.html#sec-lincom-rules">Chapter 14</a> and the sample correlation between a company’s ROE and its industry’s, 0.42, to explain why.</li>
<li>Which comparison better answers “are SAP customers less profitable than their peers”: the chapter’s, which compares the mean ROE with the fixed number 15.7%, or this one? Explain what each treats as fixed and what each treats as random.</li>
</ol>
<details aria-label="Solution" id="details-1" class="solution-details">
<summary>Solution</summary>
<ol type="1">
<li>The parameter is the average, over all of SAP’s customers, of each company’s ROE minus its own industry’s ROE. Call it <span class="math inline">\(\delta\)</span>. The chapter’s <span class="math inline">\(\mu\)</span> is the average ROE of SAP customers on its own; <span class="math inline">\(\delta\)</span> measures the average gap between each customer and its peers, so it already accounts for the mix of industries the customers come from.</li>
<li>The estimated standard error is <span class="math inline">\(23.3/\sqrt{81}\approx2.59\)</span> points. The interval is <span class="math inline">\(-3.1\pm2(2.59)
\approx[-8.2,\ 2.1]\)</span> percentage points.</li>
<li>Zero lies inside the interval, so parity with peers is plausible. So is the <span class="math inline">\(-3\)</span>-point gap Nucleus reported, along with gaps as large as <span class="math inline">\(-8\)</span> points. A gap of <span class="math inline">\(+5.0\)</span> points lies above the upper endpoint and is not a plausible value at this confidence level. The data do not support SAP’s claim, and they do not establish Nucleus’s headline either.</li>
<li>A difference has variance <span class="math inline">\(\operatorname{Var}(X)+\operatorname{Var}(Y)-2\operatorname{Cov}(X,Y)\)</span>. Companies in profitable industries tend to have high ROE themselves, and the sample correlation of 0.42 makes the covariance term positive. Subtracting the industry benchmark removes the part of each company’s ROE that is explained by its industry, leaving a difference whose standard deviation, 23.3 points, is below the 25.7 points of ROE alone. The standard error shrinks with it.</li>
<li>The paired comparison is the better answer to the question as posed. The chapter’s version treats 15.7% as a known constant, but it is the average of the 81 sampled companies’ industry benchmarks, and a different sample of 81 customers would have a different industry mix and a different benchmark average. Pairing each company with its own industry makes the benchmark part of the observation, so the sampling variability of the industry mix is included in the standard error rather than ignored.</li>
</ol>
</details>
</div></div>
</div>
<div id="exercise-reading-interval-statements" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 16.6: </strong>Reading a confidence interval</div><div class="fobx-body">
<p>A grocery delivery app takes a random sample of 400 orders from last month. The <strong>order value</strong> is the amount spent on an order. The sample mean order value is $64.20 and the sample standard deviation is $38.00, so the estimated standard error is <span class="math inline">\(38/\sqrt{400}=1.90\)</span> and the two-SE interval for the mean order value <span class="math inline">\(\mu\)</span> is <span class="math inline">\([60.4,\ 68.0]\)</span> dollars.</p>
<p>Decide whether each statement is a correct reading of the interval. Where it is not, say what is wrong and what a correct version would say.</p>
<ol type="1">
<li>“About 95% of orders have order values between $60.40 and $68.00.”</li>
<li>“There is a 95% probability that the mean order value across all of last month’s orders is between $60.40 and $68.00.”</li>
<li>“If we sampled another 400 orders, there is a 95% chance their sample mean would fall between $60.40 and $68.00.”</li>
<li>“A mean order value of $70 is not a plausible value at this level of confidence.”</li>
<li>“Sampling 1,600 orders instead of 400 would roughly halve the margin of error.”</li>
<li>“The mean order value last month was $64.20.”</li>
</ol>
<p>Finally, a free-delivery promotion breaks even if the mean order value is at least $62. What does the interval say about whether the promotion breaks even?</p>
<details aria-label="Solution" id="details-2" class="solution-details">
<summary>Solution</summary>
<ol type="1">
<li>Incorrect. The interval describes plausible values for the <em>mean</em> order value. The sample standard deviation of individual order values is $38, but the interval concerns uncertainty in the mean, not the spread of orders. A correct version: “the mean order value is plausibly anywhere from $60.40 to $68.00.”</li>
<li>This is the common mistake described in <a href="#sec-ci" class="quarto-xref"><span>Section 16.2.2</span></a>. The mean is a fixed number, and this particular interval either contains it or does not. The 95% describes the procedure: across repeated random samples of 400 orders, about 95% of intervals built this way contain the true mean.</li>
<li>Incorrect. The interval estimates the population mean; it is not an interval designed to contain the next sample mean with probability 0.95. A new sample mean varies around the unknown population mean, and the probability that it falls inside this particular interval is not given by the confidence level.</li>
<li>Correct. $70 lies above the interval’s upper endpoint, so the observed mean would be unusually far below the true mean if it were $70.</li>
<li>Correct, approximately. The standard error is <span class="math inline">\(s/\sqrt n\)</span>, so quadrupling <span class="math inline">\(n\)</span> halves it, provided the new sample’s standard deviation is close to $38.</li>
<li>Incorrect as stated. $64.20 is the sample mean, the estimate; the mean of all of last month’s orders is unknown. The interval is the honest report: the best estimate is $64.20, and values within about $3.80 of it cannot be ruled out.</li>
</ol>
<p>The break-even value of $62 lies inside the interval. The best estimate is above it, but a true mean below $62 is consistent with the data, so the sample cannot rule out a promotion that loses money. A decision needs either a larger sample or a judgment about how costly the downside is.</p>
</details>
</div></div>
</div>
<div id="exercise-sample-vs-population-size" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 16.7: </strong>Sample size, population size, and what the standard error leaves out</div><div class="fobx-body">
<p>A national bank with two million checking customers surveys 800 of them, chosen at random, on a ten-point satisfaction scale. A regional credit union with 20,000 members runs the same survey on 800 randomly chosen members. Both samples have a standard deviation of 2.0 points; the bank’s mean is 7.4 and the credit union’s is 7.9.</p>
<ol type="1">
<li>Compute the estimated standard error of each sample mean.</li>
<li>A bank executive argues that the credit union’s estimate must be far more precise, because 800 is 4% of its members but only 0.04% of the bank’s. Evaluate the argument.</li>
<li>The bank considers an alternative: email the survey to all two million customers. Suppose 60,000 respond, with a sample standard deviation of 2.0 points. Compute the standard error that formula would give for the mean of those 60,000 responses, and explain what that number does not capture. Which estimate would you trust more, the 800 random customers or the 60,000 volunteers?</li>
<li>Return to SAP’s objection that 81 companies out of 30,000 is too few to say anything. Which fact determines the precision of the Nucleus estimate: the fraction of customers sampled, or the sample size together with the spread of ROE? Then describe a different objection SAP could have raised about the 81 companies, which came from the customer list on SAP’s own website.</li>
</ol>
<details aria-label="Solution" id="details-3" class="solution-details">
<summary>Solution</summary>
<ol type="1">
<li>Both standard errors are <span class="math inline">\(2.0/\sqrt{800}\approx0.071\)</span> points. The formula uses the sample size and the spread of responses, and those are the same in both surveys.</li>
<li>The argument confuses the fraction sampled with the sample size. The sampling model treats the 800 responses as iid draws from the population’s distribution, and the precision of their average depends on how many draws there are and how variable each one is, not on how many customers went unsampled. Sampling without replacement from a smaller population does make the draws slightly dependent in a way that helps the credit union, but at 4% of the population the effect is a reduction of about 2% in the standard error, far from the executive’s “far more precise.”</li>
<li>The formula gives <span class="math inline">\(2.0/\sqrt{60{,}000}\approx0.008\)</span> points. That number describes sampling variability under the assumption that the 60,000 are a random sample of the two million, and they are not: they are the 3% who chose to answer. If dissatisfied customers respond more often, the mean of the volunteers is biased downward, and no sample size shrinks that bias. The standard error reports only the error that random sampling introduces. The 800 random customers give an estimate whose error the model can describe; the 60,000 volunteers give an estimate whose main error the model ignores.</li>
<li>The precision of the Nucleus estimate depends on <span class="math inline">\(n=81\)</span> and the spread of ROE, which gave a standard error of about 2.9 points, and not on the fraction 81/30,000. The better objection concerns how the 81 were chosen. Companies listed as customers on SAP’s website are the ones SAP chose to showcase, which need not resemble a random draw from all 30,000. If that list is unrepresentative, the estimate is biased in a direction the standard error cannot reveal, in either direction.</li>
</ol>
</details>
</div></div>
</div>
<div id="exercise-bootstrap-headline" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 16.8: </strong>Bootstrapping the headline</div><div class="fobx-body">
<p>Nucleus’s headline, “SAP customers are 20 percent less profitable than their peers,” is a ratio: the sample mean ROE divided by the average industry benchmark, minus one, or <span class="math inline">\(12.6/15.7-1\approx-19.5\%\)</span>. <a href="#fig-practice-boot-ratio" class="quarto-xref">Figure&nbsp;<span>16.11</span></a> shows 10,000 bootstrap values of this percentage difference, each computed from a resample of the 81 companies.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-practice-boot-ratio" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-practice-boot-ratio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="inference_01_sampling-distributions_files/figure-html/fig-practice-boot-ratio-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-practice-boot-ratio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.11: 10,000 bootstrap values of the percentage difference between the mean ROE of SAP customers and the average of their industry benchmarks. The dashed line marks the observed value of -19.5%; the bootstrap standard error is 16.5 percentage points.
</figcaption>
</figure>
</div>
</div>
</div>
<ol type="1">
<li>Why does <span class="math inline">\(s/\sqrt n\)</span> not give the standard error of this statistic?</li>
<li>Describe the bootstrap procedure that produced the figure. Explain why each resample draws whole rows of the data, keeping each company’s ROE together with its industry benchmark, rather than resampling the two columns separately.</li>
<li>The bootstrap standard error is 16.5 percentage points. Form the two-SE interval for the true percentage difference and say which of these are plausible values: parity with peers, Nucleus’s 20% deficit, and SAP’s advertised 32% advantage.</li>
<li>The 2.5th and 97.5th percentiles of the bootstrap values are -52.7% and 12.2%. Compare them with the two-SE interval and comment on whether the normal approximation is adequate here.</li>
<li>Compare this conclusion with the one from <a href="#exercise-sap-paired">the paired comparison above</a>, which measured the gap in percentage points rather than as a ratio.</li>
</ol>
<details aria-label="Solution" id="details-4" class="solution-details">
<summary>Solution</summary>
<ol type="1">
<li>The statistic is a ratio of two sample means, each of which varies from sample to sample, and the two vary together because a company’s ROE is correlated with its industry’s. The formula <span class="math inline">\(s/\sqrt n\)</span> describes the sampling variability of a single sample mean and says nothing about how a ratio of two correlated means varies.</li>
<li>Draw 81 companies from the 81 observed ones with replacement, compute the mean ROE and mean benchmark of the resample, form the percentage difference, and repeat 10,000 times. The standard deviation of the 10,000 values is the bootstrap standard error. Resampling rows preserves the pairing of each company with its industry benchmark. The correlation can vary from resample to resample. Resampling the columns separately would break that dependence and describe a different, incorrect sampling process.</li>
<li>The interval is <span class="math inline">\(-19.5\pm2(16.5)
\approx[-52.6\%,\ 13.6\%]\)</span>. Parity, at 0%, is inside it, and so is a 20% deficit; the data are also consistent with deficits far larger than Nucleus claimed. A 32% advantage lies well above the upper endpoint and is not plausible.</li>
<li>The percentile interval is close to the two-SE interval, and the bootstrap histogram is roughly bell-shaped with a mild skew, so the normal approximation is adequate for these purposes. The bootstrap has done two jobs here: it supplied a standard error that no simple formula gives, and it showed that the sampling distribution is close enough to normal for the two-SE interval to be reasonable.</li>
<li>Both analyses lead to the same reading of the dispute. Zero gap is plausible, Nucleus’s reported gap is plausible, and SAP’s advertised advantage is not. The substantive conclusion does not depend on which scale we use.</li>
</ol>
</details>
</div></div>
</div>
<div id="exercise-bootstrap-weight" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 16.9: </strong>How well do we know the minimum-variance weight?</div><div class="fobx-body">
<p>In <a href="./prob_09_combining-random-variables.html#exercise-minimum-variance-weight">Chapter 14</a>, the minimum-variance mix of the DAX and FTSE indices put a weight of 0.173 on the DAX, computed from 1,859 daily returns over 1991 through 1998. That weight is an estimate: a different eight years would have given a different number. <a href="#fig-practice-boot-alpha" class="quarto-xref">Figure&nbsp;<span>16.12</span></a> shows 5,000 bootstrap values of the weight, each computed from a resample of the 1,859 days. For these calculations, use an iid model for the daily pairs of returns; part 2 examines its limitations.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-practice-boot-alpha" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-practice-boot-alpha-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="inference_01_sampling-distributions_files/figure-html/fig-practice-boot-alpha-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-practice-boot-alpha-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.12: 5,000 bootstrap values of the minimum-variance weight on the DAX. The dashed line marks the estimate from the original sample, 0.173; the bootstrap standard error is 0.043.
</figcaption>
</figure>
</div>
</div>
</div>
<ol type="1">
<li>Why is the two-SE interval from <a href="#sec-ci" class="quarto-xref"><span>Section 16.2.2</span></a> not directly available for this statistic? What does the bootstrap supply?</li>
<li>Each bootstrap resample draws days with replacement, keeping each day’s DAX and FTSE returns together. Explain why the pairing must be kept, and what assumption about the days the resampling relies on. Use <a href="./prob_10_sums-averages-clt.html#exercise-returns-add-like-iid">the daily-returns exercise in Chapter 15</a> to explain why near-zero correlation between consecutive returns does not establish that assumption.</li>
<li>The bootstrap standard error is 0.043. Form the two-SE interval for the true minimum-variance weight. Is a weight of zero, meaning the FTSE alone, a plausible value? Is an even split?</li>
<li>The 2.5th and 97.5th bootstrap percentiles are 0.088 and 0.258. Compare them with the two-SE interval and with the shape of <a href="#fig-practice-boot-alpha" class="quarto-xref">Figure&nbsp;<span>16.12</span></a>.</li>
<li>Write two sentences advising a FTSE investor who asked for the variance-minimizing DAX allocation, conveying both the estimate and its uncertainty.</li>
</ol>
<details aria-label="Solution" id="details-5" class="solution-details">
<summary>Solution</summary>
<ol type="1">
<li>The weight is a ratio built from two sample variances and a sample covariance, and there is no simple formula like <span class="math inline">\(s/\sqrt n\)</span> for its standard error. The bootstrap supplies an estimate of that standard error and a picture of the sampling distribution’s shape, by recomputing the weight on repeated resamples of the observed days.</li>
<li>The weight depends on the covariance between the two indices, which lives in the pairing of each day’s two returns; resampling the columns separately would destroy it. Resampling days assumes the days are independent draws from a common distribution. Near-zero correlation in raw returns does not establish independence: large absolute returns can cluster even when signed returns are uncorrelated. The weight depends on variances and covariance, so that dependence can affect its uncertainty. The interval here is conditional on an iid approximation whose adequacy the earlier exercise does not establish.</li>
<li>The interval is <span class="math inline">\(0.173\pm2(0.043)
\approx[0.09,\ 0.26]\)</span>. Under the iid model, zero lies below the interval, so holding the FTSE alone is not a plausible variance-minimizing choice at this confidence level. An even split lies far above it and is not plausible either.</li>
<li>The percentiles nearly coincide with the two-SE endpoints, and the bootstrap histogram is roughly symmetric and bell-shaped. This supports the two-SE approximation within the iid resampling model; it does not check that model’s adequacy for dependent returns.</li>
<li>“Under an iid model for daily returns, the estimated DAX weight is 17%, with a two-SE interval from 9% to 26%. Dependence across days or changes in the return distribution could make that interval unreliable for an allocation decision.”</li>
</ol>
</details>
</div></div>
</div>
<div id="exercise-hmda-denials" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 16.10: </strong>Mortgage denial rates</div><div class="fobx-body">
<p>The <code>HMDA</code> data in the <code>AER</code> package come from a Federal Reserve Bank of Boston study of 2,380 mortgage applications in the Boston area in 1990. Each application was either denied or approved, and the data record whether the applicant was Black. <a href="#tbl-practice-hmda" class="quarto-xref">Table&nbsp;<span>16.2</span></a> gives the counts. Treat the applications as a random sample of mortgage applications in the area that year.</p>
<div class="cell">
<div id="tbl-practice-hmda" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-practice-hmda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;16.2: Mortgage applications and denials in the Boston HMDA data, 1990.
</figcaption>
<div aria-describedby="tbl-practice-hmda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">Applications</th>
<th style="text-align: right;">Denied</th>
<th style="text-align: right;">Denial rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Black applicants</td>
<td style="text-align: right;">339</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">28.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other applicants</td>
<td style="text-align: right;">2041</td>
<td style="text-align: right;">189</td>
<td style="text-align: right;">9.3%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<ol type="1">
<li>A denial rate is the average of a variable that equals 1 for a denied application and 0 otherwise. Using the variance of a 0/1 variable from <a href="./prob_10_sums-averages-clt.html#exercise-conversion-rate">the conversion-rate exercise in Chapter 15</a>, write the standard error of a sample proportion <span class="math inline">\(\hat p\)</span> based on <span class="math inline">\(n\)</span> applications.</li>
<li>Compute the estimated standard error and a two-SE interval for the denial rate among all applications in the area, and then separately for Black applicants and for other applicants.</li>
<li>The interval for Black applicants is about four times as wide as the interval for other applicants. Give the two reasons.</li>
<li>The difference between the two sample denial rates is 19.1 percentage points. Treating the two groups as independent samples, the standard error of the difference is <span class="math inline">\(\sqrt{SE_1^2+SE_2^2}\)</span>. Explain where that formula comes from, compute it, and form a two-SE interval for the difference in denial rates.</li>
<li>State carefully what the interval in part 4 does and does not establish. What questions would the Boston Fed’s researchers have needed to answer before interpreting the gap?</li>
</ol>
<details aria-label="Solution" id="details-6" class="solution-details">
<summary>Solution</summary>
<ol type="1">
<li>A 0/1 variable with mean <span class="math inline">\(p\)</span> has variance <span class="math inline">\(p(1-p)\)</span>, so the average of <span class="math inline">\(n\)</span> of them has standard deviation <span class="math inline">\(\sqrt{p(1-p)/n}\)</span>. Plugging in the sample proportion gives the estimated standard error <span class="math inline">\(\sqrt{\hat p(1-\hat p)/n}\)</span>.</li>
<li>Overall, <span class="math inline">\(\hat p=0.120\)</span> with standard error <span class="math inline">\(\sqrt{0.120(0.880)/2,380}\approx0.0067\)</span>, for an interval of about <span class="math inline">\([10.6\%,\ 13.3\%]\)</span>. For Black applicants, <span class="math inline">\(\hat p=0.283\)</span> with standard error 0.024 and interval <span class="math inline">\([23.4\%,\ 33.2\%]\)</span>. For other applicants, <span class="math inline">\(\hat p=0.093\)</span> with standard error 0.006 and interval <span class="math inline">\([8.0\%,\ 10.5\%]\)</span>.</li>
<li>The sample of Black applicants is about one sixth the size, which by itself multiplies the standard error by about <span class="math inline">\(\sqrt6\approx2.4\)</span>. Their denial rate is also closer to one half, where <span class="math inline">\(p(1-p)\)</span> is largest, which adds the rest of the difference.</li>
<li>The difference of two independent estimators has variance equal to the sum of their variances, by the variance rule for a difference with zero covariance; taking the square root gives the formula. Here the standard error is <span class="math inline">\(\sqrt{0.024^2+0.006^2}\approx0.025\)</span>, and the interval is about <span class="math inline">\([14.0,\ 24.1]\)</span> percentage points.</li>
<li>Under the sampling model, the interval excludes a zero gap by a wide margin, so random sampling variation alone is an implausible explanation for the observed difference. It does not say why the gap exists. Applicants differ in income, debt ratios, credit history, and the properties they sought, and the raw rates make no adjustment for any of that. The Boston Fed study’s central question was whether the gap survives after accounting for those characteristics, which requires the tools of the regression chapters. The interval here answers only the question of whether the raw gap could be sampling noise.</li>
</ol>
</details>
</div></div>
</div>
<div id="exercise-two-stores-two-intervals" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 16.11: </strong>Two stores, two intervals</div><div class="fobx-body">
<p>A retailer audits average transaction size at two stores. At Store A, a random sample of 64 transactions has mean $52 and standard deviation $16. At Store B, a random sample of 100 transactions has mean $58 and standard deviation $20.</p>
<ol type="1">
<li>Compute the two-SE interval for each store’s mean transaction size.</li>
<li>The two intervals overlap. The regional manager concludes that “the stores could easily have the same average, so there is no evidence of a difference.” Before computing anything more, say whether overlapping intervals justify that conclusion.</li>
<li>The estimated difference in means is $6. Treating the samples as independent, compute the standard error of the difference and a two-SE interval for the true difference in mean transaction size.</li>
<li>Reconcile parts 1 and 3. Why can two intervals overlap while the interval for their difference excludes zero?</li>
<li>What does the interval in part 3 say about the size of the difference, as opposed to its existence? How would you report the result?</li>
</ol>
<details aria-label="Solution" id="details-7" class="solution-details">
<summary>Solution</summary>
<ol type="1">
<li>Store A’s standard error is <span class="math inline">\(16/\sqrt{64}=2\)</span>, giving <span class="math inline">\([48,\ 56]\)</span>. Store B’s is <span class="math inline">\(20/\sqrt{100}=2\)</span>, giving <span class="math inline">\([54,\ 62]\)</span>.</li>
<li>No.&nbsp;Each interval describes plausible values for one mean on its own. Whether the two means could be equal is a question about their difference, which has its own sampling distribution and its own interval. Overlap is a rough visual check that is too conservative: it can fail to flag differences the data actually establish.</li>
<li>The difference of two independent estimators has variance equal to the sum of their variances, so the standard error is <span class="math inline">\(\sqrt{2^2+2^2}\approx2.83\)</span>. The interval is <span class="math inline">\(6\pm2(2.83)\)</span>, about <span class="math inline">\([0.3,\ 11.7]\)</span> dollars.</li>
<li>Two intervals fail to overlap only when the gap between the means exceeds the sum of the two margins, <span class="math inline">\(2(2)+2(2)=8\)</span> here. The interval for the difference excludes zero when the gap exceeds two standard errors of the difference, <span class="math inline">\(2\sqrt{2^2+2^2}\approx5.7\)</span>. The second threshold is smaller because standard errors add in quadrature, not directly. A gap of $6 clears the correct threshold and not the overlap test.</li>
<li>The interval says the true difference is plausibly anywhere from about 30 cents to nearly $12. The direction is reasonably well established, but the size is not: the data are consistent with a difference too small to act on and with one large enough to matter. A fair report gives the estimate of $6 and the interval together, rather than either “the stores differ” or “no evidence of a difference.”</li>
</ol>
</details>
</div></div>
</div>
<div id="exercise-audit-total" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 16.12: </strong>Estimating a total from a sample of invoices</div><div class="fobx-body">
<p>An auditor reviews a company’s 8,000 supplier invoices for the year. Checking every one is too costly, so the auditor draws 200 at random without replacement and records the overbilling on each, in dollars, with zero for a correct invoice. The sampled overbilling has mean $12.40 and standard deviation $60. Only 60 of the 200 invoices contained any error. For parts 1–3, use the iid approximation: 200 invoices are only 2.5% of the population.</p>
<ol type="1">
<li>Compute the estimated standard error and a two-SE interval for the mean overbilling per invoice across all 8,000.</li>
<li>The quantity that matters is the total overbilling, which is 8,000 times the mean. Give an estimate of the total and a two-SE interval for it. Which rule from the probability chapters lets you scale the interval this way?</li>
<li>The company treats total overbilling above $50,000 as material. What does the interval say about whether the total is material?</li>
<li>The auditor wants the margin of error for the total to be $20,000. First use $60 as the planning standard deviation and <span class="math inline">\(s/\sqrt n\)</span> to find a sample size. This would sample a substantial fraction of the invoices. For sampling without replacement from <span class="math inline">\(N=8{,}000\)</span>, the estimated SE of the mean is <span class="math inline">\(\dfrac{s}{\sqrt n}\sqrt{1-\dfrac nN}\)</span>. Use this correction to find the smallest whole-number sample size with a two-SE margin of at most $20,000 for the total.</li>
<li>Seventy percent of the sampled invoices had zero error, so the overbilling distribution is a spike at zero with a right tail. Does that shape threaten the interval in part 1? Say what would make you more or less comfortable with it.</li>
</ol>
<details aria-label="Solution" id="details-8" class="solution-details">
<summary>Solution</summary>
<ol type="1">
<li>The standard error is <span class="math inline">\(60/\sqrt{200}\approx4.24\)</span> dollars, and the interval is <span class="math inline">\(12.40\pm2(4.24)\)</span>, about <span class="math inline">\([3.9,\ 20.9]\)</span> dollars per invoice.</li>
<li>The estimated total is <span class="math inline">\(8{,}000(12.40)=99{,}200\)</span> dollars. Multiplying an estimator by a constant multiplies its standard error by the same constant, so the total’s standard error is <span class="math inline">\(8{,}000(4.24)\approx33{,}900\)</span> and the interval is about <span class="math inline">\([31{,}000,\ 167{,}000]\)</span> dollars. This is the scaling rule for the standard deviation of <span class="math inline">\(aX\)</span>.</li>
<li>The interval spans the threshold. A total below $50,000 is plausible, and so is one three times the threshold. The sample does not settle materiality; the best estimate is well above the line, but the uncertainty is too large to conclude either way.</li>
<li>A margin of $20,000 on the total is $2.50 on the mean. The iid calculation <span class="math inline">\(2(60)/\sqrt n=2.5\)</span> gives <span class="math inline">\(n=2{,}304\)</span>, more than a quarter of the population. With the correction, squaring <span class="math inline">\(2(60)\sqrt{1/n-1/8{,}000}\le2.5\)</span> gives <span class="math inline">\(n\ge 2{,}304/(1+2{,}304/8{,}000)\approx1{,}788.82\)</span>. Round up to 1,789 invoices. Sampling without replacement reduces uncertainty because each additional invoice leaves fewer unchecked.</li>
<li>If a few invoices have very large errors, the sample mean and standard deviation both depend heavily on whether those invoices were drawn. A sample that misses them can underestimate both the mean and its uncertainty. Inspecting the largest sampled errors or bootstrapping the mean can reveal sensitivity to the observed tail, but neither can reveal extreme errors absent from the sample. Information about such errors in the full invoice population would help assess the interval.</li>
</ol>
</details>
</div></div>
</div>
<div id="exercise-ceo-salaries" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 16.13: </strong>CEO pay and the uncertainty in a standard deviation</div><div class="fobx-body">
<p>The <code>ceosal1</code> data in the <code>wooldridge</code> package are a random sample of 209 chief executives’ 1990 salaries, in thousands of dollars, drawn from a <em>Businessweek</em> survey. The sample mean is $1,281 thousand, the median is $1,039 thousand, the standard deviation is $1,372 thousand, and the largest salary is $14,822 thousand. We bootstrapped the mean, the median, and the standard deviation, 10,000 resamples each.</p>
<div class="cell">
<div id="tbl-practice-ceo-boot" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-practice-ceo-boot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;16.3: Bootstrap standard errors and 2.5th and 97.5th percentiles for three summaries of the CEO salary sample, in thousands of dollars.
</figcaption>
<div aria-describedby="tbl-practice-ceo-boot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 11%">
<col style="width: 17%">
<col style="width: 22%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Summary</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Bootstrap SE</th>
<th style="text-align: right;">2.5th percentile</th>
<th style="text-align: right;">97.5th percentile</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean</td>
<td style="text-align: right;">1,281</td>
<td style="text-align: right;">94</td>
<td style="text-align: right;">1,120</td>
<td style="text-align: right;">1,486</td>
</tr>
<tr class="even">
<td style="text-align: left;">Median</td>
<td style="text-align: right;">1,039</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">937</td>
<td style="text-align: right;">1,115</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Standard deviation</td>
<td style="text-align: right;">1,372</td>
<td style="text-align: right;">369</td>
<td style="text-align: right;">608</td>
<td style="text-align: right;">2,020</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<ol type="1">
<li>Compute the formula standard error <span class="math inline">\(s/\sqrt n\)</span> for the mean salary and the two-SE interval. Compare the standard error with the bootstrap standard error in <a href="#tbl-practice-ceo-boot" class="quarto-xref">Table&nbsp;<span>16.3</span></a>.</li>
<li>The median’s bootstrap standard error is about half the mean’s. Explain why the median is estimated more precisely than the mean in this sample.</li>
<li>The bootstrap interval for the standard deviation runs from about $608 thousand to $2,020 thousand. Explain why the standard deviation is so uncertain, and what that means for any calculation in the earlier chapters that treated a sample standard deviation as if it were the population value.</li>
<li>A compensation committee asks what a typical CEO in this population earned. Which summary would you give them, with what interval, and what would you say about the population the sample represents?</li>
</ol>
<details aria-label="Solution" id="details-9" class="solution-details">
<summary>Solution</summary>
<ol type="1">
<li>The formula gives <span class="math inline">\(1,372/\sqrt{209}\approx95\)</span> thousand dollars, and the interval <span class="math inline">\([1,091,\ 1,471]\)</span>. The bootstrap standard error of 94 is nearly identical, as the technical note on the bootstrap for the mean in <a href="#sec-bootstrap" class="quarto-xref"><span>Section 16.4</span></a> predicts.</li>
<li>The mean moves whenever the largest salaries are included or excluded from a resample; the median depends only on the middle of the ordered sample and barely notices the tail. In a heavily skewed sample the median is both a more stable and a more representative summary of a typical value.</li>
<li>The standard deviation is dominated by the squared distance of the largest salary from the mean. Whether that one CEO appears zero, one, or several times in a resample changes <span class="math inline">\(s\)</span> by hundreds of thousands of dollars, so <span class="math inline">\(s\)</span> is estimated with a relative uncertainty of roughly 30%. Every calculation that plugged <span class="math inline">\(s\)</span> in for <span class="math inline">\(\sigma\)</span>, including the standard errors in this chapter, inherits that uncertainty; the effect is small when the data are well behaved and large when a few extreme values drive <span class="math inline">\(s\)</span>.</li>
<li>The median, about $1,039 thousand with a bootstrap interval of roughly $937 to $1,115 thousand, describes a typical CEO better than the mean, which a handful of very large salaries pull upward. The interval concerns the population represented by the magazine’s survey of 1990 salaries. Generalizing to all CEOs, or to a different year, would require evidence that the survey represents that population.</li>
</ol>
</details>
</div></div>
</div>
</section>
<section id="data-used-in-this-section" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="data-used-in-this-section">Data used in this section</h2>
<ul>
<li><a href="./appendix_data.html#sec-data-sap-nucleus">SAP Customer ROE</a> supplies the 81 companies’ ROE and industry benchmarks.</li>
<li><code>EuStockMarkets</code>, distributed with R, supplies the daily DAX and FTSE levels, 1991–1998.</li>
<li><code>HMDA</code> from the <code>AER</code> package supplies the Boston mortgage applications <span class="citation" data-cites="munnell-hmda-1996 aer-package">(<a href="appendix_data.html#ref-munnell-hmda-1996" role="doc-biblioref">Munnell et al. 1996</a>; <a href="appendix_data.html#ref-aer-package" role="doc-biblioref">Kleiber and Zeileis 2008</a>)</span>.</li>
<li><code>ceosal1</code> from the <code>wooldridge</code> package supplies the CEO salaries <span class="citation" data-cites="wooldridge-package">(<a href="appendix_data.html#ref-wooldridge-package" role="doc-biblioref">Shea 2024</a>)</span>.</li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-carr-sap-lies" class="csl-entry" role="listitem">
Carr, Nicholas. 2005. <em>Lies, Damned Lies and <span>IT</span> Statistics</em>. Rough Type (blog), November 8. <a href="https://www.roughtype.com/?p=150">https://www.roughtype.com/?p=150</a>.
</div>
<div id="ref-carr-sap-ads" class="csl-entry" role="listitem">
Carr, Nicholas. 2006. <em><span>SAP</span>’s Truth-Stretching Ads</em>. Rough Type (blog), January 18. <a href="https://www.roughtype.com/?p=225">https://www.roughtype.com/?p=225</a>.
</div>
<div id="ref-aer-package" class="csl-entry" role="listitem">
Kleiber, Christian, and Achim Zeileis. 2008. <em>Applied Econometrics with <span>R</span></em>. Springer-Verlag. <a href="https://doi.org/10.1007/978-0-387-77318-6">https://doi.org/10.1007/978-0-387-77318-6</a>.
</div>
<div id="ref-munnell-hmda-1996" class="csl-entry" role="listitem">
Munnell, Alicia H., Geoffrey M. B. Tootell, Lynn E. Browne, and James McEneaney. 1996. <span>“Mortgage Lending in Boston: Interpreting <span>HMDA</span> Data.”</span> <em>American Economic Review</em> 86 (1): 25–53.
</div>
<div id="ref-sap-nucleus" class="csl-entry" role="listitem">
Nucleus Research. 2006. <em><span>SAP</span> Customers Are 20 Percent Less Profitable Than Their Peers</em>. Research Note G12, Nucleus Research Inc., Wellesley, MA. <a href="https://www.oracle.com/us/corporate/analystreports/industries/059823.pdf">https://www.oracle.com/us/corporate/analystreports/industries/059823.pdf</a>.
</div>
<div id="ref-wooldridge-package" class="csl-entry" role="listitem">
Shea, Justin M. 2024. <em>Wooldridge: 115 Data Sets from <span>“Introductory Econometrics: A Modern Approach, 7e”</span> by Jeffrey m. Wooldridge</em>. <a href="https://CRAN.R-project.org/package=wooldridge">https://CRAN.R-project.org/package=wooldridge</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./prob_10_sums-averages-clt.html" class="pagination-link" aria-label="Sums, Averages, and the Central Limit Theorem">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Sums, Averages, and the Central Limit Theorem</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./inference_02_hypothesis-tests.html" class="pagination-link" aria-label="Hypothesis Tests and p-values">
        <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Hypothesis Tests and p-values</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>