<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>19&nbsp; Proportions and Comparisons Between Groups – TEMBA Statistics — Course Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./case_triangle-test.html" rel="next">
<link href="./inference_03_limits.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d3f7f8e73c8d287b30bcf59c2b563615.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/foldbox/foldbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>
.Definition {
  --color1: #F4EAF0;
  --color2: #7C3F58;
}
.Exercise {
  --color1: #E7F4F5;
  --color2: #147D85;
}
.TechnicalDetail {
  --color1: #EEF1F3;
  --color2: #5B6770;
}
.Example {
  --color1: #F4EFEA;
  --color2: #80644D;
}
.Notation {
  --color1: #EEF1F3;
  --color2: #5B6770;
}
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles/callouts.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./inference_01_sampling-distributions.html">Statistical Inference</a></li><li class="breadcrumb-item"><a href="./inference_04_proportions-comparisons.html"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Proportions and Comparisons Between Groups</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">TEMBA Statistics — Course Notes</a> 
        <div class="sidebar-tools-main">
    <a href="./../index.html" title="Course site" class="quarto-navigation-tool px-1" aria-label="Course site"><i class="bi bi-house-door"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Data analysis and visualization for one variable</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_01_visualizing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Visualizing a Single Quantitative Variable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_02_describing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Distributions of Quantitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_03_location-and-spread.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Measuring Location and Spread</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_04_transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Transforming Quantitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_05_categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Categorical Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Probability for one variable</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_01_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introduction to Probability and Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_02_probability-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Probability Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_03_distribution-parameters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Measures of Location and Spread (and Other Parameters of Probability Distributions)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_04_normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">The Normal Distribution</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Data analysis, visualizations, and probability models for multiple random variables</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_05_multivariate-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Joint, Marginal, and Conditional Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_06_probability-trees-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability Trees, Total Probability, and Bayes’ Rule</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_07_independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Independence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_08_quantitative-quantitative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Visualizing and Summarizing Two Quantitative Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Combining Random Variables</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_09_combining-random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Combining Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_10_sums-averages-clt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Sums, Averages, and the Central Limit Theorem</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_01_sampling-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Sampling Distributions and Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_02_hypothesis-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Hypothesis Tests and p-values</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_03_limits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">The Limits of Statistical Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_04_proportions-comparisons.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Proportions and Comparisons Between Groups</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./case_triangle-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Case Study: Can Customers Taste the Difference?</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slr_simple-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./case_market-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Case Study: The Market Model</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-proportion" id="toc-sec-proportion" class="nav-link active" data-scroll-target="#sec-proportion"><span class="header-section-number">19.1</span> A sample proportion</a>
  <ul class="collapse">
  <li><a href="#sec-test-proportion" id="toc-sec-test-proportion" class="nav-link" data-scroll-target="#sec-test-proportion"><span class="header-section-number">19.1.1</span> Testing a hypothesized proportion</a></li>
  <li><a href="#sec-margin-of-error" id="toc-sec-margin-of-error" class="nav-link" data-scroll-target="#sec-margin-of-error"><span class="header-section-number">19.1.2</span> Margin of error and sample size</a></li>
  </ul></li>
  <li><a href="#sec-diff-means" id="toc-sec-diff-means" class="nav-link" data-scroll-target="#sec-diff-means"><span class="header-section-number">19.2</span> A difference in means</a></li>
  <li><a href="#sec-diff-props" id="toc-sec-diff-props" class="nav-link" data-scroll-target="#sec-diff-props"><span class="header-section-number">19.3</span> A difference in proportions</a>
  <ul class="collapse">
  <li><a href="#sec-supplier" id="toc-sec-supplier" class="nav-link" data-scroll-target="#sec-supplier"><span class="header-section-number">19.3.1</span> When a detectable difference is too small to matter</a></li>
  </ul></li>
  <li><a href="#sec-more-sampling-summary" id="toc-sec-more-sampling-summary" class="nav-link" data-scroll-target="#sec-more-sampling-summary"><span class="header-section-number">19.4</span> Summary</a></li>
  <li><a href="#sec-more-sampling-practice" id="toc-sec-more-sampling-practice" class="nav-link" data-scroll-target="#sec-more-sampling-practice"><span class="header-section-number">19.5</span> Additional practice</a></li>
  <li><a href="#data-used-in-this-section" id="toc-data-used-in-this-section" class="nav-link" data-scroll-target="#data-used-in-this-section">Data used in this section</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./inference_01_sampling-distributions.html">Statistical Inference</a></li><li class="breadcrumb-item"><a href="./inference_04_proportions-comparisons.html"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Proportions and Comparisons Between Groups</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Proportions and Comparisons Between Groups</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In Chapter 7 we met the <a href="./prob_02_probability-basics.html#exercise-workplace-random-variables">hybrid-work experiment</a> that Bloom, Han, and Liang ran at Trip.com <span class="citation" data-cites="wfh-bloom">(<a href="appendix_data.html#ref-wfh-bloom" role="doc-biblioref">Bloom et al. 2024</a>)</span>. They randomly assigned 1,612 employees either to work in the office five days a week or to work from home two days a week, and then recorded who left the company during the study. In the office group 59 of the 820 employees left, or 7.2%. In the hybrid group it was 38 of 792, or 4.8%. That’s a gap of 2.4 percentage points, so attrition was about a third lower for the employees who could work from home. But we know that the two groups would have had different attrition rates even if hybrid work made no difference at all, just because different employees ended up in each group. Random assignment makes each group a random sample of the 1,612 employees in the study, so we will treat the two groups as independent random samples, just as we treated the <a href="./inference_01_sampling-distributions.html#sec-sap-dispute">SAP customers</a> as iid draws. How much of the 2.4 points could be due to chance?</p>
<p>We can’t answer that question yet. So far we have two tools, and both of them are for a population mean. The first is the <a href="./inference_01_sampling-distributions.html#sec-ci">confidence interval</a>: the estimate plus or minus two standard errors gives us a range of plausible values for the parameter. The second is the hypothesis test, where we use a <a href="./inference_02_hypothesis-tests.html">t-statistic</a> and its <a href="./inference_02_hypothesis-tests.html#defn-p-value">p-value</a> to measure how strong the evidence is against one particular hypothesized value. The t-statistic just counts how many standard errors there are between our estimate and the hypothesized value, and the p-value is the probability of seeing a test statistic at least as extreme as the one we observed if the hypothesized value were true (so smaller p-values mean stronger evidence against it). If you look back at how we got these tools, we only ever used two facts about the sample mean: its sampling distribution is approximately normal and centered at the true mean in the population or probability model, and we have an estimate of its standard error.</p>
<p>That means we can use the same tools for the hybrid-work experiment as soon as we have the right standard errors. An attrition rate is a proportion, so we start with the standard error of a sample proportion. The question is about the gap between two groups, so we also need a standard error for a difference. We work that out for a difference between two means first, and then for a difference between two proportions like the one above.</p>
<section id="sec-proportion" class="level2" data-number="19.1">
<h2 data-number="19.1" class="anchored" data-anchor-id="sec-proportion"><span class="header-section-number">19.1</span> A sample proportion</h2>
<p>We have already worked with proportions as averages. When we looked at <a href="./singlevar_05_categorical.html#sec-proportion-mean">loan defaults</a> we coded each loan with a dummy (or indicator) variable that is 1 if the loan defaulted and 0 if it didn’t, and the proportion of defaults was just the mean of that variable. The same is true for any sample proportion: it’s the sample mean of a variable that equals 1 when the outcome occurs and 0 otherwise.</p>
<p>Here’s an example. A marketing team shows 1,100 customers two advertisements for the same product. One was written by a person and the other was written by AI. Each customer sees the two ads in a random order, with nothing to indicate who wrote them, and picks the one they think the AI wrote. The customers make their choices independently, and 531 of them get it right. Let <span class="math inline">\(X_i=1\)</span> if customer <span class="math inline">\(i\)</span> correctly picks out the AI-written ad and <span class="math inline">\(X_i=0\)</span> if not. If we add up all the <span class="math inline">\(X_i\)</span> we get the number of correct answers, so the fraction of customers in our sample who got it right is just the sample mean of the <span class="math inline">\(X_i\)</span>:</p>
<p><span class="math display">\[
\hat p = \frac{1}{n}\sum_{i=1}^n X_i = \frac{531}{1{,}100} \approx 0.483.
\]</span></p>
<div id="defn-sample-proportion" class="Definition">
<div class="Definition fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-book fobx-icon" aria-hidden="true"></i><strong>Definition 19.1: </strong>Population and sample proportion</div><div class="fobx-body">
<p>The <strong>population proportion</strong> <span class="math inline">\(p\)</span> is the fraction of the population with the outcome we are interested in. We can also think of <span class="math inline">\(p\)</span> as the probability that a single unit drawn at random from the population has the outcome. Like <span class="math inline">\(\mu\)</span>, it’s a parameter — a fixed number that we don’t know.</p>
<p>The <strong>sample proportion</strong> <span class="math inline">\(\hat p\)</span> is the fraction of a random sample with the outcome, which is the sample mean of the 0/1 variable recording the outcome. It’s our estimator for <span class="math inline">\(p\)</span>. We will write <span class="math inline">\(\hat p\)</span> for the estimator and also for the estimate that we get from a particular sample.</p>
</div></div>
</div>
<p>We’ll treat the 1,100 participants as a random sample of the company’s customers and model their responses as iid draws, just like we did in the <a href="./inference_01_sampling-distributions.html#sec-sap-dispute">SAP example</a>. Then <span class="math inline">\(p\)</span> is the proportion of all the company’s customers who would correctly pick out the AI-written ad if we showed them this pair of ads. Each <span class="math inline">\(X_i\)</span> is a 0/1 random variable with mean <span class="math inline">\(p\)</span> and variance <span class="math inline">\(p(1-p)\)</span> (we derive these in the <a href="#technical-se-proportion">technical detail below</a>). Since <span class="math inline">\(\hat p\)</span> is <a href="./prob_10_sums-averages-clt.html#sec-sums-averages">an average of iid random variables</a> we already know the mean and standard deviation of its sampling distribution, and the <a href="./prob_10_sums-averages-clt.html#sec-clt">Central Limit Theorem</a> tells us the shape:</p>
<p><span class="math display">\[
\hat p \;\approx\; N\!\left(p,\; \frac{p(1-p)}{n}\right).
\]</span></p>
<p>In words: over many random samples the sample proportion is equal to <span class="math inline">\(p\)</span> on average, and the typical distance between <span class="math inline">\(\hat p\)</span> and <span class="math inline">\(p\)</span> shrinks like <span class="math inline">\(1/\sqrt n\)</span> as the sample size grows. This is exactly the sampling distribution of <span class="math inline">\(\bar X\)</span> that we had before, except that <span class="math inline">\(\sigma^2\)</span> is now <span class="math inline">\(p(1-p)\)</span>.</p>
<div id="note-se-proportion" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Standard error of a sample proportion
</div>
</div>
<div class="callout-body-container callout-body">
<p>For an iid sample of <span class="math inline">\(n\)</span> 0/1 observations with population proportion <span class="math inline">\(p\)</span>,</p>
<p><span class="math display">\[
SE(\hat p) = \sqrt{\frac{p(1-p)}{n}} \approx \sqrt{\frac{\hat p(1-\hat p)}{n}}.
\]</span></p>
<p>With 0/1 data the standard deviation is completely determined by <span class="math inline">\(p\)</span>, so we don’t need to compute <span class="math inline">\(s\)</span> separately. We don’t know <span class="math inline">\(p\)</span>, of course, so we plug in <span class="math inline">\(\hat p\)</span>. As usual the standard error tells us the typical size of the estimation error <span class="math inline">\(\hat p-p\)</span> across random samples.</p>
<p>For the normal approximation to work well we need to see enough of <em>both</em> outcomes in our sample. As we discussed in <a href="./prob_10_sums-averages-clt.html#sec-clt">Chapter 15</a> there isn’t one cutoff that works for every problem. If <span class="math inline">\(p\)</span> is close to 0 or 1 we will need a larger sample than if <span class="math inline">\(p\)</span> is close to one half, because the distribution of a 0/1 variable is very skewed when one of the outcomes is rare.</p>
</div>
</div>
<div id="technical-se-proportion" class="TechnicalDetail">
<details class="TechnicalDetail fobx-simplebox fobx-default"><summary><strong>Technical detail 19.1: </strong>Where <span class="math inline">\(p(1-p)\)</span> comes from, and why <span class="math inline">\(s/\sqrt n\)</span> gives the same answer</summary><div>
<p>If <span class="math inline">\(X\)</span> is a 0/1 random variable with <span class="math inline">\(\Pr(X=1)=p\)</span>, then its mean is <span class="math inline">\(E[X]=0(1-p)+1(p)=p\)</span>. The variance is the average squared deviation from the mean, weighting each deviation by its probability:</p>
<p><span class="math display">\[
\operatorname{Var}(X)=(0-p)^2(1-p)+(1-p)^2p = p(1-p)\left[p+(1-p)\right]=p(1-p).
\]</span></p>
<p>In fact we could have skipped all of this and computed the usual standard error <span class="math inline">\(s/\sqrt n\)</span> directly from the column of zeros and ones. With 0/1 data the sample variance turns out to be <span class="math inline">\(s^2=\frac{n}{n-1}\hat p(1-\hat p)\)</span>, so the only difference between the two standard errors is whether we divide by <span class="math inline">\(n-1\)</span> or <span class="math inline">\(n\)</span>. In the advertising study <span class="math inline">\(s/\sqrt n = 0.015073\)</span> and <span class="math inline">\(\sqrt{\hat p(1-\hat p)/n}=0.015067\)</span>, which are the same to four decimal places.</p>
</div></details>
</div>
<p>For the advertising study,</p>
<p><span class="math display">\[
SE(\hat p) \approx \sqrt{\frac{0.483(1-0.483)}{1{,}100}} \approx 0.015,
\]</span></p>
<p>or about 1.5 percentage points. We can use the same <a href="./inference_01_sampling-distributions.html#defn-confidence-interval">two-SE recipe</a> to get a confidence interval:</p>
<p><span class="math display">\[
0.483 \pm 2(0.015) \approx [0.453,\ 0.513].
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Interpretation: can customers identify the AI-written ad?
</div>
</div>
<div class="callout-body-container callout-body">
<p>The plausible values for the share of customers who would correctly identify the AI-written ad range from about 45.3% to about 51.3%. That range includes 50%, and it also includes 46%. If customers were just guessing between the two ads they would be right half the time, so what we saw is consistent with customers having no ability to tell the ads apart. If our sampling assumptions hold, we have estimated the share of correct answers to within about 3 percentage points.</p>
</div>
</div>
<div id="exercise-email-open-rate" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 19.1: </strong>An email open rate</div><div class="fobx-body">
<p>A marketing team sends a pilot version of a promotional email to a random sample of 850 customers, and 287 of them open it.</p>
<ol type="1">
<li>Estimate the open rate among all customers, and give an approximate 95% confidence interval.</li>
<li>For a campaign like this one the team considers 35% to be a good open rate. What does your interval tell you about how this campaign compares?</li>
</ol>
<details class="solution-details" id="solution-email-open-rate" aria-label="Solution">
<summary>Solution</summary>
<ol type="1">
<li>The sample proportion is <span class="math inline">\(\hat p=287/850\approx0.338\)</span> and its estimated standard error is <span class="math inline">\(\sqrt{0.338(0.662)/850}\approx0.016\)</span>. The interval is <span class="math inline">\(0.338\pm2(0.016)\approx[0.305,\ 0.370]\)</span>, or about 30.5% to 37.0%.</li>
<li>Our estimate of 33.8% is less than 35%, but 35% is inside the interval. Any open rate between 30.5% and 37.0% is plausible, so from this pilot we can’t say that the campaign falls short of the benchmark, and we can’t say that it meets the benchmark either. If it was important to know whether the campaign would reach 35%, the team should have thought about the margin of error when they decided how many customers to include in the pilot (see <a href="#sec-margin-of-error" class="quarto-xref"><span>Section 19.1.2</span></a>).</li>
</ol>
</details>
</div></div>
</div>
<section id="sec-test-proportion" class="level3" data-number="19.1.1">
<h3 data-number="19.1.1" class="anchored" data-anchor-id="sec-test-proportion"><span class="header-section-number">19.1.1</span> Testing a hypothesized proportion</h3>
<p>Our interval contains 50%, which is the accuracy we would expect if the customers were guessing blindly. We can use the <a href="./inference_02_hypothesis-tests.html">hypothesis test from Chapter 17</a> to measure how much evidence we have against that one particular value. The team decided before they collected any data that they would test for a difference from 50% in either direction. If we write <span class="math inline">\(p_0\)</span> for the hypothesized proportion, the hypotheses are <span class="math inline">\(H_0:p=0.5\)</span> and <span class="math inline">\(H_A:p\ne0.5\)</span>, and the <span class="math inline">\(t\)</span>-statistic looks just like it did before:</p>
<p><span class="math display">\[
T=\frac{\hat p-p_0}{SE(\hat p)},
\qquad
t=\frac{0.4827-0.5}{0.0151}\approx-1.15.
\]</span></p>
<p>So the sample proportion is about 1.15 standard errors below one half. When the null hypothesis is true <span class="math inline">\(T\)</span> has approximately a standard normal distribution, which gives us a two-sided p-value of about 0.25. That is, if customers really did identify the AI-written ad correctly half the time, in about a quarter of studies of this size we would see a sample proportion at least this far from 50% (in one direction or the other). With <span class="math inline">\(\alpha=0.05\)</span> we fail to reject the null hypothesis, which is what we should expect since <a href="./inference_02_hypothesis-tests.html#sec-ci-test">50% is inside the two-SE interval</a>. That doesn’t mean we have shown that customers are just guessing! All of the values from about 45.3% to 51.3% are still plausible.</p>
<div id="technical-null-se" class="TechnicalDetail">
<details class="TechnicalDetail fobx-simplebox fobx-default"><summary><strong>Technical detail 19.2: </strong>A standard error computed under the null</summary><div>
<p>You will see many textbooks and software packages that compute the standard error for a test of <span class="math inline">\(H_0:p=p_0\)</span> using the hypothesized value, as <span class="math inline">\(\sqrt{p_0(1-p_0)/n}\)</span>. The reasoning is that the test already assumes <span class="math inline">\(p=p_0\)</span>, so we may as well use it. In our example this gives <span class="math inline">\(\sqrt{0.5(0.5)/1{,}100}\approx0.01508\)</span>, compared to 0.01507 when we plug in <span class="math inline">\(\hat p\)</span>, and <span class="math inline">\(t=-1.15\)</span> in both cases. The two versions will be very close unless the sample is small or <span class="math inline">\(\hat p\)</span> is far away from <span class="math inline">\(p_0\)</span>. We always use the plug-in standard error so that we have one standard error for both the interval and the test. With the two-SE rule, the interval excludes a hypothesized value exactly when the <span class="math inline">\(t\)</span>-statistic for that value is larger than 2 in absolute value, which corresponds to testing at about the 5% level under the normal approximation.</p>
</div></details>
</div>
</section>
<section id="sec-margin-of-error" class="level3" data-number="19.1.2">
<h3 data-number="19.1.2" class="anchored" data-anchor-id="sec-margin-of-error"><span class="header-section-number">19.1.2</span> Margin of error and sample size</h3>
<p>When you see a “margin of error” reported for a sample proportion it is usually two standard errors, and it’s often computed in the worst case. The standard error depends on <span class="math inline">\(p\)</span> through <span class="math inline">\(p(1-p)\)</span>, and <span class="math inline">\(p(1-p)\)</span> is largest when <span class="math inline">\(p=0.5\)</span>, where it equals <span class="math inline">\(0.25\)</span>. At <span class="math inline">\(p=0.5\)</span>,</p>
<p><span class="math display">\[
SE(\hat p)=\sqrt{\frac{0.5(1-0.5)}{n}}=\frac{0.5}{\sqrt n},
\qquad\text{so}\qquad
2\,SE(\hat p)=\frac{1}{\sqrt n}.
\]</span></p>
<p>In words: no matter what the true proportion is, the two-SE margin of error from a random sample of <span class="math inline">\(n\)</span> customers can’t be bigger than <span class="math inline">\(1/\sqrt n\)</span>. The advertising study had 1,100 customers, so its margin of error is at most <span class="math inline">\(1/\sqrt{1{,}100}\approx0.030\)</span>, or 3 percentage points.</p>
<p>We don’t need any data to compute the worst-case margin, so we can use it to plan a study. If we want a margin of error of <span class="math inline">\(m\)</span> we solve <span class="math inline">\(m=1/\sqrt n\)</span> for <span class="math inline">\(n\)</span>:</p>
<p><span class="math display">\[
n = \frac{1}{m^2}.
\]</span></p>
<p>To guarantee a margin of at most 3 points we round up, to <span class="math inline">\(n=1,112\)</span> customers. <a href="#fig-margin-n" class="quarto-xref">Figure&nbsp;<span>19.1</span></a> shows how the worst-case margin changes with the sample size, along with the sample sizes we would need for margins of 3, 2, and 1 points.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-margin-n" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-margin-n-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="inference_04_proportions-comparisons_files/figure-html/fig-margin-n-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-margin-n-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;19.1: The worst-case margin of error for a sample proportion, 1/sqrt(n), plotted against the sample size. The marked points show the sample sizes that give margins of 3, 2, and 1 percentage points.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Going from a 3-point margin to a 2-point margin takes about 1,400 more customers, and going from 2 points to 1 point takes another 7,500. The margin shrinks like <span class="math inline">\(1/\sqrt n\)</span>, so to cut it in half we always need four times as many customers.</p>
<div id="note-margin-of-error" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Planning a sample size for a proportion
</div>
</div>
<div class="callout-body-container callout-body">
<p>For a random sample of size <span class="math inline">\(n\)</span> the two-SE margin of error for a proportion is at most <span class="math inline">\(1/\sqrt n\)</span>, so a sample of</p>
<p><span class="math display">\[
n \approx \frac{1}{m^2}
\]</span></p>
<p>guarantees a margin no larger than <span class="math inline">\(m\)</span>, if our sampling assumptions hold. When <span class="math inline">\(p\)</span> is far from one half this is a conservative guarantee. For example at <span class="math inline">\(p=0.1\)</span> the margin is <span class="math inline">\(2\sqrt{0.1(0.9)/n}=0.6/\sqrt n\)</span>, which is only 60% of the worst case. If we know from earlier data that <span class="math inline">\(p\)</span> is in some narrow range, we can plan using <span class="math inline">\(2\sqrt{p(1-p)/n}\)</span> instead, taking <span class="math inline">\(p\)</span> to be the end of the range that is closest to one half.</p>
</div>
</div>
<div id="exercise-remote-work-survey" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 19.2: </strong>A remote-work survey</div><div class="fobx-body">
<p>A technology company with 5,000 employees is considering a permanent remote-work policy. HR asks a random sample of 200 employees whether they would support the policy and 142 of them say yes. Management will only adopt the policy if more than 60% of all employees support it. Treat the responses as iid and assume that the normal approximation is adequate.</p>
<ol type="1">
<li>Compute an approximate 95% confidence interval for the proportion of all employees who support the policy.</li>
<li>Should management go ahead with the policy? Check your answer by computing the <span class="math inline">\(t\)</span>-statistic for the null hypothesis <span class="math inline">\(p=0.60\)</span>.</li>
</ol>
<details class="solution-details" id="solution-remote-work-survey" aria-label="Solution">
<summary>Solution</summary>
<ol type="1">
<li>The sample proportion is <span class="math inline">\(\hat p=142/200=0.71\)</span> and the estimated standard error is <span class="math inline">\(\sqrt{0.71(0.29)/200}\approx0.032\)</span>, so the interval is <span class="math inline">\(0.71\pm2(0.032)\approx[0.646,\ 0.774]\)</span>.</li>
<li>All of the plausible values are above 60% (the smallest is about 64.6%). The <span class="math inline">\(t\)</span>-statistic is <span class="math inline">\((0.71-0.60)/0.032\approx3.4\)</span>. The sample proportion is 3.4 standard errors above the threshold, so we reject <span class="math inline">\(p=0.60\)</span> at the 5% level. If the sampling assumptions hold, the survey supports going ahead.</li>
</ol>
</details>
</div></div>
</div>
</section>
</section>
<section id="sec-diff-means" class="level2" data-number="19.2">
<h2 data-number="19.2" class="anchored" data-anchor-id="sec-diff-means"><span class="header-section-number">19.2</span> A difference in means</h2>
<p>So far we have estimated one mean at a time, but many practical questions are comparisons. Suppose a company pilots an AI chatbot for customer support and finds that the chatbot’s conversations get lower satisfaction scores, on average, than conversations with human agents. Is the chatbot actually worse? Maybe, but we know that two sample means will differ from each other even when the population means are the same, so before we conclude anything we should ask how big a gap sampling variation alone could plausibly produce.</p>
<p>We’ll call the two groups <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> and write <span class="math inline">\(\mu_A\)</span> and <span class="math inline">\(\mu_B\)</span> for their population means. The parameter we want to learn about is the difference <span class="math inline">\(\mu_A-\mu_B\)</span>. Our data are two independent random samples with sample sizes <span class="math inline">\(n_A\)</span> and <span class="math inline">\(n_B\)</span>, and the natural estimator is the difference in the sample means, <span class="math inline">\(\bar X_A-\bar X_B\)</span>.</p>
<p>We already know that on average each sample mean is equal to its own population mean, and the mean of a difference is the difference of the means, so <span class="math inline">\(E[\bar X_A-\bar X_B]=\mu_A-\mu_B\)</span>. To get the standard error we need the variance of <span class="math inline">\(\bar X_A-\bar X_B\)</span>, which we can find using the <a href="./prob_09_combining-random-variables.html#sec-lincom-rules">rule for the variance of a difference</a> from the chapter on combining random variables. The samples are independent, so the covariance is zero and we are left with the sum of the two variances:</p>
<p><span class="math display">\[
\operatorname{Var}(\bar X_A-\bar X_B)=\operatorname{Var}(\bar X_A)+\operatorname{Var}(\bar X_B)=\frac{\sigma_A^2}{n_A}+\frac{\sigma_B^2}{n_B}.
\]</span></p>
<p>It may seem strange that we add the variances when we are subtracting the means. The reason is that the estimation error in <span class="math inline">\(\bar X_A\)</span> and the estimation error in <span class="math inline">\(\bar X_B\)</span> both end up in the difference, and since the samples are independent there’s no reason to expect those errors to cancel. We also know that a difference of two independent (approximately) normal random variables is again approximately normal. That means everything we did for a single mean (the two-SE interval, the <span class="math inline">\(t\)</span>-statistic) works here too, as soon as we have a standard error.</p>
<div id="note-se-diff-means" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Standard error of a difference in means
</div>
</div>
<div class="callout-body-container callout-body">
<p>For independent iid samples from groups <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>,</p>
<p><span class="math display">\[
SE(\bar X_A-\bar X_B)=\sqrt{\frac{\sigma_A^2}{n_A}+\frac{\sigma_B^2}{n_B}}
\approx\sqrt{\frac{s_A^2}{n_A}+\frac{s_B^2}{n_B}},
\]</span></p>
<p>where <span class="math inline">\(s_A\)</span> and <span class="math inline">\(s_B\)</span> are the sample standard deviations in the two groups. This is the same as <span class="math inline">\(\sqrt{SE(\bar X_A)^2+SE(\bar X_B)^2}\)</span>, so if you already have a standard error for each group you can square them, add them up, and take the square root. Just as before, the standard error tells us how far off our estimate of the difference is likely to be, over repeated pairs of samples. It will always be bigger than the larger of the two groups’ standard errors, but smaller than what we would get by adding them together.</p>
</div>
</div>
<p>This formula is only for independent samples: knowing which units we sampled from group <span class="math inline">\(A\)</span> should tell us nothing about the units we sampled from group <span class="math inline">\(B\)</span>. Paired data are different. If we measure the same stores before and after a price change, for example, each “before” observation is matched to an “after” observation from the same store and the two samples are dependent. With paired data we compute the difference within each pair, and then treat those differences as a single sample (see <a href="#exercise-paired-assay">the paired assay exercise</a> below).</p>
<p>Let’s look at an example. A tech company trains new hires using one of two coding bootcamps, an intensive program and a standard program, and wants to compare them. The company takes a random sample of employees who completed each program and gives all of them the same standardized coding exercise. No employee is in both samples, and the employees we happen to draw from one program have no effect on who gets drawn from the other, so it’s reasonable to model the two samples as independent. <a href="#tbl-bootcamp" class="quarto-xref">Table&nbsp;<span>19.1</span></a> has the summary statistics.</p>
<div class="cell">
<div id="tbl-bootcamp" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-bootcamp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;19.1: Scores on a standardized coding exercise for employees who completed each bootcamp.
</figcaption>
<div aria-describedby="tbl-bootcamp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Program</th>
<th style="text-align: right;">Employees</th>
<th style="text-align: right;">Mean score</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">SE of mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intensive</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">129</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">2.39</td>
</tr>
<tr class="even">
<td style="text-align: left;">Standard</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">3.54</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The average score was 9 points higher in the intensive group, so 9 points is our estimate of the difference in mean scores between <em>all</em> the employees who might take the intensive program and <em>all</em> those who might take the standard program. Of course there are only 120 employees in this study, and with a different 120 we would have seen a different gap. The standard error of the difference is</p>
<p><span class="math display">\[
SE(\bar X_A-\bar X_B)\approx\sqrt{\frac{20^2}{70}+\frac{25^2}{50}}\approx4.27\text{ points},
\]</span></p>
<p>and the approximate 95% confidence interval is</p>
<p><span class="math display">\[
9\pm2(4.27)\approx[0.5,\ 17.5]\text{ points}.
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Interpretation: direction and size
</div>
</div>
<div class="callout-body-container callout-body">
<p>All of the plausible values for the difference are positive. If our sampling assumptions hold, then, we have evidence that the mean score is higher for the intensive program. We know much less about how much higher — the plausible values run from about half a point to about 18 points. That matters if the intensive program costs more money or takes more of the employees’ time, since a half point improvement is probably not worth paying for and an 18 point improvement might well be.</p>
</div>
</div>
<p>We can also test the null hypothesis that there is no difference between the programs, <span class="math inline">\(H_0:\mu_A-\mu_B=0\)</span>, against the alternative <span class="math inline">\(H_A:\mu_A-\mu_B\ne0\)</span>. The <span class="math inline">\(t\)</span>-statistic is</p>
<p><span class="math display">\[
t=\frac{(\bar x_A-\bar x_B)-0}{SE(\bar X_A-\bar X_B)}=\frac{9}{4.27}\approx2.11,
\]</span></p>
<p>and the two-sided p-value is about 0.035. In other words, if the mean scores were really the same for both programs, only about 3.5% of studies like this one would give a difference that is 2.11 or more standard errors away from zero. With <span class="math inline">\(\alpha=0.05\)</span> we reject the null hypothesis, as we should have expected since zero isn’t in the 95% confidence interval.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Common mistake: Judging a difference by whether two intervals overlap
</div>
</div>
<div class="callout-body-container callout-body">
<p>If we compute a two-SE interval for each program’s mean separately we get <span class="math inline">\([124.2,\ 133.8]\)</span> for the intensive program and <span class="math inline">\([112.9,\ 127.1]\)</span> for the standard program. These two intervals overlap, even though the interval for the difference doesn’t include zero!</p>
<p>What’s going on? For the two intervals to be completely separated the gap between the sample means has to be bigger than the two margins of error added together, which here is <span class="math inline">\(2(2.39)+2(3.54)\approx11.9\)</span> points. For the interval for the difference to exclude zero the gap only has to be bigger than <span class="math inline">\(2\sqrt{2.39^2+3.54^2}\approx8.5\)</span> points. The second threshold is always the smaller one (the square root of a sum of squares is smaller than the sum), and our 9-point gap is in between. So checking for overlap can miss real differences, and when the question is about a difference we should compute the interval for the difference.</p>
</div>
</div>
<p>Can we say that the intensive program caused the higher scores? Only if the employees in the standard program tell us how the employees in the intensive program <em>would have scored if they had taken the standard program</em> instead (and vice versa). Put another way, if we had given both groups the same program we should expect to see similar average scores, up to sampling variation.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The direction of selection bias
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose that the stronger or more motivated employees were the ones who chose the intensive program. Then the comparison is biased in favor of the intensive program, since the difference in scores reflects the differences in skill and motivation as well as whatever effect the program has. It could easily go the other way — if managers sent their weaker employees to the intensive program, those employees might score lower even if the program helped them quite a bit, and the comparison would be biased against the intensive program. Just as we saw with the SAP customers, a confidence interval only accounts for sampling variability. It does nothing about <a href="./inference_03_limits.html">selection bias</a>.</p>
</div>
</div>
<p>Random assignment avoids this problem. If we assign employees to programs at random, their ability, motivation, and everything else about them has no influence on which program they get. The two groups will still differ somewhat by chance, but those differences are no longer systematic, and chance differences are what our standard errors measure. Then we can take a difference in scores as evidence about the effect of the program.</p>
<div id="exercise-two-teams" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 19.3: </strong>A first comparison of means</div><div class="fobx-body">
<p>A company takes independent random samples of 100 tickets from each of its two service teams. Team A’s tickets had a mean resolution time of 18 hours with a standard deviation of 10 hours, and Team B’s tickets had a mean of 15 hours, also with a standard deviation of 10 hours. Assume that the normal approximation is adequate for each sample mean.</p>
<ol type="1">
<li>Estimate <span class="math inline">\(\mu_A-\mu_B\)</span> and find the standard error of your estimate. Then compute the two-SE interval.</li>
<li>What does the sign of the interval tell you? Is it plausible that the difference in the population is four hours?</li>
<li>Suppose you reported B minus A instead. What happens to the estimate, the standard error, and the interval?</li>
</ol>
<details class="solution-details" id="solution-two-teams" aria-label="Solution">
<summary>Solution</summary>
<ol type="1">
<li>Our estimate is <span class="math inline">\(18-15=3\)</span> hours. The standard error of each sample mean is <span class="math inline">\(10/\sqrt{100}=1\)</span> hour, so the standard error of the difference is <span class="math inline">\(\sqrt{1^2+1^2}\approx1.41\)</span> hours, and the interval is <span class="math inline">\(3\pm2(1.41)\approx[0.17,\ 5.83]\)</span> hours.</li>
<li>The entire interval is above zero, so (under our sampling model) Team A’s tickets take longer on average. We are less sure about how much longer. Any difference from about 0.2 hours to about 5.8 hours is plausible, and that includes four hours.</li>
<li>The estimate would be <span class="math inline">\(-3\)</span> hours and the interval would be <span class="math inline">\([-5.83,\ -0.17]\)</span> hours. The standard error is still 1.41 hours. It measures how variable the estimate is, and that doesn’t depend on which mean we subtract from which.</li>
</ol>
</details>
</div></div>
</div>
<div id="exercise-cloud-on-premise" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 19.4: </strong>Cloud and on-premise response times</div><div class="fobx-body">
<p>A company wants to compare application response times for cloud and on-premise deployments of its software. It runs a benchmark where 28 cloud instances average 92.4 milliseconds with a standard deviation of 15.6, and 35 on-premise instances average 89.7 milliseconds with a standard deviation of 18.2. Treat the two sets of instances as independent random samples, and assume that the normal approximation is adequate for each sample mean.</p>
<ol type="1">
<li>Compute an approximate 95% confidence interval for the difference in mean response time (cloud minus on-premise).</li>
<li>Can the company conclude that the mean response times are different for the two deployments? Can it conclude that they are the same?</li>
</ol>
<details class="solution-details" id="solution-cloud-on-premise" aria-label="Solution">
<summary>Solution</summary>
<ol type="1">
<li>The standard errors are <span class="math inline">\(15.6/\sqrt{28}\approx2.95\)</span> milliseconds for cloud and <span class="math inline">\(18.2/\sqrt{35}\approx3.08\)</span> milliseconds for on-premise. The difference in means is <span class="math inline">\(92.4-89.7=2.7\)</span> milliseconds and its standard error is <span class="math inline">\(\sqrt{2.95^2+3.08^2}\approx4.26\)</span>, so the interval is <span class="math inline">\(2.7\pm2(4.26)\approx[-5.8,\ 11.2]\)</span> milliseconds.</li>
<li>Zero is a plausible value for the difference and <span class="math inline">\(t=2.7/4.26\approx0.63\)</span>, so we fail to reject the null hypothesis that the means are equal. But that isn’t the same thing as showing that the two deployments perform equally well! The cloud deployment could be 11 milliseconds slower on average, or it could be almost 6 milliseconds faster, and the data are consistent with both. Whether differences like these are important will depend on the application. If they are, the company needs to benchmark more instances.</li>
</ol>
</details>
</div></div>
</div>
<div id="exercise-support-training" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 19.5: </strong>Did the training shorten response times?</div><div class="fobx-body">
<p>A company introduces a training program to try to reduce response times to support tickets. From its customer research the company believes that customers won’t notice an improvement of less than 30 minutes. To evaluate the program the company takes a random sample of 42 tickets from before the training, which averaged 245 minutes with a standard deviation of 65, and a random sample of 38 tickets from after the training, which averaged 210 minutes with a standard deviation of 58.</p>
<ol type="1">
<li>Compute an approximate 95% confidence interval for the reduction in mean response time (before minus after). Is it plausible that the reduction is zero?</li>
<li>Should the company expect its customers to notice the improvement? Compute the <span class="math inline">\(t\)</span>-statistic for the null hypothesis that the reduction is 30 minutes.</li>
<li>The two samples were taken in different months. What else would you want to know before you decide that the training is responsible for the reduction?</li>
</ol>
<details class="solution-details" id="solution-support-training" aria-label="Solution">
<summary>Solution</summary>
<ol type="1">
<li>The standard errors of the two sample means are <span class="math inline">\(65/\sqrt{42}\approx10.03\)</span> and <span class="math inline">\(58/\sqrt{38}\approx9.41\)</span> minutes, so the standard error of the difference is <span class="math inline">\(\sqrt{10.03^2+9.41^2}\approx13.75\)</span> minutes and the interval is <span class="math inline">\(35\pm2(13.75)=[7.5,\ 62.5]\)</span> minutes. Zero is outside the interval and <span class="math inline">\(t=35/13.75\approx2.5\)</span>. If our sampling assumptions hold, the mean response time went down.</li>
<li>Our estimate of 35 minutes is larger than the 30-minute threshold, but the threshold is well inside the interval and <span class="math inline">\(t=(35-30)/13.75\approx0.36\)</span>. The plausible reductions go from 7.5 minutes (which customers wouldn’t notice) all the way to 62.5 minutes (which they would). So we have good evidence that response times improved, but we can’t say whether they improved enough for customers to notice.</li>
<li>When we compare before and after, anything that changed between the two periods gets attributed to the training. Ticket volume, the mix of easy and hard tickets, staffing, and the time of year could all have affected response times. A better design would stagger the training across randomly chosen teams, so that we could compare trained and untrained teams during the same weeks. Then a change that comes from the calendar would show up in both groups.</li>
</ol>
</details>
</div></div>
</div>
<div id="exercise-paired-assay" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 19.6: </strong>Same tablets, two measurements</div><div class="fobx-body">
<p>A drug manufacturer is evaluating a handheld assay that is faster than its standard lab assay. A quality lab takes a random sample of 36 tablets from a large production run and measures every tablet twice, once with the handheld device and once with the lab assay. For each tablet we compute the difference between the handheld reading and the lab reading (handheld minus lab). The differences have a mean of 1.5 mg and a sample standard deviation of 3 mg. Model the differences as iid, and assume that the normal approximation is adequate for their mean.</p>
<ol type="1">
<li>Compute a two-SE interval for the population mean difference.</li>
<li>Explain why the sample size is <span class="math inline">\(n=36\)</span> and not 72. If we computed separate standard deviations for the handheld and lab readings and combined them, what information would we be throwing away?</li>
<li>The company will accept the device if its readings differ from the lab assay by less than 3 mg on average, in either direction. What does the interval tell you about that standard? Does it tell you how far off a single handheld reading could be from the lab value?</li>
</ol>
<details class="solution-details" id="solution-paired-assay" aria-label="Solution">
<summary>Solution</summary>
<ol type="1">
<li>The estimated standard error is <span class="math inline">\(3/\sqrt{36}=0.5\)</span> mg, so the interval is <span class="math inline">\(1.5\pm2(0.5)=[0.5,\ 2.5]\)</span> mg. Under our model the handheld device gives higher readings than the lab assay, on average.</li>
<li>We have 36 differences, one for each tablet, and the tablets are independent. The two readings on the same tablet are not: both of them depend on how much of the drug is really in that tablet, so they are positively correlated. When we take the difference the tablet-to-tablet variation in content cancels out. The standard deviation of the differences already accounts for that covariance. If we used the formula for independent samples we would be ignoring it, and our standard error would be too large.</li>
<li>All of the plausible values for the mean difference are between 0.5 and 2.5 mg, which is inside the 3 mg standard, so the data support accepting the device as far as the average is concerned. But the interval is only about the mean difference. The differences for individual tablets have a standard deviation of 3 mg, so a single handheld reading can easily miss the lab value by more than 3 mg.</li>
</ol>
</details>
</div></div>
</div>
</section>
<section id="sec-diff-props" class="level2" data-number="19.3">
<h2 data-number="19.3" class="anchored" data-anchor-id="sec-diff-props"><span class="header-section-number">19.3</span> A difference in proportions</h2>
<p>We just saw that a proportion is the mean of a 0/1 variable, so everything we did for a difference in means works for a difference in proportions. The only change is that we use <span class="math inline">\(SE(\hat p)\)</span> where we had <span class="math inline">\(s/\sqrt n\)</span>. The parameter is <span class="math inline">\(p_A-p_B\)</span> and we estimate it with <span class="math inline">\(\hat p_A-\hat p_B\)</span>. The samples are independent, so just like before the variances add.</p>
<div id="note-se-diff-props" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Standard error of a difference in proportions
</div>
</div>
<div class="callout-body-container callout-body">
<p>For independent iid samples of 0/1 observations from groups <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>,</p>
<p><span class="math display">\[
SE(\hat p_A-\hat p_B)\approx\sqrt{\frac{\hat p_A(1-\hat p_A)}{n_A}+\frac{\hat p_B(1-\hat p_B)}{n_B}}
=\sqrt{SE(\hat p_A)^2+SE(\hat p_B)^2}.
\]</span></p>
<p>For the normal approximation to work well we need enough of both outcomes in <em>each</em> of the two groups. If we write the proportions as percentages, then the estimated difference and its standard error are in <strong>percentage points</strong>.</p>
</div>
</div>
<p>Here is an example. A manufacturer has to choose between two suppliers for a critical component. When a part is defective it delays production, so the company spends six months evaluating the suppliers and inspects 15,000 parts from each one. Supplier A is the company’s current supplier, and the cheaper of the two. Of the parts from Supplier A, 180 are defective, compared to 120 of the parts from Supplier B, so the defect rates are 1.2% and 0.8%. The difference in defect rates is 0.4 percentage points, with</p>
<p><span class="math display">\[
SE(\hat p_A-\hat p_B)\approx\sqrt{\frac{0.012(0.988)}{15{,}000}+\frac{0.008(0.992)}{15{,}000}}\approx0.00115,
\]</span></p>
<p>or about 0.11 percentage points. The approximate 95% confidence interval is</p>
<p><span class="math display">\[
0.4\pm2(0.11)\approx[0.17,\ 0.63]\text{ percentage points},
\]</span></p>
<p>and the <span class="math inline">\(t\)</span>-statistic for testing a difference of zero is 3.5. If our sampling assumptions hold, Supplier A’s parts really are worse.</p>
<p>What are those assumptions? For the normal approximation we are treating the parts we inspected from each supplier as independent draws from that supplier’s production. That’s not the same as assuming that what each supplier produces in the future will look like a random sample of all the settings where the company might use these components, and nothing in our calculation justifies that.</p>
<section id="sec-supplier" class="level3" data-number="19.3.1">
<h3 data-number="19.3.1" class="anchored" data-anchor-id="sec-supplier"><span class="header-section-number">19.3.1</span> When a detectable difference is too small to matter</h3>
<p>Should the company switch suppliers? That depends on the costs. Supplier A charges $12 per part and Supplier B charges $15. The company uses 50,000 parts every year, so switching to B would cost an extra $150,000 per year. On the other hand each defective part costs the company about $450 in downtime and replacement. If the difference in defect rates is 0.4 points (our estimate), staying with A means <span class="math inline">\(50{,}000(0.004)=200\)</span> more defective parts per year at a cost of $90,000. That’s $60,000 less than the extra money the company would pay to Supplier B.</p>
<p>We can’t stop there, because the true difference in defect rates could be larger than 0.4 points. It only makes sense to switch if the additional defects cost more than the price premium, and for that to happen the difference in defect rates has to be bigger than the break-even value</p>
<p><span class="math display">\[
\frac{\$150{,}000}{\$450\times50{,}000}\approx0.0067,
\]</span></p>
<p>or 0.67 percentage points. In <a href="#fig-supplier-decision" class="quarto-xref">Figure&nbsp;<span>19.2</span></a> we show the interval along with the two differences that matter for this decision, zero and the break-even value.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-supplier-decision" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-supplier-decision-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="inference_04_proportions-comparisons_files/figure-html/fig-supplier-decision-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-supplier-decision-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;19.2: The 95% confidence interval for the difference in defect rates (Supplier A minus Supplier B). Zero and the break-even difference are marked, and both are outside the interval.
</figcaption>
</figure>
</div>
</div>
</div>
<p>We reject a difference of zero. We also reject the break-even difference (<span class="math inline">\(t=-2.3\)</span>). Even if the difference were as large as the upper endpoint of the interval, the additional defects would cost the company $141,700 per year, which is still less than the $150,000 premium. So the company saves money by staying with Supplier A, even though we are quite sure that Supplier A’s parts are worse.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Common mistake: Reading statistical significance as practical importance
</div>
</div>
<div class="callout-body-container callout-body">
<p>Statistical significance is about the evidence against one hypothesized value, which is usually a difference of zero. It doesn’t tell us whether the difference is big enough to matter. If the sample is large enough, a very small difference can be statistically significant.</p>
<p>For example, a training program that raises scores by a fraction of a point might not be worth three days away from work. On the other hand, a checkout redesign that adds one purchase per 10,000 visits could pay for itself if the site has millions of visitors. Whether a difference is important in practice depends on the costs and benefits of the decision, and on its scale. To find out, compare the confidence interval to the differences that would change what you do.</p>
</div>
</div>
<div id="technical-pooled-se" class="TechnicalDetail">
<details class="TechnicalDetail fobx-simplebox fobx-default"><summary><strong>Technical detail 19.3: </strong>A pooled standard error for testing equal proportions</summary><div>
<p>When the null hypothesis <span class="math inline">\(p_A=p_B\)</span> is true the two groups have the same proportion. Many textbooks and software packages estimate that common proportion by pooling the two groups, <span class="math inline">\(\bar p=(\text{total with the outcome})/(n_A+n_B)\)</span>, and use it to compute a standard error under the null. That standard error is</p>
<p><span class="math display">\[
\sqrt{\bar p(1-\bar p)\left(\frac{1}{n_A}+\frac{1}{n_B}\right)}.
\]</span></p>
<p>In the supplier evaluation <span class="math inline">\(\bar p=0.0100\)</span> and the pooled standard error is 0.001149, while the unpooled standard error is 0.001149. The <span class="math inline">\(t\)</span>-statistics are 3.48 and 3.48, so to this many digits we can’t tell them apart. The pooled standard error is only for testing a difference of zero. For the confidence interval, or for testing any other value (like our break-even difference), we use the unpooled standard error from <a href="#note-se-diff-props">the rule above</a>.</p>
</div></details>
</div>
<div id="exercise-ab-test-conversions" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 19.7: </strong>An A/B test</div><div class="fobx-body">
<p>An e-commerce site randomly assigns each visitor to one of two page designs. In this test Variant A converted 156 of its 820 visitors and Variant B converted 171 of its 830.</p>
<ol type="1">
<li>Compute an approximate 95% confidence interval for the difference in conversion rates (B minus A).</li>
<li>Based on these results, should the company switch to Variant B?</li>
</ol>
<details class="solution-details" id="solution-ab-test-conversions" aria-label="Solution">
<summary>Solution</summary>
<ol type="1">
<li>The sample proportions are <span class="math inline">\(156/820\approx0.190\)</span> for A and <span class="math inline">\(171/830\approx0.206\)</span> for B, and their standard errors are 0.0137 and 0.0140. The difference is 1.6 percentage points and its standard error is <span class="math inline">\(\sqrt{0.0137^2+0.0140^2}\approx0.0196\)</span>. That gives us the interval <span class="math inline">\(0.016\pm2(0.0196)\approx[-0.023,\ 0.055]\)</span>, or <span class="math inline">\(-2.3\)</span> to <span class="math inline">\(5.5\)</span> percentage points.</li>
<li>Zero is in the interval and <span class="math inline">\(t=0.016/0.0196\approx0.8\)</span>, so we don’t detect a difference between the two designs. The range of plausible values is wide, though. Variant A could convert 2.3 points better, or Variant B could convert 5.5 points better, and when conversion rates are around 20% either one would be a large effect. So this test doesn’t tell the company what to do. To choose between the designs the company needs to know what an additional conversion is worth, and what it would cost to switch.</li>
</ol>
</details>
</div></div>
</div>
<div id="exercise-checkout-payment-method" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 19.8: </strong>Checkout completion by payment method</div><div class="fobx-body">
<p>An e-commerce company wants to compare checkout completion for different payment methods. In one month of data there were 900 checkout attempts using a credit card, and 847 of them were completed. There were 480 attempts using a digital wallet, and 445 of those were completed. Customers chose their own payment method. Treat the attempts as independent, and assume that the normal approximation is adequate for each completion rate.</p>
<ol type="1">
<li>Compute an approximate 95% confidence interval for the difference in completion rates (digital wallet minus credit card).</li>
<li>A manager wants to use these rates to decide whether to promote digital wallets, or to discourage them. What does the interval tell the manager?</li>
<li>Suppose that the interval had excluded zero. Would that show that the company could raise its completion rate by steering customers toward the payment method with the higher rate?</li>
</ol>
<details class="solution-details" id="solution-checkout-payment-method" aria-label="Solution">
<summary>Solution</summary>
<ol type="1">
<li>The completion rates are <span class="math inline">\(847/900\approx0.941\)</span> for credit cards and <span class="math inline">\(445/480\approx0.927\)</span> for digital wallets, and their standard errors are 0.0078 and 0.0119. The difference is <span class="math inline">\(-1.4\)</span> percentage points, and its standard error is <span class="math inline">\(\sqrt{0.0078^2+0.0119^2}\approx0.0142\)</span>. The interval is <span class="math inline">\(-0.014\pm2(0.0142)\approx[-0.042,\ 0.014]\)</span>, or <span class="math inline">\(-4.2\)</span> to <span class="math inline">\(1.4\)</span> percentage points.</li>
<li>Zero is a plausible value for the difference, so we can’t say that either method has the higher completion rate, and this comparison doesn’t give the manager a reason to promote or discourage either one. With both methods more than 92% of attempts are completed.</li>
<li>No.&nbsp;The customers who choose to pay with a digital wallet could be different from the customers who pay by credit card. They might use different devices, place larger or smaller orders, or be in more of a hurry. Any of those could lead to a difference in completion rates that has nothing to do with the payment method itself. The confidence interval accounts for sampling variability in the two rates, but it can’t account for which customers end up in each group. To answer the manager’s question the company could randomly vary which payment method is featured on the checkout page.</li>
</ol>
</details>
</div></div>
</div>
</section>
</section>
<section id="sec-more-sampling-summary" class="level2" data-number="19.4">
<h2 data-number="19.4" class="anchored" data-anchor-id="sec-more-sampling-summary"><span class="header-section-number">19.4</span> Summary</h2>
<p><a href="#tbl-se-summary" class="quarto-xref">Table&nbsp;<span>19.2</span></a> has the four standard errors that we have used so far. In every row we get the approximate 95% confidence interval by taking the estimate plus or minus two standard errors. To get the <span class="math inline">\(t\)</span>-statistic for a hypothesized value we subtract that value from the estimate, and divide by the standard error.</p>
<div id="tbl-se-summary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-se-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;19.2: Estimates and standard errors for the four parameters we have covered so far.
</figcaption>
<div aria-describedby="tbl-se-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Estimate</th>
<th>Estimated standard error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean <span class="math inline">\(\mu\)</span></td>
<td><span class="math inline">\(\bar x\)</span></td>
<td><span class="math inline">\(SE(\bar x)=s/\sqrt n\)</span></td>
</tr>
<tr class="even">
<td>Proportion <span class="math inline">\(p\)</span></td>
<td><span class="math inline">\(\hat p\)</span></td>
<td><span class="math inline">\(SE(\hat p)=\sqrt{\hat p(1-\hat p)/n}\)</span></td>
</tr>
<tr class="odd">
<td>Difference in means <span class="math inline">\(\mu_A-\mu_B\)</span></td>
<td><span class="math inline">\(\bar x_A-\bar x_B\)</span></td>
<td><span class="math inline">\(\begin{gathered}\sqrt{SE(\bar x_A)^2+SE(\bar x_B)^2}\\=\sqrt{s_A^2/n_A+s_B^2/n_B}\end{gathered}\)</span></td>
</tr>
<tr class="even">
<td>Difference in proportions <span class="math inline">\(p_A-p_B\)</span></td>
<td><span class="math inline">\(\hat p_A-\hat p_B\)</span></td>
<td><span class="math inline">\(\begin{gathered}\sqrt{SE(\hat p_A)^2+SE(\hat p_B)^2}\\=\sqrt{\hat p_A(1-\hat p_A)/n_A+\hat p_B(1-\hat p_B)/n_B}\end{gathered}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The last two rows are built from the first two. The two samples are independent, so the <a href="./prob_09_combining-random-variables.html#sec-lincom-rules">rule for the variance of a difference</a> says the variance of <span class="math inline">\(\bar X_A-\bar X_B\)</span> is the variance of <span class="math inline">\(\bar X_A\)</span> plus the variance of <span class="math inline">\(\bar X_B\)</span>. A squared standard error is just a variance. So we find the standard error for each group separately, square them, add them up, and take the square root. Writing that out gives the second line in each row, since <span class="math inline">\(s_A^2/n_A\)</span> is <span class="math inline">\(SE(\bar x_A)^2\)</span>.</p>
<ol type="1">
<li>We build the interval and the test the same way in every row of the table. If you make a mistake it will probably be in choosing the standard error, so that’s the step to check.</li>
<li>Both of the standard errors for differences assume that we have independent samples. If the data are paired, compute the difference within each pair first, and then use the one-sample formula on the differences.</li>
<li>A test tells us about one hypothesized value, while the interval shows us all of the values that are plausible given the data. If the decision depends on a threshold or a break-even value we need the interval. We have seen that a difference can be statistically significant and still be too small to act on, and we have seen that when we fail to detect a difference it could still be large.</li>
<li>All of these intervals only measure sampling variability. They don’t tell us whether the two groups are comparable in other ways, which depends on how the groups were formed. With random assignment we can interpret a difference between the groups as the effect of the treatment. When people choose their own groups we can’t.</li>
</ol>
</section>
<section id="sec-more-sampling-practice" class="level2" data-number="19.5">
<h2 data-number="19.5" class="anchored" data-anchor-id="sec-more-sampling-practice"><span class="header-section-number">19.5</span> Additional practice</h2>
<div id="exercise-choose-se" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 19.9: </strong>Choose the parameter and standard error</div><div class="fobx-body">
<p>For each of the settings below, name the population parameter, say what the unit of observation is, and give the estimated standard error. What independence assumption does the standard error need?</p>
<ol type="1">
<li>We estimate mean resolution time from 100 randomly selected tickets.</li>
<li>We estimate the proportion of customers who renew from 400 randomly selected customers.</li>
<li>We compare mean resolution time using two independent samples of tickets, handled by two different teams.</li>
<li>We compare the proportion of visitors who make a purchase, where visitors were randomly assigned to one of two webpage designs.</li>
<li>A lab measures the same 36 tablets with a handheld assay and with the standard lab assay, and we estimate the mean difference between them. We have the standard deviation of the 36 differences.</li>
</ol>
<details class="solution-details" id="solution-choose-se" aria-label="Solution">
<summary>Solution</summary>
<ol type="1">
<li>The parameter is a population mean <span class="math inline">\(\mu\)</span>, and the unit is a ticket. The standard error is <span class="math inline">\(s/\sqrt n\)</span>. It assumes that the tickets are independent.</li>
<li>The parameter is a proportion <span class="math inline">\(p\)</span>, and the unit is a customer. The standard error is <span class="math inline">\(\sqrt{\hat p(1-\hat p)/n}\)</span>. It assumes that the customers are independent.</li>
<li>The parameter is a difference in means <span class="math inline">\(\mu_A-\mu_B\)</span>, and the unit is a ticket. The standard error is <span class="math inline">\(\sqrt{SE(\bar x_A)^2+SE(\bar x_B)^2}\)</span> <span class="math inline">\(=\sqrt{s_A^2/n_A+s_B^2/n_B}\)</span>. It assumes that the tickets within each team are independent, and that the two teams’ samples are independent of each other.</li>
<li>The parameter is a difference in proportions <span class="math inline">\(p_A-p_B\)</span>, and the unit is a visitor. The standard error is <span class="math inline">\(\sqrt{SE(\hat p_A)^2+SE(\hat p_B)^2}\)</span> <span class="math inline">\(=\sqrt{\hat p_A(1-\hat p_A)/n_A+\hat p_B(1-\hat p_B)/n_B}\)</span>. It assumes that the visitors are independent and that the two groups are independent. We get independent groups here because separate visitors were randomly assigned to the two designs.</li>
<li>The parameter is the mean difference within a tablet, and the unit is a tablet. We compute the difference for each tablet first, and then the standard error is <span class="math inline">\(s_d/\sqrt{36}\)</span>, which assumes that the tablets are independent. The two readings on the same tablet are paired, so we can’t use the formula for independent samples.</li>
</ol>
</details>
</div></div>
</div>
<div id="exercise-shed-renters" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 19.10: </strong>How many adults rent?</div><div class="fobx-body">
<p>We used the Federal Reserve’s 2025 Survey of Household Economics and Decisionmaking (SHED) in <a href="./singlevar_05_categorical.html#sec-ordinal-rating">the chapter on categorical variables</a>, where we plotted its ratings of economic conditions. The survey also asks each respondent about their housing. There are 12,934 respondents in our extract, and 3,426 of them said that they pay rent. The rest either own their home (with or without a mortgage), or they neither own nor pay rent. Let <span class="math inline">\(p\)</span> be the proportion of all U.S. adults who pay rent. For this exercise you should treat the respondents as a random sample of U.S. adults.</p>
<p>A renters-insurance company estimates the size of its market using a planning model. The model assumes that one in four adults pays rent, so <span class="math inline">\(p_0=0.25\)</span>.</p>
<ol type="1">
<li>Compute <span class="math inline">\(\hat p\)</span>, its estimated standard error, and a two-SE interval for <span class="math inline">\(p\)</span>. In one sentence, what does the interval tell you about the share of adults who rent?</li>
<li>Is the planning model’s 25% a plausible value for <span class="math inline">\(p\)</span>? Check your answer with a t-statistic. Use the <a href="./prob_04_normal.html#sec-empirical-rule">68/95/99.7 rule</a> to put a bound on the two-sided p-value, and state your conclusion at <span class="math inline">\(\alpha=0.05\)</span>.</li>
<li>What sources of error does this interval leave out? Explain why a narrow interval doesn’t tell us, by itself, that our estimate is close to the proportion among all U.S. adults.</li>
</ol>
<details class="solution-details" id="solution-shed-renters" aria-label="Solution">
<summary>Solution</summary>
<ol type="1">
<li>The sample proportion is <span class="math inline">\(\hat p=3,426/12,934\approx0.265\)</span> and its estimated standard error is <span class="math inline">\(\sqrt{0.265(0.735)/12,934}\approx0.0039\)</span>, or about 0.388 percentage points. The two-SE interval is <span class="math inline">\(0.265\pm2(0.0039)\)</span>, which is about <span class="math inline">\([25.7\%,\ 27.3\%]\)</span>. If we accept the sampling assumption, the plausible values for the share of U.S. adults who pay rent are a little more than one in four, and the margin of error is 0.8 points.</li>
<li>The whole interval is above 25%, so the planning value isn’t plausible (under the sampling assumption). We can test <span class="math inline">\(H_0:p=0.25\)</span> against <span class="math inline">\(H_A:p\ne0.25\)</span>, working in percentage points: <span class="math display">\[
t=\frac{26.49-25}{0.388}\approx3.84.
\]</span> The sample proportion is almost four standard errors above the planning value. About 99.7% of a standard normal distribution is within three standard deviations of zero, so the two-sided p-value has to be less than 0.003. That’s much smaller than 0.05 and we reject the null hypothesis, which agrees with what we saw from the two-SE interval.</li>
<li>The interval measures how much our estimate would vary from one random sample to the next, if the sampling model is right. It doesn’t account for differences between the people who answer the survey and the people who don’t. We can have a very narrow interval even when these respondents are systematically different from U.S. adults as a whole.</li>
</ol>
</details>
</div></div>
</div>
<div id="exercise-zero-errors" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 19.11: </strong>Zero observed errors</div><div class="fobx-body">
<p>A pilot audit of 40 randomly selected insurance claims finds no errors. An analyst plugs <span class="math inline">\(\hat p=0\)</span> into <span class="math inline">\(\sqrt{\hat p(1-\hat p)/40}\)</span>, gets a standard error of zero, and reports a confidence interval of <span class="math inline">\([0,\ 0]\)</span>. Has the pilot shown that the error rate in the population is zero? Which condition for the interval fails here? (You don’t need to construct a better interval.)</p>
<details class="solution-details" id="solution-zero-errors" aria-label="Solution">
<summary>Solution</summary>
<p>No.&nbsp;If the population error rate is small but positive we could easily get a sample of 40 claims with no errors. For example, if the error rate is 2% then about 45% of samples of 40 claims would have no errors at all, since <span class="math inline">\(0.98^{40}\approx0.45\)</span>. The normal approximation needs enough of both outcomes in the sample, and we have none of one of them. The standard error is zero because the approximation has failed. It doesn’t mean that we are certain about the error rate.</p>
</details>
</div></div>
</div>
<div id="exercise-audit-cost-precision" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 19.12: </strong>Precision and audit cost</div><div class="fobx-body">
<p>An insurer has several million claims, and wants an approximate 95% confidence interval for the proportion of claims with billing errors. It costs $10 to audit each claim. Use the worst-case planning margin <span class="math inline">\(1/\sqrt n\)</span>.</p>
<ol type="1">
<li>Find the sample size and the cost of the audit for a margin of 4 percentage points. Do the same for a margin of 2 percentage points.</li>
<li>When we cut the margin in half the cost more than doubles. Why?</li>
<li>The audit team proposes sampling only from claims with records that are easy to retrieve. Does your calculation in part 1 account for that?</li>
</ol>
<details class="solution-details" id="solution-audit-cost-precision" aria-label="Solution">
<summary>Solution</summary>
<ol type="1">
<li>If we solve <span class="math inline">\(1/\sqrt n=0.04\)</span> we get <span class="math inline">\(n=625\)</span> claims, which would cost $6,250. If we solve <span class="math inline">\(1/\sqrt n=0.02\)</span> we get <span class="math inline">\(n=2{,}500\)</span> claims, which would cost $25,000.</li>
<li>The margin shrinks with <span class="math inline">\(\sqrt n\)</span>, so to cut it in half we need four times as many claims. The cost is proportional to the number of claims, so it is four times as large too.</li>
<li>No.&nbsp;The margin describes the sampling variability for a random sample from all of the claims. The claims that are easy to retrieve could have a systematically different error rate, and auditing more of them won’t fix that.</li>
</ol>
</details>
</div></div>
</div>
<div id="exercise-two-stores-two-intervals" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 19.13: </strong>Two stores, two intervals</div><div class="fobx-body">
<p>A retailer audits the average transaction size at two of its stores. A random sample of 64 transactions at Store A has a mean of $52 and a standard deviation of $16. A random sample of 100 transactions at Store B has a mean of $58 and a standard deviation of $20. Assume that the normal approximation is adequate for each sample mean.</p>
<ol type="1">
<li>Compute the two-SE interval for the mean transaction size at each store.</li>
<li>The two intervals overlap. The regional manager concludes that “the stores could easily have the same average, so there is no evidence of a difference.” Before you compute anything else, do overlapping intervals justify the manager’s conclusion?</li>
<li>Treat the samples as independent. Compute the standard error of the difference in means (B minus A), and a two-SE interval for the difference in the population.</li>
<li>Reconcile your answers to parts 1 and 3 in one or two sentences.</li>
</ol>
<details class="solution-details" id="solution-two-stores-two-intervals" aria-label="Solution">
<summary>Solution</summary>
<ol type="1">
<li>For Store A the standard error is <span class="math inline">\(16/\sqrt{64}=2\)</span> and the interval is <span class="math inline">\([48,\ 56]\)</span>. For Store B the standard error is <span class="math inline">\(20/\sqrt{100}=2\)</span> and the interval is <span class="math inline">\([54,\ 62]\)</span>.</li>
<li>No.&nbsp;Each interval gives us the plausible values for one of the means, without reference to the other. Whether the two means could be equal is a question about the difference between them, and the difference has its own standard error and its own interval.</li>
<li>The standard error is <span class="math inline">\(\sqrt{2^2+2^2}\approx2.83\)</span>. The interval is <span class="math inline">\(6\pm2(2.83)\)</span>, or about <span class="math inline">\([0.3,\ 11.7]\)</span> dollars.</li>
<li>The two separate intervals will overlap unless the gap between the means is more than the sum of their margins of error, which is <span class="math inline">\(4+4=8\)</span> dollars. The interval for the difference will exclude zero when the gap is more than two standard errors of the difference, which is only <span class="math inline">\(2\sqrt{2^2+2^2}\approx5.7\)</span> dollars. It’s smaller because we add up the squares of the standard errors, and not the standard errors themselves. The gap we observed is $6, which is more than 5.7 and less than 8.</li>
</ol>
</details>
</div></div>
</div>
<div id="exercise-sales-tool-break-even" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 19.14: </strong>A sales tool with a break-even</div><div class="fobx-body">
<p>An auto-parts distributor is thinking about buying a subscription to a sales-planning tool for its outside sales representatives. Between the license and the selling time that reps would lose to training, the tool costs $4,000 per rep per quarter. That means it only pays for itself if it raises the mean quarterly gross margin per rep by more than $4,000. The distributor ran a pilot for one quarter with 135 reps, and randomly assigned 60 of them to use the tool (group A). The other 75 reps worked as usual (group B).</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group</th>
<th style="text-align: right;">Reps</th>
<th style="text-align: right;">Mean gross margin</th>
<th style="text-align: right;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A, with the tool</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">$96,800</td>
<td style="text-align: right;">$19,500</td>
</tr>
<tr class="even">
<td>B, without the tool</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">$88,400</td>
<td style="text-align: right;">$18,000</td>
</tr>
</tbody>
</table>
<p>Treat the two groups as independent samples, and assume that the normal approximation is adequate for the mean of each group.</p>
<ol type="1">
<li>Let <span class="math inline">\(\mu_A-\mu_B\)</span> be the effect of the tool on mean quarterly gross margin per rep. Compute the estimate <span class="math inline">\(\bar x_A-\bar x_B\)</span>, its standard error, and the two-SE interval for <span class="math inline">\(\mu_A-\mu_B\)</span>.</li>
<li>The vendor’s summary of the pilot says that “The tool produced a statistically significant lift in gross margin.” Use your interval to evaluate that statement at the 5% level. How does random assignment help us interpret the difference as the effect of the tool?</li>
<li>Has the pilot shown that the tool pays for itself? Compare the interval to the $4,000 break-even value. What can the distributor conclude?</li>
</ol>
<details class="solution-details" id="solution-sales-tool-break-even" aria-label="Solution">
<summary>Solution</summary>
<ol type="1">
<li>We will work in thousands of dollars. The estimate is <span class="math inline">\(96.8-88.4=8.4\)</span>. The two groups were measured separately, so we add the variances of the two sample means: <span class="math display">\[
SE(\bar X_A-\bar X_B)=\sqrt{\frac{19.5^2}{60}+\frac{18.0^2}{75}}\approx3.26.
\]</span> The interval is <span class="math inline">\(8.4\pm2(3.26)\approx[1.9,\ 14.9]\)</span>, or about $1,900 to $14,900 per rep per quarter.</li>
<li>Zero is below the lower endpoint of the interval, so we would reject the null hypothesis of no effect in a two-sided test at about the 5% level. The vendor’s statement is accurate. Since the distributor assigned the tool at random, the only differences between the two groups (other than the tool) are due to chance, and it’s credible that the lift is the effect of the tool for these reps. We don’t have to worry that we are just seeing a difference between the kinds of reps who would volunteer to use the tool and those who wouldn’t. Random assignment doesn’t make these 135 reps representative of sales reps at other firms, though.</li>
<li>No.&nbsp;The break-even value of $4,000 is inside the interval, so the pilot is consistent with effects that are below the break-even value and with effects that are above it. Our estimate of $8,400 is above break-even but only by <span class="math inline">\((8.4-4.0)/3.26\approx1.35\)</span> standard errors, and that isn’t enough to rule out a tool that loses money. So the pilot hasn’t shown that the tool pays for itself. The vendor’s statement tells us that the effect isn’t zero, but the distributor’s decision depends on whether the effect is larger than $4,000.</li>
</ol>
</details>
</div></div>
</div>
<div id="exercise-hmda-denials" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 19.15: </strong>Mortgage denial rates</div><div class="fobx-body">
<p>The <code>HMDA</code> data in the <code>AER</code> package are from a study by the Federal Reserve Bank of Boston, which looked at 2,380 mortgage applications in the Boston area in 1990. Each application was either approved or denied, and the data record whether the applicant was Black. The counts are in <a href="#tbl-practice-hmda" class="quarto-xref">Table&nbsp;<span>19.3</span></a>. Treat the applications as a random sample of the mortgage applications in the area that year.</p>
<div class="cell">
<div id="tbl-practice-hmda" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-practice-hmda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;19.3: Mortgage applications and denials in the Boston HMDA data, 1990.
</figcaption>
<div aria-describedby="tbl-practice-hmda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">Applications</th>
<th style="text-align: right;">Denied</th>
<th style="text-align: right;">Denial rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Black applicants</td>
<td style="text-align: right;">339</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">28.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other applicants</td>
<td style="text-align: right;">2,041</td>
<td style="text-align: right;">189</td>
<td style="text-align: right;">9.3%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<ol type="1">
<li>Compute the estimated standard error and a two-SE interval for the denial rate among all applications in the area. Then do the same for Black applicants and for other applicants separately.</li>
<li>The interval for Black applicants is about four times as wide as the interval for other applicants. There are two reasons. What are they?</li>
<li>The difference between the two sample denial rates is 19.1 percentage points. Treat the two groups as independent samples, and compute the standard error of the difference and a two-SE interval for the difference in denial rates.</li>
<li>What does the interval in part 3 tell us, and what doesn’t it tell us? Be careful. What questions would the researchers at the Boston Fed have needed to answer before they could interpret the gap?</li>
</ol>
<details class="solution-details" id="solution-hmda-denials" aria-label="Solution">
<summary>Solution</summary>
<ol type="1">
<li>For all applications, <span class="math inline">\(\hat p=0.120\)</span> and the standard error is <span class="math inline">\(\sqrt{0.120(0.880)/2,380}\approx0.0067\)</span>, so the interval is about <span class="math inline">\([10.6\%,\ 13.3\%]\)</span>. For Black applicants, <span class="math inline">\(\hat p=0.283\)</span> with a standard error of 0.024, and the interval is <span class="math inline">\([23.4\%,\ 33.2\%]\)</span>. For other applicants, <span class="math inline">\(\hat p=0.093\)</span> with a standard error of 0.006, and the interval is <span class="math inline">\([8.0\%,\ 10.5\%]\)</span>.</li>
<li>First, the sample of Black applicants is only about one sixth as large. That alone would make the standard error larger by a factor of about <span class="math inline">\(\sqrt6\approx2.4\)</span>. Second, the denial rate for Black applicants is closer to one half, and <span class="math inline">\(p(1-p)\)</span> is largest at one half. That accounts for the rest.</li>
<li>From the standard error for a difference in proportions we get <span class="math inline">\(\sqrt{0.024^2+0.006^2}\approx0.025\)</span>, and the interval is about <span class="math inline">\([14.0,\ 24.1]\)</span> percentage points.</li>
<li>Zero is far outside the interval, so (under our sampling model) it isn’t plausible that the difference we observed is only due to random sampling variation. The interval doesn’t tell us why there is a gap. The applicants were different in their incomes, their debt ratios, their credit histories, and the properties they were trying to buy, and the raw denial rates don’t adjust for any of those differences. The main question in the Boston Fed study was whether there is still a gap after we account for the applicants’ characteristics. We can’t answer that by comparing two raw rates.</li>
</ol>
</details>
</div></div>
</div>
</section>
<section id="data-used-in-this-section" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="data-used-in-this-section">Data used in this section</h2>
<ul>
<li><a href="./appendix_data.html#sec-data-wfh-bloom">Bloom, Han &amp; Liang Hybrid WFH Experiment</a> supplies the attrition counts used in the introduction <span class="citation" data-cites="wfh-bloom">(<a href="appendix_data.html#ref-wfh-bloom" role="doc-biblioref">Bloom et al. 2024</a>)</span>.</li>
<li><a href="./appendix_data.html#sec-data-shed">Survey of Household Economics and Decisionmaking</a> supplies the housing-status data used in the additional practice.</li>
<li><code>HMDA</code> from the <code>AER</code> package supplies the Boston mortgage applications <span class="citation" data-cites="munnell-hmda-1996 aer-package">(<a href="appendix_data.html#ref-munnell-hmda-1996" role="doc-biblioref">Munnell et al. 1996</a>; <a href="appendix_data.html#ref-aer-package" role="doc-biblioref">Kleiber and Zeileis 2008</a>)</span>.</li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-wfh-bloom" class="csl-entry" role="listitem">
Bloom, Nicholas, Ruobing Han, and James Liang. 2024. <span>“Hybrid Working from Home Improves Retention Without Damaging Performance.”</span> <em>Nature</em> 630 (8018): 920–25. <a href="https://doi.org/10.1038/s41586-024-07500-2">https://doi.org/10.1038/s41586-024-07500-2</a>.
</div>
<div id="ref-aer-package" class="csl-entry" role="listitem">
Kleiber, Christian, and Achim Zeileis. 2008. <em>Applied Econometrics with <span>R</span></em>. Springer-Verlag. <a href="https://doi.org/10.1007/978-0-387-77318-6">https://doi.org/10.1007/978-0-387-77318-6</a>.
</div>
<div id="ref-munnell-hmda-1996" class="csl-entry" role="listitem">
Munnell, Alicia H., Geoffrey M. B. Tootell, Lynn E. Browne, and James McEneaney. 1996. <span>“Mortgage Lending in Boston: Interpreting <span>HMDA</span> Data.”</span> <em>American Economic Review</em> 86 (1): 25–53.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./inference_03_limits.html" class="pagination-link" aria-label="The Limits of Statistical Inference">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">The Limits of Statistical Inference</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./case_triangle-test.html" class="pagination-link" aria-label="Case Study: Can Customers Taste the Difference?">
        <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Case Study: Can Customers Taste the Difference?</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>