<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Introduction to Probability and Sampling – TEMBA Statistics — Course Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./prob_02_probability-basics.html" rel="next">
<link href="./singlevar_05_categorical.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d3f7f8e73c8d287b30bcf59c2b563615.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/foldbox/foldbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>
.Definition {
  --color1: #F4EAF0;
  --color2: #7C3F58;
}
.Exercise {
  --color1: #E7F4F5;
  --color2: #147D85;
}
.Notation {
  --color1: #EEF1F3;
  --color2: #5B6770;
}
.TechnicalDetail {
  --color1: #EEF1F3;
  --color2: #5B6770;
}
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles/callouts.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./prob_01_intro.html">Probability</a></li><li class="breadcrumb-item"><a href="./prob_01_intro.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introduction to Probability and Sampling</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">TEMBA Statistics — Course Notes</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Visualizing and summarizing a single variable</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_01_visualizing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Visualizing a Single Quantitative Variable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_02_describing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Distributions of Quantitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_03_location-and-spread.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Measuring Location and Spread</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_04_transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Transforming Quantitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_05_categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Categorical Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Probability</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_01_intro.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introduction to Probability and Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_02_probability-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Probability Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_03_distribution-parameters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Measures of Location and Spread (and Other Parameters of Probability Distributions)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_04_normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">The Normal Distribution</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-what-is-probability" id="toc-sec-what-is-probability" class="nav-link active" data-scroll-target="#sec-what-is-probability"><span class="header-section-number">6.1</span> What is probability?</a>
  <ul class="collapse">
  <li><a href="#probability-distributions" id="toc-probability-distributions" class="nav-link" data-scroll-target="#probability-distributions"><span class="header-section-number">6.1.1</span> Probability distributions</a></li>
  <li><a href="#what-is-a-probability-model" id="toc-what-is-a-probability-model" class="nav-link" data-scroll-target="#what-is-a-probability-model"><span class="header-section-number">6.1.2</span> What is a probability model?</a></li>
  </ul></li>
  <li><a href="#what-is-sampling-and-what-is-a-sample" id="toc-what-is-sampling-and-what-is-a-sample" class="nav-link" data-scroll-target="#what-is-sampling-and-what-is-a-sample"><span class="header-section-number">6.2</span> What is sampling, and what is a sample?</a></li>
  <li><a href="#data-used-in-this-section" id="toc-data-used-in-this-section" class="nav-link" data-scroll-target="#data-used-in-this-section">Data used in this section</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./prob_01_intro.html">Probability</a></li><li class="breadcrumb-item"><a href="./prob_01_intro.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introduction to Probability and Sampling</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introduction to Probability and Sampling</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Probability</strong> is the mathematical language of uncertainty. It lets us reason coherently about the relative chances of different outcomes and make good decisions with incomplete information. When a survey asks a few hundred or a few thousand Americans how they rate the economy, how accurately can we expect the results to reflect the opinions of the 260+ million adults in the country? When a manufacturing plant produces thousands of widgets daily, how can managers predict tomorrow’s defect rate? What’s the chance the Federal Reserve will keep rates steady at their next meeting? We can make these questions precise — and answer some of them — using probability.</p>
<p>Up until now, we’ve been summarizing and analyzing data we already have. But in essentially every example we’ve seen, we really want to know about data we <em>don’t</em> have: the economic-conditions ratings of all U.S. adults, the sale price of a new house, the Fed’s target range after the next FOMC meeting. One way to think about probability is as describing data you don’t have access to, either because it doesn’t exist yet (the target range after the next FOMC meeting) or because you can’t realistically observe it (the opinions of all U.S. adults). In either case, we can use probability to reason about what we <em>expect</em> to see in the future, how likely different outcomes are, and what decisions we should make in the face of that uncertainty.</p>
<p>Let’s look at an example. Suppose you’re considering funding one of two LendingClub loans at the end of 2012 (where our data stop). Both loans are for the same amount. The first is a small-business loan and the second is a debt-consolidation loan. The two applications are otherwise identical (in terms, borrower credit history, etc.) and if paid in full you will get the same return on your investment. Which will you pick? Splitting the historical LendingClub loans by purpose gives us the default rate for each of these two kinds:</p>
<div class="cell">
<div id="tbl-two-loan-defaults" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-two-loan-defaults-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.1: Historical default rates for small-business and debt-consolidation loans in the LendingClub data.
</figcaption>
<div aria-describedby="tbl-two-loan-defaults-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Purpose</th>
<th style="text-align: right;">Loans</th>
<th style="text-align: right;">Default rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">small_business</td>
<td style="text-align: right;">3,191</td>
<td style="text-align: right;">25.8%</td>
</tr>
<tr class="even">
<td style="text-align: left;">debt_consolidation</td>
<td style="text-align: right;">49,409</td>
<td style="text-align: right;">16.5%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Which loan would you fund, and what’s the chance it would default?</p>
<p>Without any additional information you’d probably pick the debt-consolidation loan and say there’s a 16.5% chance of default. You did a number of things all at once: you made the (at least partially) subjective decision that the historical data were <em>representative</em> of future outcomes, you constructed a rule for assigning probabilities to uncertain outcomes (a <strong>probability model</strong>), estimated its <strong>parameters</strong> (the two default probabilities), and used that model to make a decision. In the next few chapters we’re going to make this process a little more formal and introduce some more sophisticated models.</p>
<section id="sec-what-is-probability" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="sec-what-is-probability"><span class="header-section-number">6.1</span> What is probability?</h2>
<p>We’ve made reference to probability several times above (and occasionally in earlier sections), but we haven’t defined it yet. When we say there’s an 80% chance that the Texas Longhorns football team will win their game against Oklahoma, we’re making a probability statement: Numerically quantifying the chance that an uncertain event will take place. There are different ways we can think about that number. We could say that if we could play the game over and over and over, about 80% of the time (or four times out of five) Texas would win. Or we could say something like: Based on what I know about the game and the two teams, I think it’s four times more likely that Texas will win than it is they will lose (or tie).</p>
<p>Both are valid interpretations of the same probability statement, but they come from different perspectives. The first is a <strong>long-run frequency</strong> interpretation: If we could repeat the game many times, the Longhorns would win about 80% of the time. A more natural long-run frequency that doesn’t invoke an abstract thought experiment would be something like: among all historical games where the two teams were similar to the Texas and Oklahoma teams this year, the Texas-like team won about 80% of the time, so there’s an 80% chance this Texas team will win the game this year.</p>
<p>The second is a <strong>subjective</strong> interpretation: It represents my personal belief about the outcome of a single game. I might have arrived at that belief by looking at historical data, but it is still a personal assessment of the chance of a single event. A subjective probability statement is often expressed in terms of betting odds: I would take a bet on Texas that returns my $4 stake plus at least $1 in profit if Texas wins, and I would not take a bet that paid less than that. That 80% chance is just another way of expressing the same idea: I think it’s four times more likely that Texas will win than it is they will lose (or tie).</p>
<p>The Federal Reserve sets a quarter-point-wide target range for its key interest rate. At each scheduled Federal Open Market Committee meeting, it can leave that range unchanged or move it by one or more quarter-point increments. An increase is a hike; a decrease is a cut.</p>
<p>When fair betting markets with more or less rational participants exist, these kinds of subjective assessments, aggregated across many participants, can accurately represent uncertainty about future events. The <a href="https://www.cmegroup.com/markets/interest-rates/cme-fedwatch-tool.html">CME FedWatch</a> tool uses the prices of futures contracts to estimate the probability of different outcomes for successive Federal Reserve meetings. By some natural metrics, <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5093703">it is pretty accurate over short windows in many regimes</a>. The price of futures contracts represents, essentially, a consensus view of how likely each potential rate decision is.</p>
<div id="technical-fedwatch-construction" class="TechnicalDetail">
<details class="TechnicalDetail fobx-simplebox fobx-default"><summary><strong>Technical detail 6.1: </strong>Where the FedWatch probabilities come from</summary><div>
<p>FedWatch backs its probabilities out of market prices, the way you might back a win probability out of betting odds. Suppose a bet pays $100 if the Fed’s target range ends up at 3.75–4.00%, and people are willing to stake about $25 on it. They are treating that outcome as having a probability of about <span class="math inline">\(25/100 = 0.25\)</span>. A small stake for a big payoff means the market considers the outcome unlikely. Traders make exactly this kind of bet on where the federal funds rate will end up, through contracts called fed funds futures, and the prices they pay imply a probability for each target range. Prices move with the news, so any probabilities you read off are a snapshot.</p>
</div></details>
</div>
<p>Here is what those market prices implied on July 9, 2026, when the target range stood at 3.50–3.75% and the next two FOMC meetings were scheduled for July 29 and September 16. <a href="#tbl-cme-intro-margins" class="quarto-xref">Table&nbsp;<span>6.2</span></a> shows the tool’s probabilities for where the target range will sit after each meeting.</p>
<div class="cell">
<div id="tbl-cme-intro-margins" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cme-intro-margins-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.2: Market-implied probabilities for the FOMC target range after the next two meetings, as reported by CME FedWatch on July 9, 2026. The target range at the time was 3.50–3.75%.
</figcaption>
<div aria-describedby="tbl-cme-intro-margins-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Target range</th>
<th style="text-align: right;">July 29</th>
<th style="text-align: right;">September 16</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3.50–3.75%</td>
<td style="text-align: right;">0.759</td>
<td style="text-align: right;">0.366</td>
</tr>
<tr class="even">
<td style="text-align: left;">3.75–4.00%</td>
<td style="text-align: right;">0.241</td>
<td style="text-align: right;">0.509</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4.00–4.25%</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">0.125</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The September branch probabilities do not come from the per-meeting totals in the table alone. CME estimates probabilities for each meeting from monthly Fed Funds futures prices, then combines successive meeting outcomes into cumulative paths. The marginal totals alone cannot tell us how September’s chances depend on July’s outcome.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cme-tree" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cme-tree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob_01_intro_files/figure-html/fig-cme-tree-1.png" class="img-fluid figure-img" width="816">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cme-tree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: The market’s view of the next two FOMC meetings, drawn as a tree. Each left-to-right path is one way the two meetings could play out. The numbers on the first pair of branches are the market’s chances for the July meeting; those on the September branches are its chances given everything to their left. Every July outcome fans out to all three September ranges; the dashed branches are moves to which the FedWatch model assigns zero probability under its assumptions.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The tree in <a href="#fig-cme-tree" class="quarto-xref">Figure&nbsp;<span>6.1</span></a> lays out how September’s chances depend on what happens in July. If the July meeting holds rates steady — the market’s 75.9% case — there is a 51.8% chance of a hike at the September meeting. If July brings a hike instead, there is a 51.9% chance of <em>another</em> hike in September. In both cases the chance of a September move is close to 0.5. The two paths differ in where a move would leave the target range. Under the FedWatch model, no path in this snapshot cuts rates or moves the range by more than one quarter-point at either meeting. We’ll come back to trees like this one once we can connect the numbers on the branches to the totals in the table.</p>
<p>In reality there often isn’t such a bright line between the long-run frequency and subjective interpretations. Subjective assessments are formed in part based on experience and historical outcomes, and long-run frequency statements often hinge on subjective assessments (e.g.&nbsp;how we choose “similar” prior games).</p>
<section id="probability-distributions" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="probability-distributions"><span class="header-section-number">6.1.1</span> Probability distributions</h3>
<p>In the first few sections of these notes we looked at ways to describe and visualize the distributions of observed variables in our dataset — a density curve, a table of proportions. Probability gives us a way to describe the distribution of <em>unobserved</em> variables. A <strong>probability distribution</strong> is a rule (a mathematical function) that assigns probabilities to all possible outcomes of a random or uncertain process. Probabilities are numbers between 0 and 1 that follow rules we spell out in <a href="prob_02_probability-basics.html#sec-prob-rules" class="quarto-xref"><span>Section 7.2</span></a>. Based on our historical data about small-business loans, we might say there is a 25.8% chance (a 0.258 probability) that a <em>new</em> small-business loan will default, and a 74.2% chance that it won’t. That’s a simple probability distribution. A probability distribution is a mathematical abstraction of the observed data distributions we’ve already seen, and it has its own mean, median, and standard deviation. We define those summaries in <a href="prob_03_distribution-parameters.html#sec-rv-mean" class="quarto-xref"><span>Section 8.1</span></a>.</p>
</section>
<section id="what-is-a-probability-model" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="what-is-a-probability-model"><span class="header-section-number">6.1.2</span> What is a probability model?</h3>
<div id="defn-probability-model" class="Definition">
<div class="Definition fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-book fobx-icon" aria-hidden="true"></i><strong>Definition 6.1: </strong>Probability model</div><div class="fobx-body">
<p>A <strong>probability model</strong> is a probability distribution we construct to approximate the outcomes of some real-world process.</p>
</div></div>
</div>
<p>We built one at the start of the chapter without calling it that. <a href="#tbl-two-loan-defaults" class="quarto-xref">Table&nbsp;<span>6.1</span></a> gives the <em>historical</em> default rate for each kind of loan; a probability model instead states the chance that a <em>future</em> loan of that kind defaults. If the historical data are a good representation of future outcomes, we might use the same numbers:</p>
<div class="cell">
<div id="tbl-loan-default-model" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-loan-default-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.3: A probability model for a future loan’s outcome, given its purpose. Each row is a probability distribution over the two outcomes, so each row sums to one.
</figcaption>
<div aria-describedby="tbl-loan-default-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Purpose</th>
<th style="text-align: right;">Pr(default)</th>
<th style="text-align: right;">Pr(repaid)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Small business</td>
<td style="text-align: right;">0.258</td>
<td style="text-align: right;">0.742</td>
</tr>
<tr class="even">
<td style="text-align: left;">Debt consolidation</td>
<td style="text-align: right;">0.165</td>
<td style="text-align: right;">0.835</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Read the small-business row: a new small-business loan defaults with probability 0.258 and is repaid with probability 0.742. That’s the two-outcome distribution from the last section, now written down for both kinds of loan.</p>
<p>For a sufficiently interesting problem a probability model will almost always be wrong in some way. But a good probability model is useful if it captures the key features of the real-world process we’re trying to understand. While you can write down a complete probability model mathematically or algorithmically without ever touching any data, typically the model will at least have some <strong>parameters</strong> that we estimate from data (e.g.&nbsp;by plugging historical default rates into our probability model as we just did). A <strong>parameter</strong> is just a feature of the probability distribution, and many of these are familiar to us from our work in earlier chapters — the mean, the variance, the standard deviation. We defined these in terms of observed data, but each has an analogue for a probability distribution that describes unobserved data.</p>
</section>
</section>
<section id="what-is-sampling-and-what-is-a-sample" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="what-is-sampling-and-what-is-a-sample"><span class="header-section-number">6.2</span> What is sampling, and what is a sample?</h2>
<p>We can think about <strong>sampling</strong> in two different ways: First and most familiar, as taking a sample from some broader overall population. The Federal Reserve’s household survey, the source of the economic-conditions ratings we saw earlier, asks a sample of adults about their finances and the economy. Their answers describe the population at large. Let’s simplify its goal to estimating the proportion of U.S. adults who rate national economic conditions good or excellent. Suppose the surveyors interview a sample of 1,000 adults, and 510 of them rate conditions good or excellent. What have we learned about the overall population? That depends entirely on how the sample is constructed.</p>
<p>Generally speaking, the highest quality surveys use <strong>random</strong> sampling to both ensure that a sample is <em>highly likely</em> to be representative of the population of interest and to help us quantify how different the sample and population ratings are likely to be. If we choose the sample completely at random from the population (e.g.&nbsp;by putting everyone’s name on a lottery ticket and pulling them out of a bag), then it is unlikely that we’ll get a sample with a disproportionate number of good-or-excellent ratings relative to the population of interest. The use of random sampling also tells us how to make uncertainty statements about how far our sample proportion of 0.51 (51%) is likely to be from the true population share who rate conditions good or excellent.</p>
<p>We can also think about <strong>sampling</strong> as generating realizations of a random process (a probability distribution). When we flip a coin ten times and record the outcomes, we’re generating a random sample of size <span class="math inline">\(n=10\)</span> from a probability distribution that assigns some chance to observing heads and some chance to observing tails. If it’s a fair coin each outcome is equally likely. If we didn’t know whether the coin was fair, we could try to answer that question by flipping it many times and recording the outcomes. If we flip a fair coin enough times, the proportion of heads should be close to one-half. Suppose we flip the coin 1,000 times and see 510 heads (a proportion of 0.51, or 51%). We can use the very same probability tools to ask whether this is evidence of an unfair coin, or whether we happened to produce more heads than tails simply by chance. In this case the “population” is the probability distribution of the coin flip, and the “sample” is the 1,000 flips we observed.</p>
<p>To belabor the point, suppose that exactly 50% of adults rate conditions good or excellent. Now imagine randomly sampling a single adult such that <em>any</em> adult is equally likely to be chosen. The chance we’ll get someone who rates conditions good or excellent is 50%. If we sample 1,000 adults from the population, what we’ve done is basically the same thing as flipping a coin 1,000 times and counting the number of heads. Our 1,000 survey responses are, for all intents and purposes, 1,000 coin flips.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Now if we didn’t know the exact population share who rate conditions good or excellent, or whether the coin was fair, we could use that observed data to estimate the population proportion or the true probability our coin will come up heads on a single flip in exactly the same way.</p>
<p>For now, two things:</p>
<ol type="1">
<li>We can use a sample from a larger population to learn about the population, and we can use a sample drawn from a probability distribution — i.e., the observed outcomes of a random or unpredictable process like the one that determines the sale price of a house — to learn about that distribution.</li>
<li>In either case the sample must <em>represent</em> the population or distribution we’re trying to learn about:
<ol type="a">
<li>If we’re using a sample to learn about a population, the sample cannot have systematic biases. We don’t measure how the country rates economic conditions by standing outside Nordstrom’s and asking people what they think about the economy, because we’ll have systematically more affluent shoppers in our sample than in the population.</li>
<li>If our sample is historical data used to build a probability model, two things must hold. First, the model must be able to describe the historical data: some choice of its parameters should reproduce the important patterns we observed. Second, the historical data must represent the future outcomes we want the model to describe. If important conditions change over time — say new tariffs alter small-business default rates — then the historical data may no longer support useful probabilities for future loans, unless we can also model the effects of these changes.</li>
</ol></li>
</ol>
<!--- PARKED pre-reorder draft (2026-08-17): adjacency language is stale under
the current chapter order, and the survey framing still uses the retired
expectations construct ("expect the economy to improve") — if unparked, apply
the SHED current-conditions swap and reorder fixes first.

Many statistics textbooks frame statistical inference as attempting to learn about population quantities from a random sample, even when there's no real population and we have all the data we could want. The LendingClub data contain every relevant loan issued over a five-year period, and the Zillow data contain every house sale in Austin over a two-year period. Others frame statistical inference as using data to learn about a probability distribution even when there is a fixed, well-defined population (all U.S. adults) among whom we could calculate our quantity of interest (the proportion of adults who expect the economy to improve) exactly.

or in terms of repeated draws from a true probability distribution. The "using a sample to learn about a population" framework is much easier to understand, but outside designed surveys rarely exists in the wild.  Our datasets contain every Lending Club loan issued over 2008-2012, and we have every house sale on Zillow in Austin for a couple of years. The latter, on the other hand, is much more abstract and never actually exists in the real world.



### Probability distributions

We will define a **probability distribution** more formally in the next chapter, but for now we can think of it as a rule (a mathematical function) that assigns probabilities (numbers between 0 and 1 that follow specific rules) to all possible outcomes of a random (or uncertain) process. Based on our historical data about small business loans, we might say there is a XXX% chance (a XXX probability) that a new small business loan will default, and a 16.5% chance that it won't. That's a simple probability distribution.

A probability distribution is just a mathematical abstraction of the visualizations and summaries we've been computing on actual data in the last chapter. A frequency table of historical loan outcomes by purpose tells us what proportion of historical loans default:

TODO: MAKE THAT TABLE

A probability distribution for *future* loans would have exactly the same row and column structure, and would also contain positive numbers that all sum to one, but the numbers would be probabilities rather than observed frequencies. The numerical values wouldn't be the same, however (unless, as we did earlier, we use the historical outcomes to **estimate** the probability of each future outcome -- then the two tables would look identical but be interpreted differently).

Similarly, for a quantitative variable like house prices we can specify a probability distribution by writing down a formula for a **density curve** like the density curve we created in chapter XXX:

(TODO: KDE for small austin houses dataset)

Recall that the area under the density curve for any price range gives us approximately the proportion of historical prices that fell in that range. 

(TODO: make this viz, using a modest-width interval where data are dense -- say 30-40th percentiles)

A probability distribution for *future* house prices can be specified by writing a mathematical formula that produces a density curve with the same key properties (non-negative with total area equal to one). The area under the curve for any price range gives us the probability that a future house will sell in that range, or the proportion of future houses that will sell in that range. 

(TODO: make similar viz for illustration. Oversmooth the KDE so it looks different and highlight the same area)

One way to write down that formula would be to copy and paste the formula defining the density curve we estimated from the historical data. That would be reasonable if historical data are representative of future outcomes, but unreliable in small samples or when we are interested in extreme outcomes. Another way to write down that formula would be to choose a family of density curves that we think is appropriate for the process we're modeling, and then estimate the **parameters** of that family from the historical data. We'll see many examples of this later on. In either case, what we're doing is specifying a **probability model** for future home sales.




## Representativeness and random sampling

We've emphasized the importance of having **representative** data in order to make high-quality probability statements (and decisions under uncertainty). There isn't a formal definition of representativeness, at least not one that will be useful for us, but the idea is quite intuitive: The data we have should be "similar enough" to the data we wish we had. About (TODO X) percent of small business loans in the recent past defaulted. If these loans are representative of future loans, we should expect about (TODO X) percent of small business loans to fail in the future. If we fail to account for important changes over time -- say the imposition of punishing tariffs on inputs from China -- then our historical data will not be representative of future outcomes, and our probability statements will be misleading.

The more common way to talk about representativeness is in the context of learning about an entire **population** -- say all U.S. adults -- from a **sample** of that population. A "sample" in this context is simply a subset of the population. It turns out that we can very accurately infer aggregate characteristics of a population from a relatively small sample, provided that the sample is representative. If we're trying to learn about the distribution of incomes in the U.S., it would be a bad idea to collect our sample by standing outside Nordstrom's and asking customers to report their income. 

The classical way to do this is to take that sample *randomly* from the overall population, in such a way that we can compute the probability of seeing any particular random sample. Imagine writing every adult's name on a ball and putting all the balls in a bingo machine. If you draw 1,000 balls at random, the resulting sample will usually be representative of the population of all U.S. adults. There is still a very small chance that we would sample 1,000 people who are all fantastically rich (or poor), but we can control and quantify that using probability theory. In the United States our federal statistical agencies do (more or less) exactly this: They start with a master list of all residential addresses, and randomly select a number of them to survey (TODO: Footnote about how the actual sampling process is more complicated, but still gives known probabilities of selection). The resulting sample is very likely to be representative of the population, and we can use probability theory to quantify how wrong we could be due to a "bad luck" sample.

## Connecting population and probability model perspectives

Most statistics textbooks will frame statistical uncertainty about population quantities or model parameters in terms of a population and a sample, or in terms of repeated draws from a true probability distribution. The "using a sample to learn about a population" framework is much easier to understand, but outside designed surveys rarely exists in the wild.  Our datasets contain every Lending Club loan issued over 2008-2012, and we have every house sale on Zillow in Austin for a couple of years. The "repeated draws from a probability distribution" framing, on the other hand, is more abstract and itself usually an approximation to a more complicated reality. But they are really two sides of the same coin.

Let's think about our house prices again. We've got data on all home sales over some historical period, and there's no obvious sense in which there's some overall population from which they are sampled. The probability modeling perspective is (roughly) that an accumulation of predictable and random or unpredictable events produced the observed distribution of home sales in our data. If we assume these are more or less constant over short time periods -- or if we can model how they are changing -- then we can use that historical data to estimate a probability model that describes uncertainty in *future* home sales. To put this into the sampling framework, we could consider the historical and future sale prices to be the "population", and the historical data to be a representative "sample" from that population. We can treat the historical data as (effectively) a random sample from the population of future and past home sales, perhaps after accounting for seasonality, changing interest rates, and so on.

On the flip side, (TODO: Redo MBA Salary example)

In the housing example, we can imagine that the "population" is some large number of future home sales, and our "sample" is the historical data. If the historical data are a good representation of future outcomes, then we treat them as a random sample from that population of future sales when we make our inferences. That's less natural than 

--->
</section>
<section id="data-used-in-this-section" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="data-used-in-this-section">Data used in this section</h2>
<ul>
<li><a href="./appendix_data.html#sec-data-lendingclub-kaggle">LendingClub Accepted Loans</a></li>
</ul>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>The two settings are not identical: after we sample one adult, the composition of the remaining population changes slightly, while one coin flip does not affect the next. With more than 260 million adults in the population, that difference is negligible for a sample of 1,000.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./singlevar_05_categorical.html" class="pagination-link" aria-label="Categorical Variables">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Categorical Variables</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./prob_02_probability-basics.html" class="pagination-link" aria-label="Probability Basics">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Probability Basics</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>