<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>14&nbsp; Combining Random Variables – TEMBA Statistics — Course Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./appendix_data.html" rel="next">
<link href="./prob_08_quantitative-quantitative.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d3f7f8e73c8d287b30bcf59c2b563615.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/foldbox/foldbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>
.Definition {
  --color1: #F4EAF0;
  --color2: #7C3F58;
}
.TechnicalDetail {
  --color1: #EEF1F3;
  --color2: #5B6770;
}
.Notation {
  --color1: #EEF1F3;
  --color2: #5B6770;
}
.Exercise {
  --color1: #E7F4F5;
  --color2: #147D85;
}
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles/callouts.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./prob_09_combining-random-variables.html">Combining Random Variables</a></li><li class="breadcrumb-item"><a href="./prob_09_combining-random-variables.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Combining Random Variables</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">TEMBA Statistics — Course Notes</a> 
        <div class="sidebar-tools-main">
    <a href="./../index.html" title="Course site" class="quarto-navigation-tool px-1" aria-label="Course site"><i class="bi bi-house-door"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Data analysis and visualization for one variable</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_01_visualizing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Visualizing a Single Quantitative Variable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_02_describing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Distributions of Quantitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_03_location-and-spread.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Measuring Location and Spread</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_04_transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Transforming Quantitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_05_categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Categorical Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Probability for one variable</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_01_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introduction to Probability and Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_02_probability-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Probability Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_03_distribution-parameters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Measures of Location and Spread (and Other Parameters of Probability Distributions)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_04_normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">The Normal Distribution</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Probability Models for Multiple Variables</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_05_multivariate-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Joint, Marginal, and Conditional Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_06_probability-trees-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability Trees, Total Probability, and Bayes’ Rule</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_07_independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Independence</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Analyzing and Combining Quantitative Variables</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_08_quantitative-quantitative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Visualizing and Summarizing Two Quantitative Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Combining Random Variables</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_09_combining-random-variables.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Combining Random Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-linear-combinations" id="toc-sec-linear-combinations" class="nav-link active" data-scroll-target="#sec-linear-combinations"><span class="header-section-number">14.1</span> Portfolios as linear combinations</a></li>
  <li><a href="#sec-lincom-rules" id="toc-sec-lincom-rules" class="nav-link" data-scroll-target="#sec-lincom-rules"><span class="header-section-number">14.2</span> The mean and variance of a linear combination</a></li>
  <li><a href="#sec-portfolio-risk" id="toc-sec-portfolio-risk" class="nav-link" data-scroll-target="#sec-portfolio-risk"><span class="header-section-number">14.3</span> Portfolio risk and diversification</a>
  <ul class="collapse">
  <li><a href="#sec-three-asset-diversification" id="toc-sec-three-asset-diversification" class="nav-link" data-scroll-target="#sec-three-asset-diversification"><span class="header-section-number">14.3.1</span> Choosing between two diversifiers</a></li>
  </ul></li>
  <li><a href="#sec-portfolio-data" id="toc-sec-portfolio-data" class="nav-link" data-scroll-target="#sec-portfolio-data"><span class="header-section-number">14.4</span> Comparing Sharpe ratios: SPY and VCIT</a>
  <ul class="collapse">
  <li><a href="#sec-portfolio-optimization" id="toc-sec-portfolio-optimization" class="nav-link" data-scroll-target="#sec-portfolio-optimization"><span class="header-section-number">14.4.1</span> Choosing the weights</a></li>
  <li><a href="#sec-sharpe" id="toc-sec-sharpe" class="nav-link" data-scroll-target="#sec-sharpe"><span class="header-section-number">14.4.2</span> Return per unit of variability</a></li>
  </ul></li>
  <li><a href="#practice" id="toc-practice" class="nav-link" data-scroll-target="#practice"><span class="header-section-number">14.5</span> Practice</a></li>
  <li><a href="#data-used-in-this-section" id="toc-data-used-in-this-section" class="nav-link" data-scroll-target="#data-used-in-this-section">Data used in this section</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./prob_09_combining-random-variables.html">Combining Random Variables</a></li><li class="breadcrumb-item"><a href="./prob_09_combining-random-variables.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Combining Random Variables</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Combining Random Variables</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Often we’re interested in a particular combination or combinations of random variables. A firm’s forecasted profit is the difference between forecasted revenue and costs. A portfolio’s return is a weighted average of the returns of the assets it holds, with weights given by the fractions invested in each asset. In each case we combine random variables to form a new one, and that combination is <em>linear</em>: we add or take differences between two random variables, possibly after scaling them (as in the portfolio example). The expected value of a <em>linear combination</em> follows from the expected values of its components, regardless of their dependence. Its variance also depends on their <em>covariance</em>, which we related to correlation in the last chapter.</p>
<section id="sec-linear-combinations" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="sec-linear-combinations"><span class="header-section-number">14.1</span> Portfolios as linear combinations</h2>
<p>Let’s start with one of the most salient examples of a linear combination: building a portfolio by allocating our capital across two or more investments. Suppose we invest a fraction <span class="math inline">\(w\)</span> of our money in one asset and the remaining <span class="math inline">\(1-w\)</span> in another. Let <span class="math inline">\(R_1\)</span> and <span class="math inline">\(R_2\)</span> denote their returns over the next week. The portfolio return is</p>
<p><span class="math display">\[
R_p=wR_1+(1-w)R_2.
\]</span></p>
<p>The return on our total investment is a weighted average of the two asset returns. The fractions invested are the <strong>portfolio weights</strong>. For example, a 60/40 portfolio earns <span class="math inline">\(0.60(0.02)+0.40(-0.01)=0.008\)</span>, or 0.8%, in a week when the first asset gains 2% and the second loses 1%.</p>
<div id="defn-linear-combination" class="Definition">
<div class="Definition fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-book fobx-icon" aria-hidden="true"></i><strong>Definition 14.1: </strong>Linear combination of random variables</div><div class="fobx-body">
<p>A <strong>linear combination</strong> of random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> has the form</p>
<p><span class="math display">\[
Z=aX+bY+c,
\]</span></p>
<p>where <span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span>, and <span class="math inline">\(c\)</span> are constants. We scale each variable, add the results, and shift the total by <span class="math inline">\(c\)</span>.</p>
</div></div>
</div>
<p>The portfolio has <span class="math inline">\(a=w\)</span>, <span class="math inline">\(b=1-w\)</span>, and <span class="math inline">\(c=0\)</span>. Profit provides another example: if <span class="math inline">\(X\)</span> is revenue, <span class="math inline">\(Y\)</span> is variable cost, and fixed costs are $100,000, then profit is <span class="math inline">\(X-Y-100{,}000\)</span>. Both revenue and variable costs are uncertain; the fixed cost shifts every possible profit by the same amount.</p>
</section>
<section id="sec-lincom-rules" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="sec-lincom-rules"><span class="header-section-number">14.2</span> The mean and variance of a linear combination</h2>
<p>The mean of a sum follows the intuitive rule: Averages add. If average monthly revenue from our west coast office is $1m, and average revenue from our east coast office is $2.3m, then our total average revenue across the two offices must be $1m + $2.3m = $3.3m. In terms of expected values, this means <span class="math display">\[
E[X + Y] = E[X] + E[Y]
\]</span> Coupled with our rules about linear transformations of a single variable — the shifting and scaling we did for <a href="./singlevar_04_transformations.html#sec-linear-transformations">data</a> and for <a href="./prob_03_distribution-parameters.html#sec-shift-scale">random variables</a> — we get the following general rule for the expected value of a linear combination of two variables:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The mean of a linear combination
</div>
</div>
<div class="callout-body-container callout-body">
<p>For random variables with finite expected values,</p>
<p><span class="math display">\[
E[aX+bY+c]=aE[X]+bE[Y]+c.
\]</span></p>
<p>We combine the expected values with the same weights and constant as the random variables. The rule holds whether or not the variables are independent.</p>
</div>
</div>
<p>For our portfolio, this just means that our expected returns for the portfolio are a weighted average of the expected returns of each investment:</p>
<p><span class="math display">\[
E[R_p]=wE[R_1]+(1-w)E[R_2].
\]</span></p>
<p>Variance and standard deviation behave quite a bit differently. If the assets in our portfolio tend to move together, they will often be up or down at the same time. Alternatively, if they tend to move in opposite directions then they hedge each other, providing more predictable returns — lower portfolio variance. This effect is measured by the size of the <em>covariance</em> between the two variables in the linear combination:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The variance of a linear combination
</div>
</div>
<div class="callout-body-container callout-body">
<p>For random variables with finite variances,</p>
<p><span class="math display">\[
\operatorname{Var}(aX+bY+c)
=a^2\operatorname{Var}(X)+b^2\operatorname{Var}(Y)
+2ab\operatorname{Cov}(X,Y).
\]</span></p>
<p>We multiply each variance by its squared weight and add the covariance term. The constant <span class="math inline">\(c\)</span> changes the location but not the spread. If the variables are uncorrelated, the covariance term is zero and only the first two terms remain. Independence is sufficient for this simplification, as we saw in Chapter 13.</p>
</div>
</div>
<p>The signs of the weights matter. For a sum, positive covariance increases variance. For a difference, <span class="math inline">\(a=1\)</span> and <span class="math inline">\(b=-1\)</span>, so positive covariance reduces variance: when revenue and costs rise together, part of their movement cancels in profit. In either case we take the square root of the variance to obtain the standard deviation.</p>
<p>The same algebra holds for sample summaries. If we create a data column <span class="math inline">\(z_i=ax_i+by_i+c\)</span>, then</p>
<p><span class="math display">\[
\bar z=a\bar x+b\bar y+c,\qquad
s_z^2=a^2s_x^2+b^2s_y^2+2ab s_{xy}.
\]</span></p>
<p>These are the sample mean and variance of the combined column, with <span class="math inline">\(s_{xy}\)</span> the sample covariance from Chapter 13. We can therefore compute a portfolio’s historical summaries directly from the two assets’ sample summaries. Using those historical quantities to describe future returns requires a further assumption that the past is informative about the future.</p>
</section>
<section id="sec-portfolio-risk" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="sec-portfolio-risk"><span class="header-section-number">14.3</span> Portfolio risk and diversification</h2>
<p>For the two-asset portfolio, recall that the mean rule gives</p>
<p><span class="math display">\[
E[R_p]=wE[R_1]+(1-w)E[R_2].
\]</span></p>
<p>Expected return is the weighted average of the assets’ expected returns. The variance rule gives</p>
<p><span class="math display">\[
\operatorname{Var}(R_p)
=w^2\operatorname{Var}(R_1)+(1-w)^2\operatorname{Var}(R_2)
+2w(1-w)\operatorname{Cov}(R_1,R_2).
\]</span></p>
<p>Portfolio variability depends on the covariance as well as the individual variances. We use standard deviation as a measure of investment risk here: it describes variability in returns, including both gains and losses.</p>
<p>Suppose two hypothetical stocks each have a 10% expected annual return and a 20% annual standard deviation. An equal-weight portfolio also has a 10% expected return. Using the identity <span class="math inline">\(\operatorname{Cov}(R_1,R_2)=\operatorname{Corr}(R_1,R_2)(0.20)(0.20)\)</span> from Chapter 13, its variance is</p>
<p><span class="math display">\[
\operatorname{Var}(R_p)=0.02+0.02\operatorname{Corr}(R_1,R_2).
\]</span></p>
<p>Only the correlation varies in this example. The table and curve show how lower correlation reduces the standard deviation of the equal-weight portfolio while leaving expected return unchanged.</p>
<div class="cell">
<div id="tbl-risk-correlation" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-risk-correlation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14.1: Equal-weight portfolios of two hypothetical stocks, each with a 20% annual standard deviation and a 10% expected annual return.
</figcaption>
<div aria-describedby="tbl-risk-correlation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Correlation</th>
<th style="text-align: right;">Portfolio standard deviation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">20.0%</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">17.3%</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">14.1%</td>
</tr>
<tr class="even">
<td style="text-align: right;">-0.5</td>
<td style="text-align: right;">10.0%</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-1.0</td>
<td style="text-align: right;">0.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-risk-vs-corr" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-risk-vs-corr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob_09_combining-random-variables_files/figure-html/fig-risk-vs-corr-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-risk-vs-corr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.1: Standard deviation of the equal-weight portfolio as correlation varies. The dashed line marks the 20% standard deviation of either stock alone.
</figcaption>
</figure>
</div>
</div>
</div>
<p>At correlation <span class="math inline">\(-1\)</span>, the equally sized deviations cancel exactly, so this particular portfolio has no variability. Perfect negative correlation is not necessary for <strong>diversification</strong>, the reduction in variability from combining assets whose returns do not move perfectly together. Even with a positive correlation of 0.5, this portfolio has lower standard deviation than either stock alone. With unequal asset variances, the weights also affect how much reduction we obtain.</p>
<section id="sec-three-asset-diversification" class="level3" data-number="14.3.1">
<h3 data-number="14.3.1" class="anchored" data-anchor-id="sec-three-asset-diversification"><span class="header-section-number">14.3.1</span> Choosing between two diversifiers</h3>
<p>The <code>portfolios</code> data record weekly returns on three exchange-traded funds over the two years from October 2023 through September 2025 <span class="citation" data-cites="portfolios-2025">(<a href="appendix_data.html#ref-portfolios-2025" role="doc-biblioref"><em>Three-Asset Weekly Return and Price Series, October 2023–September 2025</em> 2025</a>)</span>. An exchange-traded fund (ETF) holds a basket of assets and trades like a single stock, so buying one share buys a slice of the whole basket. <code>SPY</code> holds the S&amp;P 500 and is a standard stand-in for the U.S. stock market — it’s the same market series we have used since the chapter on describing distributions. <code>EFA</code> holds large stocks from developed markets outside North America: Europe, Japan, Australia. <code>TLT</code> holds long-term U.S. Treasury bonds, government debt with twenty or more years to maturity. Each return is the percent change in the fund’s value from one Friday close to the next, expressed as a proportion, for 104 weeks.</p>
<p>Suppose your entire portfolio is currently the U.S. market — all <code>SPY</code> — and you’ve decided to diversify by adding exactly one of the other two funds. Which one? <a href="#fig-asset-returns" class="quarto-xref">Figure&nbsp;<span>14.2</span></a> plots the three return series, and the summary table follows.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-asset-returns" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-asset-returns-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob_09_combining-random-variables_files/figure-html/fig-asset-returns-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-asset-returns-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.2: Weekly returns on the three funds over the two years ending September 2025. The three series are about equally volatile — similar-sized swings around zero — but they differ in average level and, less visibly, in how they move together.
</figcaption>
</figure>
</div>
</div>
</div>
<div id="technical-annualization" class="TechnicalDetail">
<details class="TechnicalDetail fobx-simplebox fobx-default"><summary><strong>Technical detail 14.1: </strong>Annualized summaries</summary><div>
<p>We multiply the weekly mean by 52 and the weekly standard deviation by <span class="math inline">\(\sqrt{52}\)</span>. The first is an annualized arithmetic mean, not the compounded return over a year. The standard-deviation scaling assumes uncorrelated weekly returns with a common variance.</p>
</div></details>
</div>
<div class="cell">
<div id="tbl-asset-summary-three" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-asset-summary-three-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14.2: Annualized sample mean return and risk for the three funds, estimated from two years of weekly returns.
</figcaption>
<div aria-describedby="tbl-asset-summary-three-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 4%">
<col style="width: 35%">
<col style="width: 29%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Fund</th>
<th style="text-align: left;">Holds</th>
<th style="text-align: right;">Sample mean return (annualized)</th>
<th style="text-align: right;">Standard deviation (annualized)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SPY</td>
<td style="text-align: left;">U.S. stocks (S&amp;P 500)</td>
<td style="text-align: right;">24.4%</td>
<td style="text-align: right;">15.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EFA</td>
<td style="text-align: left;">International developed-market stocks</td>
<td style="text-align: right;">19.7%</td>
<td style="text-align: right;">15.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TLT</td>
<td style="text-align: left;">Long-term U.S. Treasury bonds</td>
<td style="text-align: right;">6.2%</td>
<td style="text-align: right;">15.1%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>All three funds carried nearly identical risk over this window — about 15% a year — and <code>EFA</code>’s sample mean return of 19.7% is more than three times <code>TLT</code>’s 6.2%. Why would anyone choose <code>TLT</code>?</p>
<p>Because the mean and standard deviation in the table describe each fund <em>held on its own</em>, and you aren’t going to hold either fund on its own — you’re going to mix it with <code>SPY</code>, and the portfolio variance formula needs an input the table doesn’t show: the covariance between each candidate and the fund you already hold. <a href="#fig-scatter-spy-three" class="quarto-xref">Figure&nbsp;<span>14.3</span></a> supplies it.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scatter-spy-three" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scatter-spy-three-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob_09_combining-random-variables_files/figure-html/fig-scatter-spy-three-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scatter-spy-three-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.3: Each candidate fund’s weekly return plotted against SPY’s, over the same 104 weeks.
</figcaption>
</figure>
</div>
</div>
</div>
<p><code>EFA</code> is a stock fund, and international stocks catch most of the same news that moves U.S. stocks: a week that’s bad for <code>SPY</code> is usually bad for <code>EFA</code> too. Its correlation with the market is 0.75. <code>TLT</code>’s correlation is 0.08 — Treasury bonds respond to interest rates and inflation news, not corporate earnings, and over this window their moves were almost uncorrelated with the stock market’s.</p>
<p>Now run both candidate portfolios through the rules of <a href="#sec-lincom-rules" class="quarto-xref"><span>Section 14.2</span></a>, using the sample means, standard deviations, and covariances as inputs. <a href="#fig-weight-curves-three" class="quarto-xref">Figure&nbsp;<span>14.4</span></a> shows the sample mean return and risk of each mix as the weight on <code>SPY</code> sweeps from 0 to 1.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-weight-curves-three" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-weight-curves-three-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob_09_combining-random-variables_files/figure-html/fig-weight-curves-three-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-weight-curves-three-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.4: Sample mean return (left) and risk (right) of the two candidate portfolios as the weight on SPY varies, computed from the sample moments. The two mixes’ sample mean returns both fall as SPY’s weight falls, EFA’s much more slowly. But mixing in EFA barely reduces risk, while mixing in TLT cuts it to about 11% at an even split.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The left panel shows that at every weight below 100% <code>SPY</code>, the <code>EFA</code> mix has the higher sample mean return, as expected. The right panel is more interesting. The <code>SPY + EFA</code> curve barely bends. The high degree of correlation means that the two ETFs tend to move together and the only diversification benefit comes from the weeks they don’t. No weighting of <code>SPY</code> and <code>EFA</code> gets the portfolio’s risk below about 14.2%. The <code>SPY + TLT</code> curve declines faster and bottoms out lower, near 11.1% at roughly an even split. Their low correlation allows much more of their variability to offset in the portfolio.</p>
<p>There is no universally right portfolio. The right choice depends on what we are optimizing for, but whatever the goal, the comparison should account for both sample mean return and risk. One way to compare the options is to fix a risk target and ask what sample mean return each can deliver. For example, take 14.2% — the lowest risk the <code>EFA</code> pairing can reach at any weight. The best <code>EFA</code> mix at that risk earns 21.9%. The <code>TLT</code> mix that hits the same risk holds 92% <code>SPY</code> and earns 22.9%:</p>
<div class="cell">
<div id="tbl-portfolio-compare-three" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-portfolio-compare-three-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14.3: Candidate portfolios compared at approximately the same annualized sample standard deviation.
</figcaption>
<div aria-describedby="tbl-portfolio-compare-three-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 53%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Portfolio</th>
<th style="text-align: right;">Sample mean return</th>
<th style="text-align: right;">Standard deviation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">100% SPY</td>
<td style="text-align: right;">24.4%</td>
<td style="text-align: right;">15.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Best SPY + EFA mix at 14.2% risk (48% SPY)</td>
<td style="text-align: right;">21.9%</td>
<td style="text-align: right;">14.2%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SPY + TLT mix at the same risk (92% SPY)</td>
<td style="text-align: right;">22.9%</td>
<td style="text-align: right;">14.2%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>At the same level of risk, the <code>TLT</code> portfolio delivers about 1.0 percentage points more sample mean return. And if you want <em>less</em> risk than 14.2%, only the <code>TLT</code> portfolio can get there — all the way down to 11.1% if you like.</p>
</section>
</section>
<section id="sec-portfolio-data" class="level2" data-number="14.4">
<h2 data-number="14.4" class="anchored" data-anchor-id="sec-portfolio-data"><span class="header-section-number">14.4</span> Comparing Sharpe ratios: SPY and VCIT</h2>
<p>We now combine <code>SPY</code> with another bond fund, <code>VCIT</code>, which holds intermediate-term investment-grade corporate bonds. Our data contain 104 weekly returns from October 06, 2023 through September 26, 2025, using adjusted closing prices that account for dividends and splits. Each row records the two returns for the same week, expressed as proportions.</p>
<p>The scatterplot shows how the weekly returns move together. The accompanying table reports the two funds’ historical means and standard deviations on an annualized scale.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scatter-spy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scatter-spy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob_09_combining-random-variables_files/figure-html/fig-scatter-spy-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scatter-spy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.5: SPY and VCIT weekly returns over the full common sample. Each point represents the same week for both funds.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div id="tbl-asset-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-asset-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14.4: Annualized sample means and standard deviations over the common weekly-return sample.
</figcaption>
<div aria-describedby="tbl-asset-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Fund</th>
<th style="text-align: right;">Mean return</th>
<th style="text-align: right;">Standard deviation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SPY</td>
<td style="text-align: right;">24.4%</td>
<td style="text-align: right;">15.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">VCIT</td>
<td style="text-align: right;">10.0%</td>
<td style="text-align: right;">6.2%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><code>SPY</code> had both a higher mean return and a higher standard deviation than <code>VCIT</code> during this period. Their sample correlation was 0.23, so the returns did not move closely together. A mixture can therefore have lower variability than either fund alone, although the attainable reduction depends on their different scales.</p>
<section id="sec-portfolio-optimization" class="level3" data-number="14.4.1">
<h3 data-number="14.4.1" class="anchored" data-anchor-id="sec-portfolio-optimization"><span class="header-section-number">14.4.1</span> Choosing the weights</h3>
<p>Let <span class="math inline">\(w\)</span> be the weight on <code>SPY</code>. We restrict it to the interval from 0 to 1, so both weights are nonnegative and sum to 1. For each allocation we compute the historical portfolio mean and standard deviation using the sample rules above. These calculations describe a portfolio rebalanced to the specified weights each week, before trading costs. The curves show how the summaries change as we increase the stock-fund weight.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-weight-curves" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-weight-curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob_09_combining-random-variables_files/figure-html/fig-weight-curves-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-weight-curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.6: Annualized sample mean and standard deviation as the SPY weight varies. The dashed line marks the allocation with the smallest sample standard deviation.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The minimum-standard-deviation portfolio holds 7.5% in <code>SPY</code> and 92.5% in <code>VCIT</code>. Its annualized sample standard deviation is 6.14%, compared with 6.25% for <code>VCIT</code> alone. Adding a small stock allocation reduces variability even though the stock fund is more variable on its own. Beyond this allocation, increasing the stock weight raises both the historical mean and standard deviation.</p>
</section>
<section id="sec-sharpe" class="level3" data-number="14.4.2">
<h3 data-number="14.4.2" class="anchored" data-anchor-id="sec-sharpe"><span class="header-section-number">14.4.2</span> Return per unit of variability</h3>
<p>Minimizing standard deviation uses no information about the mean return. If we want to compare return above a risk-free benchmark relative to variability, we can use the <strong>Sharpe ratio</strong> <span class="citation" data-cites="sharpe-1966">(<a href="appendix_data.html#ref-sharpe-1966" role="doc-biblioref">Sharpe 1966</a>)</span>.</p>
<div id="defn-sharpe-ratio" class="Definition">
<div class="Definition fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-book fobx-icon" aria-hidden="true"></i><strong>Definition 14.2: </strong>The Sharpe ratio</div><div class="fobx-body">
<p>For a portfolio with positive standard deviation and a constant risk-free return <span class="math inline">\(r_f\)</span> over the same period,</p>
<p><span class="math display">\[
\text{Sharpe ratio}=\frac{E[R_p]-r_f}{\operatorname{SD}(R_p)}.
\]</span></p>
<p>The numerator is expected return above the risk-free benchmark. Dividing by standard deviation expresses that excess return per unit of variability.</p>
</div></div>
</div>
<p>For the historical comparison, we substitute each portfolio’s sample mean and standard deviation. We use the data’s average Treasury-bill rate as a constant benchmark, 4.7% annualized. The curve shows the resulting sample Sharpe ratio for every allocation.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-sharpe-weights" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sharpe-weights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob_09_combining-random-variables_files/figure-html/fig-sharpe-weights-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sharpe-weights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.7: Sample Sharpe ratio using the annualized sample-average Treasury-bill rate as a constant benchmark. The point marks the maximizing allocation.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The maximum occurs at 44.7% in <code>SPY</code>, with a sample Sharpe ratio of 1.41. This portfolio accepts more variability than the minimum-standard-deviation allocation in exchange for a higher historical mean. The table compares both allocations with the individual funds.</p>
<div class="cell">
<div id="tbl-portfolio-compare" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-portfolio-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14.5: Two allocation objectives compared with holding either fund alone. Means and standard deviations are annualized sample summaries.
</figcaption>
<div aria-describedby="tbl-portfolio-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 33%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 22%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Allocation</th>
<th style="text-align: right;">SPY weight</th>
<th style="text-align: right;">Mean return</th>
<th style="text-align: right;">Standard deviation</th>
<th style="text-align: right;">Sharpe ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">All VCIT</td>
<td style="text-align: right;">0.0%</td>
<td style="text-align: right;">10.0%</td>
<td style="text-align: right;">6.2%</td>
<td style="text-align: right;">0.85</td>
</tr>
<tr class="even">
<td style="text-align: left;">Minimum standard deviation</td>
<td style="text-align: right;">7.5%</td>
<td style="text-align: right;">11.1%</td>
<td style="text-align: right;">6.1%</td>
<td style="text-align: right;">1.04</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Maximum sample Sharpe ratio</td>
<td style="text-align: right;">44.7%</td>
<td style="text-align: right;">16.4%</td>
<td style="text-align: right;">8.3%</td>
<td style="text-align: right;">1.41</td>
</tr>
<tr class="even">
<td style="text-align: left;">All SPY</td>
<td style="text-align: right;">100.0%</td>
<td style="text-align: right;">24.4%</td>
<td style="text-align: right;">15.3%</td>
<td style="text-align: right;">1.29</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>We selected these weights using the same observations that supply the reported performance. The maximizing allocation therefore describes this sample; it does not establish which allocation will have the highest Sharpe ratio in future returns. Over this window, the minimum-variability mix and the maximum-Sharpe mix answer different questions and assign different weights to the same two funds.</p>
</section>
</section>
<section id="practice" class="level2" data-number="14.5">
<h2 data-number="14.5" class="anchored" data-anchor-id="practice"><span class="header-section-number">14.5</span> Practice</h2>
<div id="exercise-linear-combinations" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 14.1: </strong>Combining uncertain quantities</div><div class="fobx-body">
<ol type="1">
<li>A firm’s revenue has standard deviation $200,000, and its variable costs have standard deviation $120,000. Their correlation is 0.6. Find the standard deviation of revenue minus variable costs. What would change if the correlation were zero?</li>
<li>Two assets each have a standard deviation of 20%. An equal-weight portfolio has standard deviation 10%. Find their correlation.</li>
<li>In the SPY–VCIT example, why does the allocation that minimizes standard deviation differ from the one that maximizes the sample Sharpe ratio?</li>
<li>Suppose a portfolio has expected annual return 8%, annual standard deviation 12%, and an annual risk-free benchmark of 3%. Compute its Sharpe ratio. Explain which inputs would change if the benchmark rose to 4% while the return distribution stayed the same.</li>
</ol>
<details id="details-1" class="solution-details" aria-label="Solution">
<summary>Solution</summary>
<ol type="1">
<li>In thousands of dollars, the variance is <span class="math inline">\(200^2+120^2-2(0.6)(200)(120)=25{,}600\)</span>, so the standard deviation is $160,000. With zero correlation the covariance term vanishes, giving a standard deviation of about $233,238.</li>
<li>The equation <span class="math inline">\(0.10^2=0.02+0.02\operatorname{Corr}\)</span> gives a correlation of <span class="math inline">\(-0.5\)</span>.</li>
<li>Minimizing standard deviation uses the two variances and their covariance. The Sharpe ratio also uses the mean returns and the benchmark. In this sample its maximizing allocation gives more weight to SPY’s higher mean return and accepts a higher standard deviation.</li>
<li>The Sharpe ratio is <span class="math inline">\((0.08-0.03)/0.12\approx0.417\)</span>. With the higher benchmark, only the excess-return numerator changes; the ratio becomes <span class="math inline">\((0.08-0.04)/0.12\approx0.333\)</span>.</li>
</ol>
</details>
</div></div>
</div>
</section>
<section id="data-used-in-this-section" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="data-used-in-this-section">Data used in this section</h2>
<ul>
<li><a href="./appendix_data.html#sec-data-portfolios-2025">Three-Asset Portfolio Series</a> supplies SPY returns and the Treasury-bill benchmark.</li>
<li><a href="./appendix_data.html#sec-data-returns-2025">Weekly Asset Returns</a> supplies VCIT returns over the same dates.</li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-sharpe-1966" class="csl-entry" role="listitem">
Sharpe, William F. 1966. <span>“Mutual Fund Performance.”</span> <em>The Journal of Business</em> 39 (1): 119–38.
</div>
<div id="ref-portfolios-2025" class="csl-entry" role="listitem">
<em>Three-Asset Weekly Return and Price Series, October 2023–September 2025</em>. 2025. Assembled from Yahoo Finance via the <code>tidyquant</code> R package (<a href="https://cran.r-project.org/package=tidyquant" class="uri">https://cran.r-project.org/package=tidyquant</a>).
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./prob_08_quantitative-quantitative.html" class="pagination-link" aria-label="Visualizing and Summarizing Two Quantitative Variables">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Visualizing and Summarizing Two Quantitative Variables</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./appendix_data.html" class="pagination-link" aria-label="Datasets">
        <span class="nav-page-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>