<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; Joint, Marginal, and Conditional Distributions – TEMBA Statistics — Course Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./prob_06_probability-trees-bayes.html" rel="next">
<link href="./prob_04_normal.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d3f7f8e73c8d287b30bcf59c2b563615.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/foldbox/foldbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>
.Definition {
  --color1: #F4EAF0;
  --color2: #7C3F58;
}
.TechnicalDetail {
  --color1: #EEF1F3;
  --color2: #5B6770;
}
.Exercise {
  --color1: #E7F4F5;
  --color2: #147D85;
}
.Notation {
  --color1: #EEF1F3;
  --color2: #5B6770;
}
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles/callouts.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./prob_05_multivariate-distributions.html">Probability Models for Multiple Variables</a></li><li class="breadcrumb-item"><a href="./prob_05_multivariate-distributions.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Joint, Marginal, and Conditional Distributions</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">TEMBA Statistics — Course Notes</a> 
        <div class="sidebar-tools-main">
    <a href="./../index.html" title="Course site" class="quarto-navigation-tool px-1" aria-label="Course site"><i class="bi bi-house-door"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Data analysis and visualization for one variable</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_01_visualizing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Visualizing a Single Quantitative Variable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_02_describing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Distributions of Quantitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_03_location-and-spread.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Measuring Location and Spread</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_04_transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Transforming Quantitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_05_categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Categorical Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Probability for one variable</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_01_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introduction to Probability and Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_02_probability-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Probability Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_03_distribution-parameters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Measures of Location and Spread (and Other Parameters of Probability Distributions)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_04_normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">The Normal Distribution</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Probability Models for Multiple Variables</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_05_multivariate-distributions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Joint, Marginal, and Conditional Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_06_probability-trees-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability Trees, Total Probability, and Bayes’ Rule</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_07_independence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Independence</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Analyzing and Combining Quantitative Variables</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_08_quantitative-quantitative.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Visualizing and Summarizing Two Quantitative Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Combining Random Variables</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_09_combining-random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Combining Random Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-crosstabs" id="toc-sec-crosstabs" class="nav-link active" data-scroll-target="#sec-crosstabs"><span class="header-section-number">10.1</span> Cross-tabulations and contingency tables</a></li>
  <li><a href="#sec-joint-marginal-conditional-proportions" id="toc-sec-joint-marginal-conditional-proportions" class="nav-link" data-scroll-target="#sec-joint-marginal-conditional-proportions"><span class="header-section-number">10.2</span> From crosstabs to joint distributions</a></li>
  <li><a href="#sec-loan-probability-model" id="toc-sec-loan-probability-model" class="nav-link" data-scroll-target="#sec-loan-probability-model"><span class="header-section-number">10.3</span> A probability model for future loans</a>
  <ul class="collapse">
  <li><a href="#conditional-probability" id="toc-conditional-probability" class="nav-link" data-scroll-target="#conditional-probability"><span class="header-section-number">10.3.1</span> Conditional probability</a></li>
  </ul></li>
  <li><a href="#data-used-in-this-section" id="toc-data-used-in-this-section" class="nav-link" data-scroll-target="#data-used-in-this-section">Data used in this section</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./prob_05_multivariate-distributions.html">Probability Models for Multiple Variables</a></li><li class="breadcrumb-item"><a href="./prob_05_multivariate-distributions.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Joint, Marginal, and Conditional Distributions</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Joint, Marginal, and Conditional Distributions</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>We want to understand the relationship between default risk and loan purpose. That relationship is an important input into the business decision of whether to write a loan and how to set its terms. Which loan purposes have the greatest default risk?</p>
<section id="sec-crosstabs" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="sec-crosstabs"><span class="header-section-number">10.1</span> Cross-tabulations and contingency tables</h2>
<p>We’ll start with counts, because everything else in this chapter is a count divided by some total.</p>
<div id="defn-cross-tabulation" class="Definition">
<div class="Definition fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-book fobx-icon" aria-hidden="true"></i><strong>Definition 10.1: </strong>Cross-tabulation</div><div class="fobx-body">
<p>A <strong>cross-tabulation</strong> or <strong>“crosstab”</strong> — also called a <strong>contingency table</strong> — counts how many observations fall into each <em>combination</em> of two variables’ categories. It has one row per category of the first variable, one column per category of the second, and a count in every cell. Its <strong>margins</strong>, the row and column of totals, are the frequency tables for the individual variables.</p>
</div></div>
</div>
<p>Fourteen purposes make for a bulky table. We want every calculation in this section small enough to check by hand, so we’ll narrow to the 58,456 loans with three of the more interesting purposes: debt consolidation, home improvement, and small business. <a href="#tbl-purpose-default-counts" class="quarto-xref">Table&nbsp;<span>10.1</span></a> shows their crosstab with loan status.</p>
<div class="cell">
<div id="tbl-purpose-default-counts" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-purpose-default-counts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.1: Cross-tabulation of loan purpose and final loan status for the three-purpose subset. Each cell counts the loans with that combination of purpose and outcome; the margins recover the one-variable frequency tables.
</figcaption>
<div aria-describedby="tbl-purpose-default-counts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Purpose</th>
<th style="text-align: right;">Charged Off</th>
<th style="text-align: right;">Fully Paid</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">debt_consolidation</td>
<td style="text-align: right;">8,131</td>
<td style="text-align: right;">41,278</td>
<td style="text-align: right;">49,409</td>
</tr>
<tr class="even">
<td style="text-align: left;">home_improvement</td>
<td style="text-align: right;">717</td>
<td style="text-align: right;">5,139</td>
<td style="text-align: right;">5,856</td>
</tr>
<tr class="odd">
<td style="text-align: left;">small_business</td>
<td style="text-align: right;">822</td>
<td style="text-align: right;">2,369</td>
<td style="text-align: right;">3,191</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: right;">9,670</td>
<td style="text-align: right;">48,786</td>
<td style="text-align: right;">58,456</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Look at the margins first, the row and column labeled <code>Total</code>. The <code>Total</code> column on the right is a frequency table of <code>purpose</code> — the same one-variable summary we built earlier, computed on this subset — and the bottom row is the frequency table of loan status: 48,786 fully paid, 9,670 charged off. The interior cells record how the two variables tend to move <strong>together</strong>.</p>
<p>With two variables there are three different totals we could divide each count by, and each choice answers a different question. Take the cell for small-business loans that charged off. Dividing it by the grand total gives the share of all loans that are small business <em>and</em> charged off:</p>
<p><span class="math display">\[
\frac{822}{58,456} = 0.014.
\]</span></p>
<div id="defn-joint-proportion" class="Definition">
<div class="Definition fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-book fobx-icon" aria-hidden="true"></i><strong>Definition 10.2: </strong>Joint proportion</div><div class="fobx-body">
<p>A <strong>joint proportion</strong> divides an interior cell of a crosstab by the grand total. It is the share of all observations with that combination of categories. The collection of all the joint proportions is the <strong>joint distribution</strong> of the two variables.</p>
</div></div>
</div>
<p>Dividing the small-business row total — the two cells in that row added together — by the grand total gives the share of all loans that are small business:</p>
<p><span class="math display">\[
\frac{2,369 + 822}{58,456}
= \frac{3,191}{58,456}
= 0.055.
\]</span></p>
<div id="defn-marginal-proportion" class="Definition">
<div class="Definition fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-book fobx-icon" aria-hidden="true"></i><strong>Definition 10.3: </strong>Marginal proportion</div><div class="fobx-body">
<p>A <strong>marginal proportion</strong> divides a row or column total by the grand total. It gives one category’s share without separating the observations by the other variable. Equivalently, we can add the joint proportions across the corresponding row or column.</p>
</div></div>
</div>
<p>For small-business loans, the marginal proportion is the sum of the two joint proportions in that row:</p>
<p><span class="math display">\[
0.041
+ 0.014
= 0.055.
\]</span></p>
<p>The crosstab has everything we need to answer the opening question: which loan purposes have the greatest default risk? To compute the small-business default rate, the only relevant information is about small-business loans, so we ignore the other rows and divide by the small-business loan total rather than the grand total. From the counts in <a href="#tbl-purpose-default-counts" class="quarto-xref">Table&nbsp;<span>10.1</span></a>, 822 of the 3,191 small-business loans charged off:</p>
<p><span class="math display">\[
\frac{822}{3,191} = 0.258.
\]</span></p>
<div id="defn-conditional-proportion" class="Definition">
<div class="Definition fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-book fobx-icon" aria-hidden="true"></i><strong>Definition 10.4: </strong>Conditional proportion</div><div class="fobx-body">
<p>A <strong>conditional proportion</strong> divides a cell by its row or column total rather than the grand total. It is the share in one category of one variable among observations in one category of the other. The conditional proportions across all categories of the variable being summarized form its <strong>conditional distribution</strong>.</p>
<p>The direction of the conditioning matters. Among small-business loans, the share that charged off is 0.258. Among charged-off loans, the share issued to small businesses is 0.085. Both calculations begin with the same cell but divide by different totals.</p>
</div></div>
</div>
<p><a href="#tbl-default-rate-by-purpose" class="quarto-xref">Table&nbsp;<span>10.2</span></a> collects the default rates for all three purposes.</p>
<div class="cell">
<div id="tbl-default-rate-by-purpose" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-default-rate-by-purpose-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.2: Default rate by loan purpose: the proportion of loans charged off, given each purpose. Purposes are sorted from highest to lowest default rate.
</figcaption>
<div aria-describedby="tbl-default-rate-by-purpose-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Purpose</th>
<th style="text-align: right;">Loans</th>
<th style="text-align: right;">Default rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">small_business</td>
<td style="text-align: right;">3,191</td>
<td style="text-align: right;">0.258</td>
</tr>
<tr class="even">
<td style="text-align: left;">debt_consolidation</td>
<td style="text-align: right;">49,409</td>
<td style="text-align: right;">0.165</td>
</tr>
<tr class="odd">
<td style="text-align: left;">home_improvement</td>
<td style="text-align: right;">5,856</td>
<td style="text-align: right;">0.122</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div id="exercise-hybrid-work-attrition" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 10.1: </strong>Hybrid work and attrition</div><div class="fobx-body">
<p>Bloom, Han, and Liang randomly assigned 1,612 employees to a control schedule or a hybrid schedule with two work-from-home days per week <span class="citation" data-cites="wfh-bloom">(<a href="appendix_data.html#ref-wfh-bloom" role="doc-biblioref">Bloom et al. 2024</a>)</span>. During the study, the following employees stayed at or left the firm:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Assigned schedule</th>
<th style="text-align: right;">Stayed</th>
<th style="text-align: right;">Left</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Control</td>
<td style="text-align: right;">761</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">820</td>
</tr>
<tr class="even">
<td>Hybrid WFH</td>
<td style="text-align: right;">754</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">792</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>1,515</strong></td>
<td style="text-align: right;"><strong>97</strong></td>
<td style="text-align: right;"><strong>1,612</strong></td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Choose one employee at random from the study. Find the joint probability that the employee was assigned to Hybrid WFH and left the firm.</li>
<li>Find the marginal distribution of assigned schedule.</li>
<li>Find the marginal distribution of attrition status.</li>
<li>Find the conditional distribution of attrition status within each assigned schedule. Check that each conditional distribution sums to one.</li>
<li>Find <span class="math inline">\(\Pr(\text{Hybrid WFH}\mid\text{Left})\)</span>.</li>
<li>Explain why the answer to part 5 differs from <span class="math inline">\(\Pr(\text{Left}\mid\text{Hybrid WFH})\)</span>. Name the denominator in each calculation.</li>
</ol>
<details class="solution-details" id="solution-hybrid-work-attrition" aria-label="Solution">
<summary>Solution</summary>
<p>The Hybrid WFH/Left cell contains 38 of the 1,612 employees, so its joint probability is</p>
<p><span class="math display">\[
\frac{38}{1612}=0.0236.
\]</span></p>
<p>The row totals give the marginal distribution of assigned schedule:</p>
<p><span class="math display">\[
\Pr(\text{Control})=\frac{820}{1612}=0.5087,
\qquad
\Pr(\text{Hybrid WFH})=\frac{792}{1612}=0.4913.
\]</span></p>
<p>The column totals give the marginal distribution of attrition status:</p>
<p><span class="math display">\[
\Pr(\text{Stayed})=\frac{1515}{1612}=0.9398,
\qquad
\Pr(\text{Left})=\frac{97}{1612}=0.0602.
\]</span></p>
<p>Within the control group, the conditional distribution of attrition status is</p>
<p><span class="math display">\[
\Pr(\text{Stayed}\mid\text{Control})=\frac{761}{820}=0.9280,
\qquad
\Pr(\text{Left}\mid\text{Control})=\frac{59}{820}=0.0720.
\]</span></p>
<p>Within the Hybrid WFH group, the corresponding distribution is</p>
<p><span class="math display">\[
\Pr(\text{Stayed}\mid\text{Hybrid WFH})=\frac{754}{792}=0.9520,
\qquad
\Pr(\text{Left}\mid\text{Hybrid WFH})=\frac{38}{792}=0.0480.
\]</span></p>
<p>Each pair sums to one because every employee in that schedule either stayed or left. Reversing the condition gives</p>
<p><span class="math display">\[
\Pr(\text{Hybrid WFH}\mid\text{Left})=\frac{38}{97}=0.3918.
\]</span></p>
<p>The two conditional probabilities share the same numerator, 38 employees, but use different denominators. The first conditions on the 97 employees who left; the second conditions on the 792 employees assigned to Hybrid WFH.</p>
</details>
</div></div>
</div>
</section>
<section id="sec-joint-marginal-conditional-proportions" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="sec-joint-marginal-conditional-proportions"><span class="header-section-number">10.2</span> From crosstabs to joint distributions</h2>
<p>Counts depend on the overall sample size. Dividing every count by the grand total normalizes the table: the interior cells now sum to one. A proportion and its percentage are the same number — 0.014 is 1.4% — and from here on we’ll write everything as proportions.</p>
<p><a href="#tbl-purpose-default-joint" class="quarto-xref">Table&nbsp;<span>10.3</span></a> shows the result of dividing every count in <a href="#tbl-purpose-default-counts" class="quarto-xref">Table&nbsp;<span>10.1</span></a> by the grand total, 58,456.</p>
<div class="cell">
<div id="tbl-purpose-default-joint" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-purpose-default-joint-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.3: Joint proportions of purpose and loan status: each count from the crosstab divided by the grand total. All interior cells together sum to one; the margins give each variable’s own distribution.
</figcaption>
<div aria-describedby="tbl-purpose-default-joint-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Purpose</th>
<th style="text-align: right;">Charged Off</th>
<th style="text-align: right;">Fully Paid</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">debt_consolidation</td>
<td style="text-align: right;">0.139</td>
<td style="text-align: right;">0.706</td>
<td style="text-align: right;">0.845</td>
</tr>
<tr class="even">
<td style="text-align: left;">home_improvement</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: right;">0.088</td>
<td style="text-align: right;">0.100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">small_business</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.041</td>
<td style="text-align: right;">0.055</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: right;">0.165</td>
<td style="text-align: right;">0.835</td>
<td style="text-align: right;">1.000</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The interior cells are the joint proportions we computed from the count table. The margins are the corresponding one-variable distributions. As we saw above, the marginal proportion of small-business loans is the sum of the two joint proportions in that row:</p>
<p><span class="math display">\[
0.041
+ 0.014
= 0.055.
\]</span></p>
<p>The fully-paid and charged-off small-business loans together account for 0.055 of all the loans in the table.</p>
<p>The normalized table also gives the conditional proportion. Dividing the joint proportion for “small business and charged off” by the marginal proportion of small-business loans gives the same default rate we computed from counts. Because the table is rounded to three decimals, we carry one extra digit in the calculation:</p>
<p><span class="math display">\[
\frac{0.0141}{0.0546} = 0.258.
\]</span></p>
<p>A conditional proportion is therefore the joint proportion divided by the marginal proportion of the conditioning variable. Dividing count by count or proportion by proportion gives the same answer because the grand total cancels.</p>
<p>This normalized crosstab is the observed-data version of the joint probability tables in the next section. The same correspondence held for one-variable distributions in <a href="prob_02_probability-basics.html#sec-prob-distributions" class="quarto-xref"><span>Section 7.4</span></a>: probabilities for future outcomes follow the same structure as proportions in observed data. Here it extends to two variables.</p>
</section>
<section id="sec-loan-probability-model" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="sec-loan-probability-model"><span class="header-section-number">10.3</span> A probability model for future loans</h2>
<p>So far we have read <a href="#tbl-purpose-default-joint" class="quarto-xref">Table&nbsp;<span>10.3</span></a> as a record of what happened to 58,456 historical loans with these three purposes. If those loans are representative of future loans with the same purposes, the table gives estimated probabilities for a future loan drawn from this restricted population.</p>
<div id="defn-joint-distribution" class="Definition">
<div class="Definition fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-book fobx-icon" aria-hidden="true"></i><strong>Definition 10.5: </strong>Joint probability distribution</div><div class="fobx-body">
<p>For two discrete random variables, a <strong>joint probability distribution</strong> assigns a probability to every <em>pair</em> of outcomes. Laid out as a table — one variable in the rows, the other in the columns — it follows the same rules as any probability distribution: every cell is non-negative, and all the cells together sum to one.</p>
</div></div>
</div>
<p>Let <span class="math inline">\(P\)</span> code the purpose of a future loan from this restricted population: <span class="math inline">\(P=1\)</span> for debt consolidation, <span class="math inline">\(P=2\)</span> for home improvement, and <span class="math inline">\(P=3\)</span> for small business. The numbers are labels, not quantities; they let us represent a categorical outcome with a numerical random variable. Let <span class="math inline">\(D\)</span> be the loan’s eventual default indicator. We will use the historical relative frequencies as a probability model for that loan: the probability assigned to each purpose–outcome pair is its count divided by 58,456. For example,</p>
<p><span class="math display">\[
\Pr(\text{small business and default})
= \Pr(P = 3 \text{ and } D = 1)
= \frac{822}{58,456}
= 0.014.
\]</span></p>
<p>Dividing each of the six interior counts by 58,456 produces the complete joint distribution in <a href="#tbl-loan-joint" class="quarto-xref">Table&nbsp;<span>10.4</span></a>.</p>
<div class="cell">
<div id="tbl-loan-joint" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-loan-joint-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.4: The joint probability distribution of purpose and outcome for a future loan from the three-purpose population, estimated from the historical relative frequencies.
</figcaption>
<div aria-describedby="tbl-loan-joint-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Purpose</th>
<th style="text-align: right;">Repaid (D = 0)</th>
<th style="text-align: right;">Default (D = 1)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Debt consolidation (P = 1)</td>
<td style="text-align: right;">0.706</td>
<td style="text-align: right;">0.139</td>
</tr>
<tr class="even">
<td style="text-align: left;">Home improvement (P = 2)</td>
<td style="text-align: right;">0.088</td>
<td style="text-align: right;">0.012</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Small business (P = 3)</td>
<td style="text-align: right;">0.041</td>
<td style="text-align: right;">0.014</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The six cells cover every possible purpose–outcome pair in this model, and their probabilities add to 1. This is Rule 2 from <a href="prob_02_probability-basics.html#sec-prob-rules" class="quarto-xref"><span>Section 7.2</span></a>: one of these pairs must occur.</p>
<p>Rule 3 lets us add probabilities for mutually exclusive pairs. In this model, a loan can default as a debt-consolidation, home-improvement, or small-business loan, so</p>
<p><span class="math display">\[
\begin{aligned}
\Pr(D = 1)
&amp;= \Pr(P = 1 \text{ and } D = 1)
+ \Pr(P = 2 \text{ and } D = 1)
+ \Pr(P = 3 \text{ and } D = 1) \\
&amp;= 0.139
+ 0.012
+ 0.014 \\
&amp;= 0.165.
\end{aligned}
\]</span></p>
<p>The probability of default is therefore the sum of the three joint probabilities in the default column.</p>
<div id="defn-marginal-distribution" class="Definition">
<div class="Definition fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-book fobx-icon" aria-hidden="true"></i><strong>Definition 10.6: </strong>Marginal probability distribution</div><div class="fobx-body">
<p>A <strong>marginal probability distribution</strong> gives the probability distribution of one variable on its own. We obtain it from a joint distribution by summing over all possible outcomes of the other variable.</p>
</div></div>
</div>
<p>Adding the row and column sums to <a href="#tbl-loan-joint" class="quarto-xref">Table&nbsp;<span>10.4</span></a> gives both marginal distributions.</p>
<div class="cell">
<div id="tbl-loan-joint-margins" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-loan-joint-margins-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.5: The joint probability distribution with the marginal distributions of purpose and outcome added in the right column and bottom row.
</figcaption>
<div aria-describedby="tbl-loan-joint-margins-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Purpose</th>
<th style="text-align: right;">Repaid (D = 0)</th>
<th style="text-align: right;">Default (D = 1)</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Debt consolidation (P = 1)</td>
<td style="text-align: right;">0.706</td>
<td style="text-align: right;">0.139</td>
<td style="text-align: right;">0.845</td>
</tr>
<tr class="even">
<td style="text-align: left;">Home improvement (P = 2)</td>
<td style="text-align: right;">0.088</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: right;">0.100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Small business (P = 3)</td>
<td style="text-align: right;">0.041</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.055</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: right;">0.835</td>
<td style="text-align: right;">0.165</td>
<td style="text-align: right;">1.000</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>These one-variable distributions appear in the margins of the joint table, which is where the name <em>marginal</em> comes from. For example, summing the two small-business joint probabilities gives its marginal probability:</p>
<p><span class="math display">\[
\Pr(P = 3)
= 0.041
+ 0.014
= 0.055.
\]</span></p>
<p>The marginal distribution of <span class="math inline">\(D\)</span> answers “what is the default probability for a future loan with one of these three purposes before we know which one?” But it deliberately averages over purposes, and we know from <a href="#tbl-default-rate-by-purpose" class="quarto-xref">Table&nbsp;<span>10.2</span></a> that purpose matters. The sharper question is conditional: <em>given</em> that the loan is for a small business, what is the chance it defaults?</p>
<section id="conditional-probability" class="level3" data-number="10.3.1">
<h3 data-number="10.3.1" class="anchored" data-anchor-id="conditional-probability"><span class="header-section-number">10.3.1</span> Conditional probability</h3>
<div id="defn-conditional-probability-joint" class="Definition">
<div class="Definition fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-book fobx-icon" aria-hidden="true"></i><strong>Definition 10.7: </strong>Conditional probability</div><div class="fobx-body">
<p>For events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> with <span class="math inline">\(\Pr(B) &gt; 0\)</span>, the <strong>conditional probability of <span class="math inline">\(A\)</span> given <span class="math inline">\(B\)</span></strong> is</p>
<p><span class="math display">\[
\Pr(A \mid B) = \frac{\Pr(A \text{ and } B)}{\Pr(B)}.
\]</span></p>
<p>The bar “<span class="math inline">\(\mid\)</span>” reads “given that” or “conditional on.” To condition on <span class="math inline">\(B\)</span>, keep only the probability that is consistent with <span class="math inline">\(B\)</span> and rescale it so it sums to one again. That is what dividing the joint probability by the marginal probability of <span class="math inline">\(B\)</span> does.</p>
</div></div>
</div>
<p>The formula is exactly the joint-over-marginal arithmetic we did with proportions in <a href="#sec-joint-marginal-conditional-proportions" class="quarto-xref"><span>Section 10.2</span></a>, now stated as a definition.</p>
<p>On the table, conditioning is a two-step procedure: keep the row or column consistent with the condition, then <em>renormalize</em> the remaining probabilities by dividing by their total. Conditioning on <span class="math inline">\(P = 3\)</span> keeps the small-business row. Its total is the marginal probability <span class="math inline">\(\Pr(P = 3)\)</span>. Dividing each joint probability in that row by <span class="math inline">\(\Pr(P = 3)\)</span> gives the conditional distribution in <a href="#tbl-small-business-conditional" class="quarto-xref">Table&nbsp;<span>10.6</span></a>.</p>
<div class="cell">
<div id="tbl-small-business-conditional" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-small-business-conditional-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.6: The conditional distribution of default status for a future small-business loan. Joint and marginal probabilities are rounded to four decimals; conditional probabilities are computed from the unrounded model.
</figcaption>
<div aria-describedby="tbl-small-business-conditional-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 33%">
<col style="width: 21%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Outcome</th>
<th style="text-align: left;">Meaning</th>
<th style="text-align: right;">Joint probability in the <span class="math inline">\(P = 3\)</span> row</th>
<th style="text-align: right;">Divide by <span class="math inline">\(\Pr(P = 3)\)</span></th>
<th style="text-align: right;">Conditional probability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(D = 0\)</span></td>
<td style="text-align: left;">Loan is repaid</td>
<td style="text-align: right;">0.0405</td>
<td style="text-align: right;">0.0405 / 0.0546</td>
<td style="text-align: right;">0.742</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(D = 1\)</span></td>
<td style="text-align: left;">Loan defaults</td>
<td style="text-align: right;">0.0141</td>
<td style="text-align: right;">0.0141 / 0.0546</td>
<td style="text-align: right;">0.258</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: right;">0.0546</td>
<td style="text-align: right;">0.0546 / 0.0546</td>
<td style="text-align: right;">1.000</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Together, the probabilities 0.742 and 0.258 form the conditional distribution of <span class="math inline">\(D\)</span> given <span class="math inline">\(P = 3\)</span>. Because this probability model uses the historical relative frequencies, they match the conditional proportions computed from counts in <a href="#sec-crosstabs" class="quarto-xref"><span>Section 10.1</span></a>; <a href="prob_02_probability-basics.html#sec-prob-distributions" class="quarto-xref"><span>Section 7.4</span></a> rounded the default probability to 0.25 for its introductory example.</p>
<p>Among the three purposes, small-business loans have the largest default probability: <span class="math inline">\(\Pr(D = 1 \mid P = 3) =
0.258\)</span>. This is the relevant comparison when we ask which loan purpose has the greatest default risk.</p>
<p>The reverse conditional answers a different question: among the loans that defaulted, what share were for small businesses?</p>
<p><span class="math display">\[
\Pr(P = 3 \mid D = 1)
= \frac{822}{9,670}
= 0.085.
\]</span></p>
<p>Small-business loans account for only 0.055 of all loans. Even with the largest default risk, they make up only 0.085 of the defaulted loans.</p>
<p>Most defaulted loans are debt-consolidation loans:</p>
<p><span class="math display">\[
\Pr(P = 1 \mid D = 1)
= \frac{8,131}{9,670}
= 0.841.
\]</span></p>
<p>Debt-consolidation loans have a lower default probability, <span class="math inline">\(\Pr(D = 1 \mid P = 1) =
0.165\)</span>, but they account for 0.845 of all loans. Their large base rate explains why they also account for most defaults.</p>
<div id="exercise-complete-renewal-model" class="Exercise">
<div class="Exercise fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-pencil-square fobx-icon" aria-hidden="true"></i><strong>Exercise 10.2: </strong>Complete a renewal model</div><div class="fobx-body">
<p>A subscription company uses the following joint probability model for a randomly selected customer next year. One probability is missing.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Current tier</th>
<th style="text-align: right;">Renews</th>
<th style="text-align: right;">Does not renew</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Basic</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">0.70</td>
</tr>
<tr class="even">
<td>Premium</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">?</td>
<td style="text-align: right;">0.30</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;">?</td>
<td style="text-align: right;">?</td>
<td style="text-align: right;"><strong>1.00</strong></td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Find the missing Premium/Does not renew joint probability.</li>
<li>Complete the marginal distribution of renewal status.</li>
<li>Find the conditional distribution of renewal status for Basic customers.</li>
<li>Find the conditional distribution of renewal status for Premium customers.</li>
<li>Find <span class="math inline">\(\Pr(\text{Premium}\mid\text{Renews})\)</span>.</li>
<li>An analyst says 0.24 is the Premium renewal rate. Explain what 0.24 represents and give the Premium renewal rate.</li>
</ol>
<details class="solution-details" id="solution-complete-renewal-model" aria-label="Solution">
<summary>Solution</summary>
<p>The Premium row must sum to its marginal probability of 0.30, so the missing joint probability is</p>
<p><span class="math display">\[
0.30-0.24=0.06.
\]</span></p>
<p>Adding down the columns gives the marginal renewal distribution:</p>
<p><span class="math display">\[
\Pr(\text{Renews})=0.42+0.24=0.66,
\qquad
\Pr(\text{Does not renew})=0.28+0.06=0.34.
\]</span></p>
<p>The completed joint probability model is</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Current tier</th>
<th style="text-align: right;">Renews</th>
<th style="text-align: right;">Does not renew</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Basic</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">0.70</td>
</tr>
<tr class="even">
<td>Premium</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.30</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>0.66</strong></td>
<td style="text-align: right;"><strong>0.34</strong></td>
<td style="text-align: right;"><strong>1.00</strong></td>
</tr>
</tbody>
</table>
<p>For Basic customers, divide the two joint probabilities in the Basic row by the row’s marginal probability, 0.70:</p>
<p><span class="math display">\[
\Pr(\text{Renews}\mid\text{Basic})=\frac{0.42}{0.70}=0.60,
\qquad
\Pr(\text{Does not renew}\mid\text{Basic})=\frac{0.28}{0.70}=0.40.
\]</span></p>
<p>For Premium customers, divide by 0.30:</p>
<p><span class="math display">\[
\Pr(\text{Renews}\mid\text{Premium})=\frac{0.24}{0.30}=0.80,
\qquad
\Pr(\text{Does not renew}\mid\text{Premium})=\frac{0.06}{0.30}=0.20.
\]</span></p>
<p>Among renewing customers, the Premium share is</p>
<p><span class="math display">\[
\Pr(\text{Premium}\mid\text{Renews})=\frac{0.24}{0.66}=0.3636.
\]</span></p>
<p>The value 0.24 is the joint probability that a customer is Premium and renews. The Premium renewal rate conditions on Premium customers, so it is <span class="math inline">\(0.24/0.30=0.80\)</span>.</p>
</details>
</div></div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Common mistake: <span class="math inline">\(\Pr(A \mid B)\)</span> and <span class="math inline">\(\Pr(B \mid A)\)</span> are different numbers
</div>
</div>
<div class="callout-body-container callout-body">
<p>Conditional probabilities are asymmetric. The two share a numerator — the joint probability of <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> — but divide it by different <em>base rates</em> (marginal probabilities), so one can be tiny while the other is close to one.</p>
</div>
</div>
<p>Most tall people aren’t in the NBA, but most people in the NBA are tall: <span class="math inline">\(\Pr(\text{NBA} \mid \text{tall})\)</span> is minuscule while <span class="math inline">\(\Pr(\text{tall} \mid \text{NBA})\)</span> is close to one. Mathematically,</p>
<p><span class="math display">\[
\Pr(\text{NBA} \mid \text{tall}) = \frac{\Pr(\text{NBA and tall})}{\Pr(\text{tall})},
\qquad
\Pr(\text{tall} \mid \text{NBA}) = \frac{\Pr(\text{NBA and tall})}{\Pr(\text{NBA})}.
\]</span></p>
<p>Adult heights are roughly normal, so about half of adults are taller than average. The first conditional therefore divides a tiny joint probability by about 0.5 and stays tiny. The second divides that same joint probability by the much smaller probability of being in the NBA, producing a conditional probability near 1.</p>
</section>
</section>
<section id="data-used-in-this-section" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="data-used-in-this-section">Data used in this section</h2>
<ul>
<li><a href="./appendix_data.html#sec-data-lendingclub-kaggle">LendingClub Accepted Loans</a></li>
<li><a href="./appendix_data.html#sec-data-wfh-bloom">Bloom, Han &amp; Liang Hybrid WFH Experiment</a></li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-wfh-bloom" class="csl-entry" role="listitem">
Bloom, Nicholas, Ruobing Han, and James Liang. 2024. <span>“Hybrid Working from Home Improves Retention Without Damaging Performance.”</span> <em>Nature</em> 630 (8018): 920–25. <a href="https://doi.org/10.1038/s41586-024-07500-2">https://doi.org/10.1038/s41586-024-07500-2</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./prob_04_normal.html" class="pagination-link" aria-label="The Normal Distribution">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">The Normal Distribution</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./prob_06_probability-trees-bayes.html" class="pagination-link" aria-label="Probability Trees, Total Probability, and Bayes' Rule">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability Trees, Total Probability, and Bayes’ Rule</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>