<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; Measures of Location and Spread (and Other Parameters of Probability Distributions) – TEMBA Statistics — Course Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./prob_04_normal.html" rel="next">
<link href="./prob_02_probability-basics.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d3f7f8e73c8d287b30bcf59c2b563615.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/foldbox/foldbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>
.TechnicalDetail {
  --color1: #EEF1F3;
  --color2: #5B6770;
}
.Exercise {
  --color1: #E7F4F5;
  --color2: #147D85;
}
.Definition {
  --color1: #F4EAF0;
  --color2: #7C3F58;
}
.Notation {
  --color1: #EEF1F3;
  --color2: #5B6770;
}
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles/callouts.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./prob_01_intro.html">Probability for one variable</a></li><li class="breadcrumb-item"><a href="./prob_03_distribution-parameters.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Measures of Location and Spread (and Other Parameters of Probability Distributions)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">TEMBA Statistics — Course Notes</a> 
        <div class="sidebar-tools-main">
    <a href="./../index.html" title="Course site" class="quarto-navigation-tool px-1" aria-label="Course site"><i class="bi bi-house-door"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Data analysis and visualization for one variable</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_01_visualizing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Visualizing a Single Quantitative Variable</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_02_describing-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Distributions of Quantitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_03_location-and-spread.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Measuring Location and Spread</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_04_transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Transforming Quantitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./singlevar_05_categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Categorical Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Probability for one variable</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_01_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introduction to Probability and Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_02_probability-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Probability Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_03_distribution-parameters.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Measures of Location and Spread (and Other Parameters of Probability Distributions)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob_04_normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">The Normal Distribution</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-rv-mean" id="toc-sec-rv-mean" class="nav-link active" data-scroll-target="#sec-rv-mean"><span class="header-section-number">8.1</span> The mean of a random variable</a></li>
  <li><a href="#sec-rv-variance" id="toc-sec-rv-variance" class="nav-link" data-scroll-target="#sec-rv-variance"><span class="header-section-number">8.2</span> Variance and standard deviation</a>
  <ul class="collapse">
  <li><a href="#sec-risk" id="toc-sec-risk" class="nav-link" data-scroll-target="#sec-risk"><span class="header-section-number">8.2.1</span> Variance/Standard deviation measure unpredictability (risk)</a></li>
  </ul></li>
  <li><a href="#sec-rv-quantiles" id="toc-sec-rv-quantiles" class="nav-link" data-scroll-target="#sec-rv-quantiles"><span class="header-section-number">8.3</span> Quantiles and the IQR</a></li>
  <li><a href="#sec-shift-scale" id="toc-sec-shift-scale" class="nav-link" data-scroll-target="#sec-shift-scale"><span class="header-section-number">8.4</span> Shifting and scaling</a></li>
  <li><a href="#continuous-random-variables" id="toc-continuous-random-variables" class="nav-link" data-scroll-target="#continuous-random-variables"><span class="header-section-number">8.5</span> Continuous random variables</a></li>
  <li><a href="#data-used-in-this-section" id="toc-data-used-in-this-section" class="nav-link" data-scroll-target="#data-used-in-this-section">Data used in this section</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./prob_01_intro.html">Probability for one variable</a></li><li class="breadcrumb-item"><a href="./prob_03_distribution-parameters.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Measures of Location and Spread (and Other Parameters of Probability Distributions)</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Measures of Location and Spread (and Other Parameters of Probability Distributions)</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The introduction to this part defined a <strong>parameter</strong> as a feature of a probability distribution. The mean, median, standard deviation, and quantiles we computed on columns of data all have exact counterparts computed on probability distributions. The formulas look almost the same. The only real change is what gets averaged: instead of summing over observations we have, we sum over outcomes that <em>could</em> happen, each weighted by its probability.</p>
<section id="sec-rv-mean" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="sec-rv-mean"><span class="header-section-number">8.1</span> The mean of a random variable</h2>
<div id="defn-expected-value" class="Definition">
<div class="Definition fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-book fobx-icon" aria-hidden="true"></i><strong>Definition 8.1: </strong>Mean (expected value) of a random variable</div><div class="fobx-body">
<p>The <strong>mean</strong> of a random variable, also called its <strong>expected value</strong>, is a weighted average of its possible outcomes, with each outcome weighted by its probability. For a discrete random variable <span class="math inline">\(X\)</span> with possible outcomes <span class="math inline">\(x_1, x_2, \dots, x_k\)</span>,</p>
<p><span class="math display">\[
E[X] = \Pr(X = x_1)\,x_1 + \dots + \Pr(X = x_k)\,x_k
     = \sum_{i=1}^{k} \Pr(X = x_i)\,x_i.
\]</span></p>
<p>We often write <span class="math inline">\(\mu\)</span> for it: <span class="math inline">\(E[X] = \mu\)</span>. The expected value is the long-run average outcome when the random process repeats many times.</p>
</div></div>
</div>
<p>Compare this to the <strong>sample mean</strong> we computed in <a href="singlevar_03_location-and-spread.html#sec-measures-center" class="quarto-xref"><span>Section 3.1</span></a>, which adds up the observed values and gives each one weight <span class="math inline">\(1/n\)</span>. We can think of that as an expected value too, with respect to a probability distribution that puts probability <span class="math inline">\(1/n\)</span> on each observed value. When the data contain ties — as for a binary variable like our default indicator — we can collapse the sample mean to a weighted average of the distinct observed values, which looks even more like the formula above.</p>
<p>As a simple first example consider the outcome of a single fair coin toss. Let <span class="math inline">\(H = 1\)</span> if the coin lands heads and <span class="math inline">\(H = 0\)</span> otherwise, so <span class="math inline">\(E[H] = 0.5 \times 1 + 0.5 \times 0 = 0.5\)</span>. At first blush this looks odd — the random variable only takes the values zero or one, so what does it mean to <em>expect</em> a value we can’t see? Well, imagine flipping that coin many times over, say 1,000 times. The <em>average</em> of your thousand 0s and 1s will land very close to 0.5. Flip the coin for long enough and the average outcome will get arbitrarily close to 0.5.</p>
<p>A slightly less abstract example: The default indicator <span class="math inline">\(D\)</span> for a new small-business loan has <span class="math inline">\(E[D] = 0.75 \times 0 + 0.25 \times 1 = 0.25\)</span> — the expected value of <em>any</em> 0/1 random variable is just the probability of a 1, the model version of the proportion-is-a-mean fact from <a href="singlevar_05_categorical.html#sec-proportion-mean" class="quarto-xref"><span>Section 5.4</span></a>. In the long run, we expect about 25% of small-business loans to fail under this model.</p>
<p>A similar calculation gives the expected payoff <span class="math inline">\(E[X]\)</span> on the $10,000 loan at 12% interest:</p>
<div class="cell">
<div id="tbl-payoff-ev" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-payoff-ev-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.1: Computing the expected payoff of a $10,000 small-business loan at 12% interest. Each row multiplies an outcome by its probability; the expected value is the sum.
</figcaption>
<div aria-describedby="tbl-payoff-ev-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Outcome</th>
<th style="text-align: right;">Probability</th>
<th style="text-align: right;">Probability × outcome</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Repaid: $11,200</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">$8,400</td>
</tr>
<tr class="even">
<td style="text-align: left;">Default: $6,000</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">$1,500</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Expected value</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">$9,900</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The lender expects to collect $9,900 per loan, in the long-run-average sense: if we could fund many independent loans with this profile, the average payoff per loan will settle near $9,900. Whether that is good news depends on what the loan cost. Subtracting the $10,000 principal turns payoffs into <em>profits</em> — a gain of $1,200 if repaid, a loss of $4,000 if not — and the expected profit is the expected payoff minus the principal: $9,900 <span class="math inline">\(-\)</span> $10,000 = -$100. At 12% interest, this loan <em>loses</em> $100 on average. A lender who funds 100 independent loans like it should expect to end up about $10,000 in the hole.</p>
<p>At 16% interest instead, the payoff when repaid becomes $11,600, the expected payoff rises to $10,200, and the expected profit is now a positive $200 per loan. How far an actual portfolio might stray from that expectation is a question we’ll answer precisely when we combine random variables later in the course. It would be a bad idea in the long run to write loans where we expect to lose money.</p>
<p>For one more example, let’s revisit the FedWatch target-range probabilities from <a href="prob_01_intro.html#sec-what-is-probability" class="quarto-xref"><span>Section 6.1</span></a> and <a href="prob_02_probability-basics.html#sec-prob-distributions" class="quarto-xref"><span>Section 7.4</span></a>. The probability distributions over target ranges after the July and September meetings are:</p>
<div id="tbl-cme-params" class="quarto-layout-panel anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cme-params-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.2: Market-implied distributions for the FOMC target range (CME FedWatch, July 9, 2026), with each range’s midpoint and its probability.
</figcaption>
<div aria-describedby="tbl-cme-params-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="tbl-cme-params" style="flex-basis: 50.0%;justify-content: center;">
<div id="tbl-cme-params-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-tbl figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-tbl" id="tbl-cme-params-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) July 29 meeting
</figcaption>
<div aria-describedby="tbl-cme-params-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="tbl-cme-params-1" class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Target range</th>
<th style="text-align: right;">Midpoint</th>
<th style="text-align: right;">Probability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3.50–3.75%</td>
<td style="text-align: right;">3.625%</td>
<td style="text-align: right;">0.759</td>
</tr>
<tr class="even">
<td style="text-align: left;">3.75–4.00%</td>
<td style="text-align: right;">3.875%</td>
<td style="text-align: right;">0.241</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="tbl-cme-params" style="flex-basis: 50.0%;justify-content: center;">
<div id="tbl-cme-params-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-tbl figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-tbl" id="tbl-cme-params-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) September 16 meeting
</figcaption>
<div aria-describedby="tbl-cme-params-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="tbl-cme-params-2" class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Target range</th>
<th style="text-align: right;">Midpoint</th>
<th style="text-align: right;">Probability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3.50–3.75%</td>
<td style="text-align: right;">3.625%</td>
<td style="text-align: right;">0.366</td>
</tr>
<tr class="even">
<td style="text-align: left;">3.75–4.00%</td>
<td style="text-align: right;">3.875%</td>
<td style="text-align: right;">0.509</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4.00–4.25%</td>
<td style="text-align: right;">4.125%</td>
<td style="text-align: right;">0.125</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
</div>
</figure>
</div>
<p>Weighting midpoints by probabilities gives an implied <em>expected</em> target-range midpoint of 3.685% after the July meeting and 3.815% after September.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Common mistake: An expected value need not be a possible outcome
</div>
</div>
<div class="callout-body-container callout-body">
<p>The mean of a random variable is a probability-weighted average, and averages land between outcomes as often as on them. As with the coin toss above — <span class="math inline">\(E[H] = 0.5\)</span> never occurs — the market-implied expected target-range midpoint of 3.685% is not the midpoint of any range the Fed can set: the target range moves in quarter-point steps, and 3.685% falls between two of the midpoints.</p>
</div>
</div>
<p>The expected increases over the current midpoint of 3.625% are 0.060 and 0.190 percentage points — about 6 and 19 basis points, in the units rate-watchers use (one basis point is a hundredth of a percentage point).</p>
</section>
<section id="sec-rv-variance" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="sec-rv-variance"><span class="header-section-number">8.2</span> Variance and standard deviation</h2>
<p>Like the sample variance computed with observed data, the variance of a random variable measures the average <em>squared</em> deviation from the mean. As with the mean, the average is weighted by each outcome’s probability.</p>
<div id="defn-rv-variance" class="Definition">
<div class="Definition fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-book fobx-icon" aria-hidden="true"></i><strong>Definition 8.2: </strong>Variance and standard deviation of a random variable</div><div class="fobx-body">
<p>The <strong>variance</strong> of a random variable <span class="math inline">\(X\)</span> with mean <span class="math inline">\(\mu\)</span> is the probability-weighted average of squared deviations from the mean. For a discrete random variable with possible outcomes <span class="math inline">\(x_1, \dots, x_k\)</span>,</p>
<p><span class="math display">\[
\text{Var}(X) = \sum_{i=1}^{k} \Pr(X = x_i)\,(x_i - \mu)^2.
\]</span></p>
<p>We write <span class="math inline">\(\sigma^2 = \text{Var}(X)\)</span>. The <strong>standard deviation</strong> is its square root, <span class="math inline">\(SD(X) = \sigma = \sqrt{\text{Var}(X)}\)</span>. Just like its sample counterpart, the standard deviation is in the same units as <span class="math inline">\(X\)</span> and can be interpreted as a typical distance from the mean.</p>
</div></div>
</div>
<p>In words: the variance is the expected squared distance between the random variable and its mean — how wrong, on the squared-error scale, we expect to be if we predict <span class="math inline">\(X\)</span> by <span class="math inline">\(\mu\)</span>. For the 16% loan, the payoff sits $1,400 above its mean of $10,200 when the loan is repaid and $4,200 below it on default, so</p>
<p><span class="math display">\[
\text{Var}(X) = 0.75 \times (1{,}400)^2 + 0.25 \times (-4{,}200)^2 = 5{,}880{,}000,
\]</span></p>
<p>and taking the square root brings us back to dollars: <span class="math inline">\(SD(X)\)</span> = $2,425. The standard deviation combines the two possible deviations — $1,400 when the loan is repaid and $4,200 when it defaults — into one probability-weighted measure of spread. The interpretation is the one we built for data in <a href="singlevar_03_location-and-spread.html#sec-measures-spread" class="quarto-xref"><span>Section 3.2</span></a>: a bigger standard deviation means a less predictable outcome.</p>
<div id="notation-parameters-and-statistics" class="Notation">
<div class="Notation fobx-simplebox fobx-default fobx-static"><div class="fobx-title"><i class="bi bi-braces fobx-icon" aria-hidden="true"></i><strong>Notation 8.1: </strong>Random variables, parameters, and statistics</div><div class="fobx-body">
<ul>
<li>Capital letters name random variables (<span class="math inline">\(X\)</span>, <span class="math inline">\(Y\)</span>, <span class="math inline">\(D\)</span>).</li>
<li>Lowercase letters name particular values they might take (<span class="math inline">\(x\)</span>, <span class="math inline">\(y\)</span>).</li>
<li>Greek letters name parameters of a true probability or population distribution: <span class="math inline">\(\mu\)</span> for its mean, <span class="math inline">\(\sigma^2\)</span> for its variance, <span class="math inline">\(\sigma\)</span> for its standard deviation.</li>
<li>Lowercase Latin letters denote quantities computed from a single observed sample: <span class="math inline">\(\bar{x}\)</span> for a sample mean, <span class="math inline">\(s^2\)</span> and <span class="math inline">\(s\)</span> for a sample variance and standard deviation. They are lowercase because they are already-observed numbers, not random.</li>
<li>Uppercase Latin letters like <span class="math inline">\(\bar X\)</span> denote a quantity computed on a <em>random</em> sample — in this case, the mean of that random sample. They’re random variables because they’re uncertain due to the random sampling. We’ll work with <span class="math inline">\(\bar X\)</span> when we average random variables later in the course.</li>
</ul>
<p>When you see a Greek letter, it refers to something unknown we’re trying to estimate. When you see a Latin letter, we have computed it (or could compute it) from data. Lowercase Latin letters (<span class="math inline">\(\bar{x}\)</span>, <span class="math inline">\(s\)</span>) are numbers we computed from our observed sample; uppercase Latin letters like <span class="math inline">\(\bar{X}\)</span> are random variables, because the samples they depend on are random.</p>
</div></div>
</div>
<section id="sec-risk" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="sec-risk"><span class="header-section-number">8.2.1</span> Variance/Standard deviation measure unpredictability (risk)</h3>
<p>As in <a href="singlevar_03_location-and-spread.html#sec-measures-spread" class="quarto-xref"><span>Section 3.2</span></a>, the spread of a probability distribution represents unpredictability or risk. The standard deviation is high when there is substantial probability placed on outcomes that are far from the expected value (the mean). Here are two hypothetical $10,000 loans with the same expected profit but different risk profiles. Both assume that the lender recovers $6,000 if the borrower defaults:</p>
<div class="cell">
<div id="tbl-loan-risk" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-loan-risk-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.3: Two loans with the same expected profit and different risk. Loan A charges a higher rate to a riskier borrower; Loan B charges a lower rate to a safer one.
</figcaption>
<div aria-describedby="tbl-loan-risk-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 39%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Loan A (riskier borrower, 14%)</th>
<th style="text-align: right;">Loan B (safer borrower, 8%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Profit if repaid</td>
<td style="text-align: right;">$1,400</td>
<td style="text-align: right;">$800</td>
</tr>
<tr class="even">
<td style="text-align: left;">Profit if default</td>
<td style="text-align: right;">-$4,000</td>
<td style="text-align: right;">-$4,000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Default probability</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Expected profit</td>
<td style="text-align: right;">$320</td>
<td style="text-align: right;">$320</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Standard deviation</td>
<td style="text-align: right;">$2,160</td>
<td style="text-align: right;">$1,440</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-loan-risk" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-loan-risk-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob_03_distribution-parameters_files/figure-html/fig-loan-risk-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-loan-risk-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.1: The two loans’ profit distributions on a common scale, with expected profits marked by dashed lines.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Interpretation: standard deviation as unpredictability (risk)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Loan A and Loan B have the same expected profit of $320, so expected value alone cannot choose between them. Their standard deviations can: $2,160 for Loan A against $1,440 for Loan B. Loan A places more probability on outcomes far from that shared average in both directions, which is what a lender means by calling it the riskier loan. Writing many loans like either one is profitable in the long run, provided defaults are close to independent — but a lender choosing between them gets one draw. At the same expected profit, a risk-averse lender takes Loan B.</p>
</div>
</div>
<p>Both loans’ long-run profitability rests on defaults being at least close to independent: one borrower’s failure tells us nothing about the others. We’ll define independence carefully later in the course.</p>
<p>The same comparison drives how investors think about other investments. Two stocks can have return distributions with the same expected return but very different standard deviations; <a href="#fig-stock-risk" class="quarto-xref">Figure&nbsp;<span>8.2</span></a> shows such a pair.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-stock-risk" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stock-risk-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob_03_distribution-parameters_files/figure-html/fig-stock-risk-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stock-risk-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.2: Return distributions for two hypothetical stocks with the same expected return.
</figcaption>
</figure>
</div>
</div>
</div>
<p>You might be happy to hold the more volatile stock in your 401k if you’re young, but the less time you have left to let your portfolio grow, the less attractive this option becomes.</p>
</section>
</section>
<section id="sec-rv-quantiles" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="sec-rv-quantiles"><span class="header-section-number">8.3</span> Quantiles and the IQR</h2>
<p>Percentiles and quantiles carry over from data to distributions the same way. The <span class="math inline">\(p\)</span>-th quantile of a distribution is the smallest value where the cumulative probability reaches or exceeds <span class="math inline">\(p\)</span>. For example: the <strong>median</strong> of a distribution is its 0.5 quantile: the smallest value where the cumulative probability reaches or exceeds 0.50. For our house price model, the median is $488,127:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-price-median" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-price-median-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob_03_distribution-parameters_files/figure-html/fig-price-median-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-price-median-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.3: The median of the Austin price model. Left: the density with exactly half its area shaded, up to the median. Right: the CDF crossing cumulative probability 0.50 at the same price.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Just as we discussed in <a href="singlevar_03_location-and-spread.html#sec-measures-center" class="quarto-xref"><span>Section 3.1</span></a>, the median can be a more robust measure of center than the mean for a skewed probability distribution; in the model above, the mean price is $546,458, which is $58,331 <em>above</em> the median. The mean is pulled up by the long right tail of the distribution, just as it was in the observed data.</p>
<p>For a continuous distribution, we can read it off the CDF by finding where the curve crosses height <span class="math inline">\(p\)</span>. The median is the 0.5 quantile, and the <strong>interquartile range</strong> is the distance between the 0.25 and 0.75 quantiles, a spread measure in the units of the variable that ignores the tails entirely.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-price-quantiles" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-price-quantiles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob_03_distribution-parameters_files/figure-html/fig-price-quantiles-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-price-quantiles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.4: Reading quantiles off the CDF of the Austin price model. Horizontal lines at cumulative probabilities 0.25, 0.50, and 0.75 cross the curve above the model’s quartiles and median; the distance between the two outer drop-lines is the IQR.
</figcaption>
</figure>
</div>
</div>
</div>
<p>For the price model, the quartiles land at $354,282 and $672,536, so the IQR is $318,254: under this model, the middle half of future sales falls in a band about $318,254 wide. Quantiles also answer tail questions directly — a seller wondering “what price will I beat with probability 0.75?” wants the 0.25 quantile, not the mean.</p>
</section>
<section id="sec-shift-scale" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="sec-shift-scale"><span class="header-section-number">8.4</span> Shifting and scaling</h2>
<p>Linear transformations of random variables act just like linear transformations applied to columns in our datasets:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Mean, median, and standard deviation of <span class="math inline">\(aX + b\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>If <span class="math inline">\(X\)</span> is a random variable with mean <span class="math inline">\(E[X] = \mu\)</span> and standard deviation <span class="math inline">\(SD(X) = \sigma\)</span>, and <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> are known constants, then <span class="math inline">\(Y = aX + b\)</span> has</p>
<p><span class="math display">\[
E[Y] = a\,\mu + b, \qquad \text{median}(Y) = a\,\text{median}(X) + b,
\]</span></p>
<p><span class="math display">\[
SD(Y) = |a|\,\sigma, \qquad Var(Y) = a^2\,\sigma^2.
\]</span></p>
<p>Adding <span class="math inline">\(b\)</span> shifts the center and leaves the spread alone; multiplying by <span class="math inline">\(a\)</span> scales both the center and the spread (and the spread doesn’t care about the sign of <span class="math inline">\(a\)</span>).</p>
</div>
</div>
<p>These are exactly the same rules we encountered for the sample mean, median, and variance/SD in <a href="singlevar_04_transformations.html#sec-linear-transformations" class="quarto-xref"><span>Section 4.1</span></a>.</p>
<p>The profit on our 16% loan is <span class="math inline">\(X - 10{,}000\)</span>, so its mean is $10,200 <span class="math inline">\(-\)</span> $10,000 = $200 and its standard deviation is exactly the payoff’s $2,424.87 — shifting can’t make an uncertain payoff any more or less predictable. Scaling Loan B’s $10,000 principal up to $100,000 sets <span class="math inline">\(a = 10\)</span>: expected profit rises to $3,200, and the standard deviation rises right along with it to $14,400.</p>
<p>We <strong>standardize</strong> a random variable by subtracting the mean and dividing by the standard deviation, producing a new random variable with mean 0 and standard deviation 1:</p>
<p><span class="math display">\[
Z = \frac{X - \mu}{\sigma}.
\]</span></p>
<p>The new random variable <span class="math inline">\(Z\)</span> measures how many standard deviations <span class="math inline">\(X\)</span> sits from its own mean. A realized value of <span class="math inline">\(Z\)</span> is a <strong>z-score</strong> and just like in <a href="singlevar_04_transformations.html#sec-zscores" class="quarto-xref"><span>Section 4.2</span></a> it measures the size of an observed difference <em>relative to</em> a typical difference, as measured by standard deviation.</p>
</section>
<section id="continuous-random-variables" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="continuous-random-variables"><span class="header-section-number">8.5</span> Continuous random variables</h2>
<p>The expected value, variance, and standard deviation are all interpreted the same way for a continuous random variable, but the formulas change from sums to integrals:</p>
<div id="technical-continuous-expectation" class="TechnicalDetail">
<details class="TechnicalDetail fobx-simplebox fobx-default"><summary><strong>Technical detail 8.1: </strong>Mean and variance as integrals</summary><div>
<p>If a continuous random variable <span class="math inline">\(X\)</span> has probability density function <span class="math inline">\(f(x)\)</span> then</p>
<p><span class="math display">\[
E[X] = \int x \, f(x) \, dx, \qquad
\text{Var}(X) = \int (x - \mu)^2 \, f(x) \, dx,
\]</span></p>
<p>and <span class="math inline">\(SD(X) = \sqrt{\text{Var}(X)}\)</span> as always. The integrals play the role the sums played for discrete random variables: they average over every possible outcome, weighting by the density instead of by individual probabilities. The mean and variance of the Austin price model come from integrals of exactly this kind, and software evaluates them.</p>
</div></details>
</div>
<p>The mean is still the long-run average, and the standard deviation still measures how far outcomes typically stray from it. The Austin price model’s standard deviation is the square root of its variance, while its median and quartiles come from the CDF.</p>
</section>
<section id="data-used-in-this-section" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="data-used-in-this-section">Data used in this section</h2>
<ul>
<li><a href="./appendix_data.html#sec-data-housing-kaggle">Austin House Listings</a></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./prob_02_probability-basics.html" class="pagination-link" aria-label="Probability Basics">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Probability Basics</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./prob_04_normal.html" class="pagination-link" aria-label="The Normal Distribution">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">The Normal Distribution</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>